// Due to the extensive length of legal translations, this is a separate file
// These will be imported into the main TranslationContext

export const termsTranslations = {
  // Requirements Section
  termsRequirementsTitle: { EN: "4. Requirements & Compatibility", ES: "4. Requisitos y Compatibilidad", FR: "4. Exigences et Compatibilité", DE: "4. Voraussetzungen & Kompatibilität", RU: "4. Требования и совместимость", ZH: "4. 要求和兼容性", JA: "4. 要件と互換性", PT: "4. Requisitos e Compatibilidade", AR: "4. المتطلبات والتوافق", IT: "4. Requisiti e Compatibilità" },
  termsRequirementsContent: { EN: "The customer is solely responsible for:", ES: "El cliente es el único responsable de:", FR: "Le client est seul responsable de :", DE: "Der Kunde ist allein verantwortlich für:", RU: "Клиент несет единоличную ответственность за:", ZH: "客户独自负责：", JA: "顧客は以下に対して単独で責任を負います：", PT: "O cliente é o único responsável por:", AR: "العميل وحده المسؤول عن:", IT: "Il cliente è l'unico responsabile di:" },
  termsRequirementsItem1: { EN: "An eSIM-compatible device (iOS/Android)", ES: "Un dispositivo compatible con eSIM (iOS/Android)", FR: "Un appareil compatible eSIM (iOS/Android)", DE: "Ein eSIM-kompatibles Endgerät (iOS/Android)", RU: "Устройство, совместимое с eSIM (iOS/Android)", ZH: "兼容 eSIM 的设备 (iOS/Android)", JA: "eSIM 対応デバイス (iOS/Android)", PT: "Um dispositivo compatível com eSIM (iOS/Android)", AR: "جهاز متوافق مع eSIM (iOS/Android)", IT: "Un dispositivo compatibile con eSIM (iOS/Android)" },
  termsRequirementsItem2: { EN: "An updated operating system", ES: "Un sistema operativo actualizado", FR: "Un système d'exploitation à jour", DE: "Aktuelle Firmware", RU: "Обновленная операционная система", ZH: "更新的操作系统", JA: "最新のオペレーティングシステム", PT: "Um sistema operacional atualizado", AR: "نظام تشغيل محدث", IT: "Un sistema operativo aggiornato" },
  termsRequirementsItem3: { EN: "Internet access for installation", ES: "Acceso a Internet para la instalación", FR: "Accès Internet pour l'installation", DE: "Aktive Internetverbindung zur Installation", RU: "Доступ к Интернету для установки", ZH: "用于安装的互联网访问", JA: "インストール用のインターネットアクセス", PT: "Acesso à internet para instalação", AR: "الوصول إلى الإنترنت للتثبيت", IT: "Accesso a Internet per l'installazione" },
  termsRequirementsItem4: { EN: "Selecting the correct country/region and data plan", ES: "Seleccionar el país/región y plan de datos correctos", FR: "Sélectionner le bon pays/région et forfait de données", DE: "Korrekte Länder- und Tarifauswahl", RU: "Выбор правильной страны/региона и тарифного плана", ZH: "选择正确的国家/地区和数据套餐", JA: "正しい国/地域とデータプランの選択", PT: "Selecionar o país/região e plano de dados corretos", AR: "اختيار البلد/المنطقة وخطة البيانات الصحيحة", IT: "Selezione del paese/regione e piano dati corretti" },
  termsRequirementsWarning: { EN: "Non-supported devices may include: older iPhone models, various Xiaomi/Oppo/Vivo/Huawei models, rooted devices, modified Android systems.", ES: "Los dispositivos no compatibles pueden incluir: modelos antiguos de iPhone, varios modelos Xiaomi/Oppo/Vivo/Huawei, dispositivos rooteados, sistemas Android modificados.", FR: "Les appareils non pris en charge peuvent inclure : anciens modèles d'iPhone, divers modèles Xiaomi/Oppo/Vivo/Huawei, appareils rootés, systèmes Android modifiés.", DE: "Nicht unterstützte Geräte: Ältere iPhones, viele Xiaomi-, Oppo-, Vivo-, Huawei- oder gerootete Android-Geräte.", RU: "Неподдерживаемые устройства могут включать: старые модели iPhone, различные модели Xiaomi/Oppo/Vivo/Huawei, рутированные устройства, модифицированные системы Android.", ZH: "不受支持的设备可能包括：旧款 iPhone 型号、各种小米/Oppo/Vivo/华为型号、已 root 的设备、修改过的 Android 系统。", JA: "サポートされていないデバイスには、古い iPhone モデル、さまざまな Xiaomi/Oppo/Vivo/Huawei モデル、root 化されたデバイス、改造された Android システムが含まれる場合があります。", PT: "Dispositivos não suportados podem incluir: modelos antigos de iPhone, vários modelos Xiaomi/Oppo/Vivo/Huawei, dispositivos com root, sistemas Android modificados.", AR: "قد تشمل الأجهزة غير المدعومة: طرازات iPhone القديمة، ونماذج Xiaomi/Oppo/Vivo/Huawei المختلفة، والأجهزة المعدلة بصلاحيات الجذر، وأنظمة Android المعدلة.", IT: "I dispositivi non supportati possono includere: modelli iPhone più vecchi, vari modelli Xiaomi/Oppo/Vivo/Huawei, dispositivi rooted, sistemi Android modificati." },
  termsRequirementsNoRefund: { EN: "No replacement or refund is provided if the customer uses an incompatible device, selects the wrong region/zone, or performs the installation incorrectly.", ES: "No se proporciona reemplazo ni reembolso si el cliente usa un dispositivo incompatible, selecciona la región/zona incorrecta o realiza la instalación incorrectamente.", FR: "Aucun remplacement ni remboursement n'est fourni si le client utilise un appareil incompatible, sélectionne la mauvaise région/zone ou effectue l'installation incorrectement.", DE: "Kein Ersatz durch uns, wenn der Kunde ein inkompatibles Gerät besitzt, falsche Region/Zone auswählt oder die Installation falsch durchführt.", RU: "Замена или возмещение не предоставляются, если клиент использует несовместимое устройство, выбирает неправильный регион/зону или выполняет установку неправильно.", ZH: "如果客户使用不兼容的设备、选择错误的地区/区域或安装不正确，将不提供更换或退款。", JA: "顧客が互換性のないデバイスを使用したり、間違った地域/ゾーンを選択したり、インストールを誤って実行した場合、交換や返金は提供されません。", PT: "Nenhuma substituição ou reembolso será fornecido se o cliente usar um dispositivo incompatível, selecionar a região/zona errada ou executar a instalação incorretamente.", AR: "لن يتم توفير أي استبدال أو استرداد إذا استخدم العميل جهازًا غير متوافق، أو اختار منطقة/منطقة خاطئة، أو قام بالتثبيت بشكل غير صحيح.", IT: "Nessuna sostituzione o rimborso sarà fornito se il cliente utilizza un dispositivo incompatibile, seleziona la regione/zona errata o esegue l'installazione in modo errato." },
  
  // Delivery Section
  termsDeliveryTitle: { EN: "5. Technical Delivery", ES: "5. Entrega Técnica", FR: "5. Livraison Technique", DE: "5. Technische Bereitstellung / Lieferung", RU: "5. Техническая доставка", ZH: "5. 技术交付", JA: "5. 技術的配信", PT: "5. Entrega Técnica", AR: "5. التسليم الفني", IT: "5. Consegna Tecnica" },
  termsDeliveryItem1: { EN: "Digital delivery occurs immediately after payment", ES: "La entrega digital ocurre inmediatamente después del pago", FR: "La livraison numérique a lieu immédiatement après le paiement", DE: "Digitale Bereitstellung sofort nach Zahlung", RU: "Цифровая доставка осуществляется сразу после оплаты", ZH: "付款后立即进行数字交付", JA: "デジタル配信は支払い直後に行われます", PT: "A entrega digital ocorre imediatamente após o pagamento", AR: "يتم التسليم الرقمي فورًا بعد الدفع", IT: "La consegna digitale avviene immediatamente dopo il pagamento" },
  termsDeliveryItem2: { EN: "Delivery method: QR code, in-app provisioning, or downloadable profile", ES: "Método de entrega: código QR, aprovisionamiento en la aplicación o perfil descargable", FR: "Méthode de livraison : code QR, provisionnement intégré ou profil téléchargeable", DE: "Via QR-Code, In-App-Provisioning oder Download", RU: "Способ доставки: QR-код, встроенное предоставление или загружаемый профиль", ZH: "交付方式：二维码、应用内配置或可下载的配置文件", JA: "配信方法：QR コード、アプリ内プロビジョニング、またはダウンロード可能なプロファイル", PT: "Método de entrega: código QR, provisionamento no aplicativo ou perfil para download", AR: "طريقة التسليم: رمز QR أو التوفير داخل التطبيق أو ملف تعريف قابل للتنزيل", IT: "Metodo di consegna: codice QR, provisioning in-app o profilo scaricabile" },
  termsDeliveryItem3: { EN: "Delivery is deemed complete once the eSIM profile is provided (not upon activation)", ES: "La entrega se considera completa una vez que se proporciona el perfil eSIM (no al activarse)", FR: "La livraison est considérée comme terminée une fois le profil eSIM fourni (pas lors de l'activation)", DE: "Lieferung gilt als erfüllt, sobald die eSIM bereitgestellt wurde – nicht erst nach Aktivierung", RU: "Доставка считается завершенной после предоставления профиля eSIM (не при активации)", ZH: "一旦提供 eSIM 配置文件，交付即被视为完成（而不是激活时）", JA: "eSIM プロファイルが提供されると配信が完了したとみなされます（アクティベーション時ではありません）", PT: "A entrega é considerada concluída assim que o perfil eSIM é fornecido (não após a ativação)", AR: "يعتبر التسليم مكتملًا بمجرد توفير ملف تعريف eSIM (وليس عند التفعيل)", IT: "La consegna è considerata completa una volta fornito il profilo eSIM (non all'attivazione)" },
  
  // Prices Section
  termsPricesTitle: { EN: "6. Prices, VAT & Crypto Payments", ES: "6. Precios, IVA y Pagos Crypto", FR: "6. Prix, TVA et Paiements Crypto", DE: "6. Preise, Umsatzsteuer & Krypto-Zahlungen", RU: "6. Цены, НДС и криптоплатежи", ZH: "6. 价格、增值税和加密货币支付", JA: "6. 価格、VAT、暗号通貨決済", PT: "6. Preços, IVA e Pagamentos Crypto", AR: "6. الأسعار وضريبة القيمة المضافة ومدفوعات العملات المشفرة", IT: "6. Prezzi, IVA e Pagamenti Crypto" },
  termsPricesVATTitle: { EN: "6.1 Prices & VAT", ES: "6.1 Precios e IVA", FR: "6.1 Prix et TVA", DE: "6.1 Preise & VAT", RU: "6.1 Цены и НДС", ZH: "6.1 价格和增值税", JA: "6.1 価格と VAT", PT: "6.1 Preços e IVA", AR: "6.1 الأسعار وضريبة القيمة المضافة", IT: "6.1 Prezzi e IVA" },
  termsPricesVATItem1: { EN: "All prices are in EUR including VAT", ES: "Todos los precios están en EUR incluyendo IVA", FR: "Tous les prix sont en EUR TTC", DE: "Alle Preise in EUR inkl. MwSt.", RU: "Все цены указаны в EUR с учетом НДС", ZH: "所有价格均以欧元计，含增值税", JA: "すべての価格は VAT 込みの EUR です", PT: "Todos os preços estão em EUR incluindo IVA", AR: "جميع الأسعار بالدولار مع ضريبة القيمة المضافة", IT: "Tutti i prezzi sono in EUR IVA inclusa" },
  termsPricesVATItem2: { EN: "VAT is applied according to the customer's EU Member State (OSS scheme)", ES: "El IVA se aplica según el Estado miembro de la UE del cliente (esquema OSS)", FR: "La TVA est appliquée selon l'État membre de l'UE du client (système OSS)", DE: "VAT nach dem EU-Land des Kunden (OSS)", RU: "НДС применяется в соответствии с государством-членом ЕС клиента (схема OSS)", ZH: "根据客户的欧盟成员国应用增值税（OSS 计划）", JA: "VAT は顧客の EU 加盟国に従って適用されます（OSS スキーム）", PT: "O IVA é aplicado de acordo com o Estado-Membro da UE do cliente (esquema OSS)", AR: "يتم تطبيق ضريبة القيمة المضافة وفقًا لدولة الاتحاد الأوروبي العضو للعميل (نظام OSS)", IT: "L'IVA è applicata secondo lo Stato membro UE del cliente (sistema OSS)" },
  termsPricesCryptoTitle: { EN: "6.2 Cryptocurrency Payments", ES: "6.2 Pagos con Criptomonedas", FR: "6.2 Paiements en Cryptomonnaies", DE: "6.2 Krypto-Zahlungen", RU: "6.2 Платежи криптовалютой", ZH: "6.2 加密货币支付", JA: "6.2 暗号通貨決済", PT: "6.2 Pagamentos com Criptomoedas", AR: "6.2 مدفوعات العملات المشفرة", IT: "6.2 Pagamenti in Criptovalute" },
  termsPricesCryptoAccepted: { EN: "We accept: SOL, USDT (Solana), USDC, Nomiqa Token", ES: "Aceptamos: SOL, USDT (Solana), USDC, token Nomiqa", FR: "Nous acceptons : SOL, USDT (Solana), USDC, jeton Nomiqa", DE: "Wir akzeptieren: SOL, USDT (Solana), USDC, Nomiqa Token", RU: "Мы принимаем: SOL, USDT (Solana), USDC, токен Nomiqa", ZH: "我们接受：SOL、USDT（Solana）、USDC、Nomiqa 代币", JA: "受け入れる：SOL、USDT（Solana）、USDC、Nomiqa トークン", PT: "Aceitamos: SOL, USDT (Solana), USDC, token Nomiqa", AR: "نقبل: SOL، USDT (Solana)، USDC، رمز Nomiqa", IT: "Accettiamo: SOL, USDT (Solana), USDC, token Nomiqa" },
  termsPricesCryptoItem1: { EN: "EUR price is fixed at checkout", ES: "El precio en EUR se fija al pagar", FR: "Le prix en EUR est fixé au moment du paiement", DE: "Preis wird in EUR definiert", RU: "Цена в EUR фиксируется при оформлении заказа", ZH: "欧元价格在结账时固定", JA: "EUR 価格はチェックアウト時に固定されます", PT: "O preço em EUR é fixado no checkout", AR: "يتم تحديد سعر اليورو عند الدفع", IT: "Il prezzo in EUR è fissato al checkout" },
  termsPricesCryptoItem2: { EN: "The system converts the price into SOL/USDT/USDC", ES: "El sistema convierte el precio en SOL/USDT/USDC", FR: "Le système convertit le prix en SOL/USDT/USDC", DE: "Checkout rechnet in SOL/USDT/USDC um", RU: "Система конвертирует цену в SOL/USDT/USDC", ZH: "系统将价格转换为 SOL/USDT/USDC", JA: "システムが価格を SOL/USDT/USDC に変換します", PT: "O sistema converte o preço em SOL/USDT/USDC", AR: "يقوم النظام بتحويل السعر إلى SOL/USDT/USDC", IT: "Il sistema converte il prezzo in SOL/USDT/USDC" },
  termsPricesCryptoItem3: { EN: "Crypto payments are irreversible", ES: "Los pagos en cripto son irreversibles", FR: "Les paiements crypto sont irréversibles", DE: "Zahlung ist irreversibel", RU: "Криптоплатежи необратимы", ZH: "加密货币支付不可逆转", JA: "暗号通貨決済は取り消しできません", PT: "Pagamentos em cripto são irreversíveis", AR: "مدفوعات العملات المشفرة غير قابلة للإلغاء", IT: "I pagamenti crypto sono irreversibili" },
  termsPricesCryptoItem4: { EN: "Payments sent via the wrong blockchain (e.g., ERC20 instead of Solana) are permanently lost – no refunds", ES: "Los pagos enviados a través de la blockchain incorrecta (p. ej., ERC20 en lugar de Solana) se pierden permanentemente: sin reembolsos", FR: "Les paiements envoyés via la mauvaise blockchain (par ex., ERC20 au lieu de Solana) sont définitivement perdus – aucun remboursement", DE: "Zahlungen über falsches Netzwerk (z. B. ERC20 statt Solana) gehen verloren → keine Erstattung", RU: "Платежи, отправленные через неправильный блокчейн (например, ERC20 вместо Solana), безвозвратно теряются – возврат невозможен", ZH: "通过错误的区块链发送的付款（例如 ERC20 而不是 Solana）将永久丢失 - 不退款", JA: "間違ったブロックチェーン（例：Solana ではなく ERC20）を介して送信された支払いは永久に失われます - 返金はありません", PT: "Pagamentos enviados pela blockchain errada (por exemplo, ERC20 em vez de Solana) são perdidos permanentemente – sem reembolsos", AR: "المدفوعات المرسلة عبر blockchain الخطأ (على سبيل المثال، ERC20 بدلاً من Solana) تُفقد بشكل دائم - لا استرداد", IT: "I pagamenti inviati tramite la blockchain errata (ad esempio, ERC20 invece di Solana) sono persi permanentemente – nessun rimborso" },
  termsPricesCryptoItem5: { EN: "Price fluctuations after purchase do not entitle the customer to refunds or adjustments", ES: "Las fluctuaciones de precios después de la compra no dan derecho al cliente a reembolsos o ajustes", FR: "Les fluctuations de prix après l'achat ne donnent pas droit au client à des remboursements ou des ajustements", DE: "Kursänderungen nach Kauf haben keinen Einfluss auf Rückerstattungen", RU: "Колебания цен после покупки не дают клиенту права на возврат средств или корректировку", ZH: "购买后的价格波动不赋予客户退款或调整的权利", JA: "購入後の価格変動は、顧客に返金または調整を受ける権利を与えません", PT: "Flutuações de preço após a compra não dão direito ao cliente a reembolsos ou ajustes", AR: "تقلبات الأسعار بعد الشراء لا تمنح العميل الحق في استرداد الأموال أو التعديلات", IT: "Le fluttuazioni dei prezzi dopo l'acquisto non danno diritto al cliente a rimborsi o adeguamenti" },
  termsPricesCryptoItem6: { EN: "Chargebacks are not possible with cryptocurrency", ES: "Los contracargos no son posibles con criptomonedas", FR: "Les rétrofacturations ne sont pas possibles avec la cryptomonnaie", DE: "Kein Chargeback bei Krypto möglich", RU: "Возвратные платежи с криптовалютой невозможны", ZH: "加密货币不可能退单", JA: "暗号通貨でのチャージバックは不可能です", PT: "Estornos não são possíveis com criptomoeda", AR: "عمليات الاسترداد غير ممكنة مع العملات المشفرة", IT: "I chargeback non sono possibili con le criptovalute" },
  
  // Network Coverage Section
  termsNetworkTitle: { EN: "7. Network Coverage, Roaming & Technical Limitations", ES: "7. Cobertura de Red, Roaming y Limitaciones Técnicas", FR: "7. Couverture Réseau, Itinérance et Limitations Techniques", DE: "7. Netzabdeckung, Roaming & technische Einschränkungen", RU: "7. Покрытие сети, роуминг и технические ограничения", ZH: "7. 网络覆盖、漫游和技术限制", JA: "7. ネットワークカバレッジ、ローミング、技術的制限", PT: "7. Cobertura de Rede, Roaming e Limitações Técnicas", AR: "7. تغطية الشبكة والتجوال والقيود الفنية", IT: "7. Copertura di Rete, Roaming e Limitazioni Tecniche" },
  termsNetworkItem1: { EN: "Coverage varies by country and local carrier", ES: "La cobertura varía según el país y el operador local", FR: "La couverture varie selon le pays et l'opérateur local", DE: "Netzabdeckung variiert je nach Land", RU: "Покрытие варьируется в зависимости от страны и местного оператора", ZH: "覆盖范围因国家和本地运营商而异", JA: "カバレッジは国と地域のキャリアによって異なります", PT: "A cobertura varia de acordo com o país e a operadora local", AR: "تختلف التغطية حسب البلد ومشغل الشبكة المحلي", IT: "La copertura varia a seconda del paese e dell'operatore locale" },
  termsNetworkItem2: { EN: "Data speed depends on network availability", ES: "La velocidad de los datos depende de la disponibilidad de la red", FR: "La vitesse des données dépend de la disponibilité du réseau", DE: "Geschwindigkeit hängt vom lokalen Carrier ab", RU: "Скорость передачи данных зависит от доступности сети", ZH: "数据速度取决于网络可用性", JA: "データ速度はネットワークの可用性に依存します", PT: "A velocidade dos dados depende da disponibilidade da rede", AR: "تعتمد سرعة البيانات على توفر الشبكة", IT: "La velocità dei dati dipende dalla disponibilità della rete" },
  termsNetworkItem3: { EN: "Hotspot/tethering may be restricted depending on the plan", ES: "El hotspot/tethering puede estar restringido según el plan", FR: "Le hotspot/partage de connexion peut être restreint selon le forfait", DE: "Hotspot / Tethering je nach Tarif eingeschränkt", RU: "Точка доступа/модем может быть ограничена в зависимости от плана", ZH: "根据套餐，热点/网络共享可能受到限制", JA: "プランによってホットスポット/テザリングが制限される場合があります", PT: "Hotspot/tethering pode ser restrito dependendo do plano", AR: "قد يتم تقييد النقطة الساخنة/الربط حسب الخطة", IT: "Hotspot/tethering potrebbe essere limitato a seconda del piano" },
  termsNetworkItem4: { EN: "Some countries restrict VoIP usage", ES: "Algunos países restringen el uso de VoIP", FR: "Certains pays restreignent l'utilisation de VoIP", DE: "Einige Länder blockieren VoIP-Dienste", RU: "Некоторые страны ограничивают использование VoIP", ZH: "某些国家限制 VoIP 使用", JA: "一部の国では VoIP の使用が制限されています", PT: "Alguns países restringem o uso de VoIP", AR: "بعض الدول تقيد استخدام VoIP", IT: "Alcuni paesi limitano l'uso di VoIP" },
  termsNetworkItem5: { EN: "Using the eSIM outside the selected region or plan will disable functionality", ES: "Usar la eSIM fuera de la región o plan seleccionado deshabilitará la funcionalidad", FR: "L'utilisation de l'eSIM en dehors de la région ou du forfait sélectionné désactivera les fonctionnalités", DE: "Nutzung in Ländern außerhalb des gewählten Pakets führt zu Nichtfunktion", RU: "Использование eSIM за пределами выбранного региона или плана отключит функциональность", ZH: "在所选地区或套餐之外使用 eSIM 将禁用功能", JA: "選択した地域またはプランの外で eSIM を使用すると、機能が無効になります", PT: "Usar o eSIM fora da região ou plano selecionado desabilitará a funcionalidade", AR: "استخدام eSIM خارج المنطقة أو الخطة المحددة سيعطل الوظيفة", IT: "L'utilizzo dell'eSIM al di fuori della regione o del piano selezionato disabiliterà la funzionalità" },
  
  // Withdrawal Rights Section
  termsWithdrawalTitle: { EN: "8. Exclusion of Withdrawal (Right of Withdrawal)", ES: "8. Exclusión de Retiro (Derecho de Retiro)", FR: "8. Exclusion du Droit de Rétractation", DE: "8. Widerrufsausschluss", RU: "8. Исключение права на отзыв", ZH: "8. 撤销权排除", JA: "8. 撤回権の除外", PT: "8. Exclusão do Direito de Rescisão", AR: "8. استبعاد حق الانسحاب", IT: "8. Esclusione del Diritto di Recesso" },
  termsWithdrawalContent: { EN: "For digital products delivered immediately, the right of withdrawal does not apply under Art. 16(m) of the EU Consumer Rights Directive.", ES: "Para productos digitales entregados inmediatamente, el derecho de desistimiento no se aplica según el Art. 16(m) de la Directiva de Derechos del Consumidor de la UE.", FR: "Pour les produits numériques livrés immédiatement, le droit de rétractation ne s'applique pas en vertu de l'art. 16(m) de la directive européenne sur les droits des consommateurs.", DE: "Für digitale Produkte, die sofort bereitgestellt werden, besteht kein Widerrufsrecht gem. Art. 16 lit. m.", RU: "Для цифровых продуктов, доставленных немедленно, право на отзыв не применяется согласно ст. 16(m) Директивы ЕС о правах потребителей.", ZH: "对于立即交付的数字产品，根据欧盟消费者权利指令第 16(m) 条，撤销权不适用。", JA: "即座に配信されるデジタル製品については、EU 消費者権利指令第 16(m) 条に基づき、撤回権は適用されません。", PT: "Para produtos digitais entregues imediatamente, o direito de rescisão não se aplica nos termos do Art. 16(m) da Diretiva de Direitos do Consumidor da UE.", AR: "بالنسبة للمنتجات الرقمية المسلمة فورًا، لا ينطبق حق الانسحاب بموجب المادة 16(م) من توجيه حقوق المستهلك في الاتحاد الأوروبي.", IT: "Per i prodotti digitali consegnati immediatamente, il diritto di recesso non si applica ai sensi dell'art. 16(m) della Direttiva UE sui diritti dei consumatori." },
  termsWithdrawalConfirmation: { EN: "I expressly consent to the immediate provision of the digital eSIM and acknowledge that my right of withdrawal expires upon delivery.", ES: "Doy mi consentimiento expreso para la provisión inmediata de la eSIM digital y reconozco que mi derecho de desistimiento expira con la entrega.", FR: "Je consens expressément à la fourniture immédiate de l'eSIM numérique et reconnais que mon droit de rétractation expire dès la livraison.", DE: "Ich stimme der sofortigen Bereitstellung der eSIM zu und bestätige das Erlöschen meines Widerrufsrechts.", RU: "Я прямо даю согласие на немедленное предоставление цифровой eSIM и признаю, что мое право на отзыв истекает после доставки.", ZH: "我明确同意立即提供数字 eSIM，并承认我的撤销权在交付后失效。", JA: "デジタル eSIM の即座の提供に明示的に同意し、配信時に撤回権が失効することを認めます。", PT: "Eu consinto expressamente com a provisão imediata do eSIM digital e reconheço que meu direito de rescisão expira após a entrega.", AR: "أوافق صراحةً على التوفير الفوري لـ eSIM الرقمي وأقر بأن حق الانسحاب الخاص بي ينتهي عند التسليم.", IT: "Acconsento espressamente alla fornitura immediata dell'eSIM digitale e riconosco che il mio diritto di recesso scade alla consegna." },
  
  // Liability Section - V3 UPGRADED
  termsLiabilityTitle: { EN: "9. Limitation of Liability", ES: "9. Limitación de Responsabilidad", FR: "9. Limitation de Responsabilité", DE: "9. Haftungsbeschränkung", RU: "9. Ограничение ответственности", ZH: "9. 责任限制", JA: "9. 責任の制限", PT: "9. Limitação de Responsabilidade", AR: "9. تحديد المسؤولية", IT: "9. Limitazione di Responsabilità" },
  termsLiabilityContent: { EN: "We are not liable for:", ES: "No somos responsables de:", FR: "Nous ne sommes pas responsables de :", DE: "Wir haften nicht für:", RU: "Мы не несем ответственности за:", ZH: "我们不对以下情况负责：", JA: "以下については責任を負いません：", PT: "Não somos responsáveis por:", AR: "نحن غير مسؤولين عن:", IT: "Non siamo responsabili per:" },
  termsLiabilityItem1: { EN: "Insufficient or no network coverage", ES: "Cobertura de red insuficiente o nula", FR: "Couverture réseau insuffisante ou inexistante", DE: "Fehlende oder schwache Netzabdeckung", RU: "Недостаточное или отсутствие покрытия сети", ZH: "网络覆盖不足或没有网络覆盖", JA: "不十分または不在のネットワークカバレッジ", PT: "Cobertura de rede insuficiente ou inexistente", AR: "تغطية شبكة غير كافية أو عدم وجودها", IT: "Copertura di rete insufficiente o assente" },
  termsLiabilityItem2: { EN: "Carrier or roaming restrictions", ES: "Restricciones del operador o roaming", FR: "Restrictions de l'opérateur ou d'itinérance", DE: "Provider- oder Roamingbeschränkungen", RU: "Ограничения оператора или роуминга", ZH: "运营商或漫游限制", JA: "キャリアまたはローミング制限", PT: "Restrições do operador ou roaming", AR: "قيود مشغل الشبكة أو التجوال", IT: "Restrizioni dell'operatore o del roaming" },
  termsLiabilityItem3: { EN: "Incompatible or incorrectly configured devices", ES: "Dispositivos incompatibles o configurados incorrectamente", FR: "Appareils incompatibles ou mal configurés", DE: "Inkompatible Geräte", RU: "Несовместимые или неправильно настроенные устройства", ZH: "不兼容或配置不正确的设备", JA: "互換性のないまたは誤って設定されたデバイス", PT: "Dispositivos incompatíveis ou configurados incorretamente", AR: "الأجهزة غير المتوافقة أو المهيأة بشكل غير صحيح", IT: "Dispositivi incompatibili o configurati in modo errato" },
  termsLiabilityItem4: { EN: "Wrong region or plan selection", ES: "Selección incorrecta de región o plan", FR: "Mauvaise sélection de région ou de forfait", DE: "Falsche Länder- oder Tarifauswahl", RU: "Неправильный выбор региона или плана", ZH: "错误的地区或套餐选择", JA: "誤った地域またはプランの選択", PT: "Seleção incorreta de região ou plano", AR: "اختيار خاطئ للمنطقة أو الخطة", IT: "Selezione errata di regione o piano" },
  termsLiabilityItem5: { EN: "eSIM misuse by third parties", ES: "Mal uso de eSIM por terceros", FR: "Utilisation abusive de l'eSIM par des tiers", DE: "Missbrauch der eSIM durch Dritte", RU: "Неправомерное использование eSIM третьими лицами", ZH: "第三方滥用 eSIM", JA: "第三者による eSIM の不正使用", PT: "Uso indevido de eSIM por terceiros", AR: "إساءة استخدام eSIM من قبل أطراف ثالثة", IT: "Uso improprio dell'eSIM da parte di terzi" },
  termsLiabilityItem6: { EN: "Sharing or leaking of the QR code", ES: "Compartir o filtrar el código QR", FR: "Partage ou fuite du code QR", DE: "Weitergabe des QR-Codes", RU: "Распространение или утечка QR-кода", ZH: "分享或泄露二维码", JA: "QR コードの共有または漏洩", PT: "Compartilhamento ou vazamento do código QR", AR: "مشاركة أو تسريب رمز QR", IT: "Condivisione o perdita del codice QR" },
  termsLiabilityItem7: { EN: "Loss of data due to device reset, theft or damage", ES: "Pérdida de datos debido a restablecimiento del dispositivo, robo o daño", FR: "Perte de données due à la réinitialisation de l'appareil, au vol ou aux dommages", DE: "Datenverlust durch Reset, Diebstahl, Schaden", RU: "Потеря данных из-за сброса устройства, кражи или повреждения", ZH: "由于设备重置、盗窃或损坏导致的数据丢失", JA: "デバイスのリセット、盗難、または損傷によるデータの損失", PT: "Perda de dados devido a reset do dispositivo, roubo ou dano", AR: "فقدان البيانات بسبب إعادة تعيين الجهاز أو السرقة أو التلف", IT: "Perdita di dati dovuta a reset del dispositivo, furto o danneggiamento" },
  // V3: Structured Liability Cap
  termsLiabilityCapTitle: { EN: "Structured Limitation", ES: "Limitación Estructurada", FR: "Limitation Structurée", DE: "Strukturierte Haftungsbegrenzung", RU: "Структурированное ограничение", ZH: "结构化限制", JA: "構造化された制限", PT: "Limitação Estruturada", AR: "القيود المهيكلة", IT: "Limitazione Strutturata" },
  termsLiabilityCapContent: { EN: "Unlimited liability applies only in cases of gross negligence, wilful misconduct, or personal injury. In all other cases, our aggregate liability is limited to the purchase price paid by the customer for the relevant product or service. This limitation applies to the fullest extent permitted by applicable law, including but not limited to claims arising from contract, tort, or statute.", ES: "La responsabilidad ilimitada se aplica solo en casos de negligencia grave, conducta dolosa o lesiones personales. En todos los demás casos, nuestra responsabilidad total se limita al precio de compra pagado por el cliente.", FR: "La responsabilité illimitée ne s'applique qu'en cas de négligence grave, de faute intentionnelle ou de préjudice corporel. Dans tous les autres cas, notre responsabilité totale est limitée au prix d'achat payé par le client.", DE: "Unbeschränkte Haftung besteht nur bei grober Fahrlässigkeit, Vorsatz oder Personenschäden. In allen anderen Fällen ist unsere Gesamthaftung auf den vom Kunden gezahlten Kaufpreis beschränkt.", RU: "Неограниченная ответственность применяется только в случаях грубой небрежности, умышленного неправомерного поведения или причинения вреда здоровью. Во всех остальных случаях наша совокупная ответственность ограничена ценой покупки.", ZH: "无限责任仅适用于重大过失、故意不当行为或人身伤害的情况。在所有其他情况下，我们的总责任限于客户支付的购买价格。", JA: "無制限の責任は、重大な過失、故意の不正行為、または人身傷害の場合にのみ適用されます。その他すべての場合、当社の責任総額は顧客が支払った購入価格に限定されます。", PT: "A responsabilidade ilimitada se aplica apenas em casos de negligência grave, conduta dolosa ou lesão pessoal. Em todos os outros casos, nossa responsabilidade total é limitada ao preço de compra pago pelo cliente.", AR: "تنطبق المسؤولية غير المحدودة فقط في حالات الإهمال الجسيم أو سوء السلوك المتعمد أو الإصابة الشخصية. في جميع الحالات الأخرى، تقتصر مسؤوليتنا الإجمالية على سعر الشراء.", IT: "La responsabilità illimitata si applica solo in caso di negligenza grave, dolo o lesioni personali. In tutti gli altri casi, la nostra responsabilità complessiva è limitata al prezzo di acquisto pagato dal cliente." },
  
  // Prohibited Use Section
  termsProhibitedTitle: { EN: "10. Prohibited Use", ES: "10. Uso Prohibido", FR: "10. Utilisation Interdite", DE: "10. Verbotene Nutzung", RU: "10. Запрещенное использование", ZH: "10. 禁止使用", JA: "10. 禁止される使用", PT: "10. Uso Proibido", AR: "10. الاستخدام المحظور", IT: "10. Uso Vietato" },
  termsProhibitedItem1: { EN: "Fraud", ES: "Fraude", FR: "Fraude", DE: "Fraud", RU: "Мошенничество", ZH: "欺诈", JA: "詐欺", PT: "Fraude", AR: "الاحتيال", IT: "Frode" },
  termsProhibitedItem2: { EN: "eSIM sharing or QR code redistribution", ES: "Compartir eSIM o redistribuir códigos QR", FR: "Partage d'eSIM ou redistribution de code QR", DE: "eSIM-Sharing / QR-Weitergabe", RU: "Обмен eSIM или перераспределение QR-кодов", ZH: "eSIM 共享或二维码再分发", JA: "eSIM の共有または QR コードの再配布", PT: "Compartilhamento de eSIM ou redistribuição de código QR", AR: "مشاركة eSIM أو إعادة توزيع رمز QR", IT: "Condivisione di eSIM o redistribuzione del codice QR" },
  termsProhibitedItem3: { EN: "Machine/bot activations", ES: "Activaciones de máquinas/bots", FR: "Activations par machine/bot", DE: "Bot-/Machine-Aktivierungen", RU: "Активации машин/ботов", ZH: "机器/机器人激活", JA: "マシン/ボットのアクティベーション", PT: "Ativações por máquina/bot", AR: "تنشيطات الآلة/الروبوت", IT: "Attivazioni di macchine/bot" },
  termsProhibitedItem4: { EN: "Illegal activities", ES: "Actividades ilegales", FR: "Activités illégales", DE: "Illegale Aktivitäten", RU: "Незаконная деятельность", ZH: "非法活动", JA: "違法行為", PT: "Atividades ilegais", AR: "الأنشطة غير القانونية", IT: "Attività illegali" },
  termsProhibitedItem5: { EN: "SIM-farming", ES: "SIM-farming", FR: "SIM-farming", DE: "SIM-Farming", RU: "SIM-фарминг", ZH: "SIM-farming", JA: "SIM ファーミング", PT: "SIM-farming", AR: "استخراج SIM", IT: "SIM-farming" },
  termsProhibitedItem6: { EN: "Reselling without written permission", ES: "Reventa sin permiso por escrito", FR: "Revente sans autorisation écrite", DE: "Reselling ohne schriftliche Genehmigung", RU: "Перепродажа без письменного разрешения", ZH: "未经书面许可的转售", JA: "書面による許可なしの再販", PT: "Revenda sem permissão por escrito", AR: "إعادة البيع بدون إذن كتابي", IT: "Rivendita senza autorizzazione scritta" },
  
  // Support Section
  termsSupportTitle: { EN: "11. Support", ES: "11. Soporte", FR: "11. Assistance", DE: "11. Support", RU: "11. Поддержка", ZH: "11. 支持", JA: "11. サポート", PT: "11. Suporte", AR: "11. الدعم", IT: "11. Supporto" },
  termsSupportEmail: { EN: "Email: support@nomiqa-esim.com", ES: "Correo electrónico: support@nomiqa-esim.com", FR: "E-mail : support@nomiqa-esim.com", DE: "E-Mail: support@nomiqa-esim.com", RU: "Электронная почта: support@nomiqa-esim.com", ZH: "电子邮件: support@nomiqa-esim.com", JA: "メール: support@nomiqa-esim.com", PT: "E-mail: support@nomiqa-esim.com", AR: "البريد الإلكتروني: support@nomiqa-esim.com", IT: "Email: support@nomiqa-esim.com" },
  termsSupportResponse: { EN: "Response time: 12-24 hours", ES: "Tiempo de respuesta: 12-24 horas", FR: "Délai de réponse : 12-24 heures", DE: "Reaktionszeit: 12–24 h", RU: "Время ответа: 12-24 часа", ZH: "响应时间：12-24 小时", JA: "応答時間: 12-24 時間", PT: "Tempo de resposta: 12-24 horas", AR: "وقت الاستجابة: 12-24 ساعة", IT: "Tempo di risposta: 12-24 ore" },
  
  // Governing Law Section - V3 UPGRADED
  termsGoverningTitle: { EN: "12. Governing Law & Jurisdiction", ES: "12. Ley Aplicable y Jurisdicción", FR: "12. Droit Applicable et Juridiction", DE: "12. Anwendbares Recht & Gerichtsstand", RU: "12. Применимое право и юрисдикция", ZH: "12. 适用法律和管辖权", JA: "12. 準拠法と管轄権", PT: "12. Lei Aplicável e Jurisdição", AR: "12. القانون الحاكم والاختصاص القضائي", IT: "12. Legge Applicabile e Giurisdizione" },
  termsGoverningContent: { EN: "These Terms shall be governed by and construed in accordance with the laws of England and Wales, without regard to its conflict of law provisions. Any disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts of England and Wales. For EU consumers, mandatory consumer protection provisions of the consumer's country of habitual residence shall apply to the extent required by applicable law.", ES: "Estos Términos se regirán por las leyes de Inglaterra y Gales. Para consumidores de la UE, se aplicarán las disposiciones obligatorias de protección al consumidor de su país de residencia habitual.", FR: "Ces Conditions sont régies par le droit de l'Angleterre et du Pays de Galles. Pour les consommateurs de l'UE, les dispositions obligatoires de protection des consommateurs de leur pays de résidence habituelle s'appliquent.", DE: "Diese AGB unterliegen dem Recht von England und Wales. Für EU-Verbraucher gelten die zwingenden Verbraucherschutzbestimmungen ihres gewöhnlichen Aufenthaltslandes.", RU: "Настоящие Условия регулируются законодательством Англии и Уэльса. Для потребителей ЕС применяются обязательные положения о защите прав потребителей страны их обычного проживания.", ZH: "本条款受英格兰和威尔士法律管辖。对于欧盟消费者，适用其惯常居住国的强制性消费者保护条款。", JA: "本規約はイングランドおよびウェールズの法律に準拠します。EU消費者については、常居所国の強行的消費者保護規定が適用されます。", PT: "Estes Termos serão regidos pelas leis da Inglaterra e País de Gales. Para consumidores da UE, aplicam-se as disposições obrigatórias de proteção ao consumidor do seu país de residência habitual.", AR: "تخضع هذه الشروط لقوانين إنجلترا وويلز. بالنسبة لمستهلكي الاتحاد الأوروبي، تنطبق أحكام حماية المستهلك الإلزامية لبلد إقامتهم المعتادة.", IT: "Questi Termini sono regolati dalle leggi di Inghilterra e Galles. Per i consumatori UE, si applicano le disposizioni obbligatorie di protezione del consumatore del paese di residenza abituale." },
  
  // Privacy Policy Section
  termsPrivacyTitle: { EN: "3. Privacy Policy (GDPR & UK GDPR Compliant)", ES: "3. Política de Privacidad (Cumple con GDPR y UK GDPR)", FR: "3. Politique de Confidentialité (Conforme RGPD et UK GDPR)", DE: "3. Datenschutzerklärung DSGVO/UK GDPR", RU: "3. Политика конфиденциальности (соответствует GDPR и UK GDPR)", ZH: "3. 隐私政策（符合 GDPR 和 UK GDPR）", JA: "3. プライバシーポリシー（GDPR および UK GDPR 準拠）", PT: "3. Política de Privacidade (Conforme GDPR e UK GDPR)", AR: "3. سياسة الخصوصية (متوافقة مع GDPR و UK GDPR)", IT: "3. Informativa sulla Privacy (Conforme GDPR e UK GDPR)" },
  termsPrivacyControllerTitle: { EN: "1. Data Controller", ES: "1. Controlador de Datos", FR: "1. Responsable du Traitement", DE: "1. Verantwortlicher", RU: "1. Контроллер данных", ZH: "1. 数据控制者", JA: "1. データ管理者", PT: "1. Controlador de Dados", AR: "1. مراقب البيانات", IT: "1. Titolare del Trattamento" },
  termsPrivacyControllerContent: { EN: "Business Unlimited Worldwide Ltd., London, United Kingdom, privacy@nomiqa-esim.com", ES: "Business Unlimited Worldwide Ltd., Londres, Reino Unido, privacy@nomiqa-esim.com", FR: "Business Unlimited Worldwide Ltd., Londres, Royaume-Uni, privacy@nomiqa-esim.com", DE: "Business Unlimited Worldwide Ltd. London, UK, privacy@nomiqa-esim.com", RU: "Business Unlimited Worldwide Ltd., Лондон, Великобритания, privacy@nomiqa-esim.com", ZH: "Business Unlimited Worldwide Ltd.，伦敦，英国，privacy@nomiqa-esim.com", JA: "Business Unlimited Worldwide Ltd.、ロンドン、イギリス、privacy@nomiqa-esim.com", PT: "Business Unlimited Worldwide Ltd., Londres, Reino Unido, privacy@nomiqa-esim.com", AR: "Business Unlimited Worldwide Ltd.، لندن، المملكة المتحدة، privacy@nomiqa-esim.com", IT: "Business Unlimited Worldwide Ltd., Londra, Regno Unito, privacy@nomiqa-esim.com" },
  termsPrivacyDataTitle: { EN: "2. Data We Process", ES: "2. Datos que Procesamos", FR: "2. Données que Nous Traitons", DE: "2. Welche Daten wir verarbeiten", RU: "2. Данные, которые мы обрабатываем", ZH: "2. 我们处理的数据", JA: "2. 処理するデータ", PT: "2. Dados que Processamos", AR: "2. البيانات التي نعالجها", IT: "2. Dati che Trattiamo" },
  termsPrivacyDataPersonal: { EN: "Personal Data", ES: "Datos Personales", FR: "Données Personnelles", DE: "Personendaten", RU: "Персональные данные", ZH: "个人数据", JA: "個人データ", PT: "Dados Pessoais", AR: "البيانات الشخصية", IT: "Dati Personali" },
  termsPrivacyDataItem1: { EN: "Name", ES: "Nombre", FR: "Nom", DE: "Name", RU: "Имя", ZH: "姓名", JA: "名前", PT: "Nome", AR: "الاسم", IT: "Nome" },
  termsPrivacyDataItem2: { EN: "Email address", ES: "Dirección de correo electrónico", FR: "Adresse e-mail", DE: "E-Mail", RU: "Адрес электронной почты", ZH: "电子邮件地址", JA: "メールアドレス", PT: "Endereço de e-mail", AR: "عنوان البريد الإلكتروني", IT: "Indirizzo e-mail" },
  termsPrivacyDataItem3: { EN: "Country / address", ES: "País / dirección", FR: "Pays / adresse", DE: "Land / Adresse", RU: "Страна / адрес", ZH: "国家/地址", JA: "国/住所", PT: "País / endereço", AR: "البلد / العنوان", IT: "Paese / indirizzo" },
  termsPrivacyDataCheckout: { EN: "Checkout Data", ES: "Datos de Pago", FR: "Données de Paiement", DE: "Checkout-Daten", RU: "Данные оформления заказа", ZH: "结账数据", JA: "チェックアウトデータ", PT: "Dados de Checkout", AR: "بيانات الدفع", IT: "Dati di Checkout" },
  termsPrivacyDataItem4: { EN: "IP address", ES: "Dirección IP", FR: "Adresse IP", DE: "IP-Adresse", RU: "IP-адрес", ZH: "IP 地址", JA: "IP アドレス", PT: "Endereço IP", AR: "عنوان IP", IT: "Indirizzo IP" },
  termsPrivacyDataItem5: { EN: "Device & browser information", ES: "Información del dispositivo y navegador", FR: "Informations sur l'appareil et le navigateur", DE: "Gerät / Browser", RU: "Информация об устройстве и браузере", ZH: "设备和浏览器信息", JA: "デバイスとブラウザ情報", PT: "Informações do dispositivo e navegador", AR: "معلومات الجهاز والمتصفح", IT: "Informazioni su dispositivo e browser" },
  termsPrivacyDataItem6: { EN: "Payment information", ES: "Información de pago", FR: "Informations de paiement", DE: "Zahlungsinformationen", RU: "Платежная информация", ZH: "支付信息", JA: "支払い情報", PT: "Informações de pagamento", AR: "معلومات الدفع", IT: "Informazioni di pagamento" },
  termsPrivacyDataItem7: { EN: "Hashed crypto wallet address", ES: "Dirección de billetera cripto hasheada", FR: "Adresse de portefeuille crypto hachée", DE: "Krypto-Wallet (gehasht)", RU: "Хешированный адрес криптокошелька", ZH: "哈希加密钱包地址", JA: "ハッシュ化された暗号ウォレットアドレス", PT: "Endereço de carteira cripto hash", AR: "عنوان محفظة التشفير المشفّر", IT: "Indirizzo portafoglio crypto hashato" },
  termsPrivacyDataItem8: { EN: "EUR value at time of payment", ES: "Valor en EUR al momento del pago", FR: "Valeur en EUR au moment du paiement", DE: "EUR-Wert zum Zahlungskurs", RU: "Стоимость в EUR на момент оплаты", ZH: "付款时的欧元价值", JA: "支払い時の EUR 価値", PT: "Valor em EUR no momento do pagamento", AR: "قيمة اليورو وقت الدفع", IT: "Valore in EUR al momento del pagamento" },
  termsPrivacyDataESIM: { EN: "eSIM Data", ES: "Datos de eSIM", FR: "Données eSIM", DE: "eSIM-Daten", RU: "Данные eSIM", ZH: "eSIM 数据", JA: "eSIM データ", PT: "Dados de eSIM", AR: "بيانات eSIM", IT: "Dati eSIM" },
  termsPrivacyDataItem9: { EN: "eSIM ID", ES: "ID de eSIM", FR: "ID eSIM", DE: "eSIM-ID", RU: "ID eSIM", ZH: "eSIM ID", JA: "eSIM ID", PT: "ID de eSIM", AR: "معرّف eSIM", IT: "ID eSIM" },
  termsPrivacyDataItem10: { EN: "Serial number", ES: "Número de serie", FR: "Numéro de série", DE: "Seriennummer", RU: "Серийный номер", ZH: "序列号", JA: "シリアル番号", PT: "Número de série", AR: "الرقم التسلسلي", IT: "Numero di serie" },
  termsPrivacyDataItem11: { EN: "Activation status", ES: "Estado de activación", FR: "Statut d'activation", DE: "Aktivierungsstatus", RU: "Статус активации", ZH: "激活状态", JA: "アクティベーション状態", PT: "Status de ativação", AR: "حالة التنشيط", IT: "Stato di attivazione" },
  termsPrivacyDataItem12: { EN: "Data usage", ES: "Uso de datos", FR: "Utilisation des données", DE: "Datenverbrauch", RU: "Использование данных", ZH: "数据使用", JA: "データ使用量", PT: "Uso de dados", AR: "استخدام البيانات", IT: "Utilizzo dei dati" },
  termsPrivacyPurposeTitle: { EN: "3. Purpose of Processing", ES: "3. Finalidad del Procesamiento", FR: "3. Finalité du Traitement", DE: "3. Zweck der Verarbeitung", RU: "3. Цель обработки", ZH: "3. 处理目的", JA: "3. 処理の目的", PT: "3. Finalidade do Processamento", AR: "3. الغرض من المعالجة", IT: "3. Finalità del Trattamento" },
  termsPrivacyPurposeItem1: { EN: "Contract fulfillment (Art. 6(1)(b) GDPR)", ES: "Cumplimiento del contrato (Art. 6(1)(b) GDPR)", FR: "Exécution du contrat (Art. 6(1)(b) RGPD)", DE: "Vertragserfüllung (Art. 6(1)b)", RU: "Исполнение договора (Арт. 6(1)(b) GDPR)", ZH: "合同履行（GDPR 第 6(1)(b) 条）", JA: "契約の履行（GDPR 第 6(1)(b) 条）", PT: "Cumprimento do contrato (Art. 6(1)(b) GDPR)", AR: "تنفيذ العقد (المادة 6(1)(ب) من GDPR)", IT: "Adempimento del contratto (Art. 6(1)(b) GDPR)" },
  termsPrivacyPurposeItem2: { EN: "VAT/OSS compliance (Art. 6(1)(c) GDPR)", ES: "Cumplimiento de IVA/OSS (Art. 6(1)(c) GDPR)", FR: "Conformité TVA/OSS (Art. 6(1)(c) RGPD)", DE: "VAT/OSS-Verpflichtungen (Art. 6(1)c)", RU: "Соблюдение НДС/OSS (Арт. 6(1)(c) GDPR)", ZH: "增值税/OSS 合规（GDPR 第 6(1)(c) 条）", JA: "VAT/OSS コンプライアンス（GDPR 第 6(1)(c) 条）", PT: "Conformidade com IVA/OSS (Art. 6(1)(c) GDPR)", AR: "الامتثال لضريبة القيمة المضافة/OSS (المادة 6(1)(ج) من GDPR)", IT: "Conformità IVA/OSS (Art. 6(1)(c) GDPR)" },
  termsPrivacyPurposeItem3: { EN: "IT security & fraud prevention (Art. 6(1)(f) GDPR)", ES: "Seguridad informática y prevención de fraude (Art. 6(1)(f) GDPR)", FR: "Sécurité informatique et prévention de la fraude (Art. 6(1)(f) RGPD)", DE: "IT-Sicherheit (Art. 6(1)f)", RU: "ИТ-безопасность и предотвращение мошенничества (Арт. 6(1)(f) GDPR)", ZH: "IT 安全和防欺诈（GDPR 第 6(1)(f) 条）", JA: "IT セキュリティおよび不正防止（GDPR 第 6(1)(f) 条）", PT: "Segurança de TI e prevenção de fraudes (Art. 6(1)(f) GDPR)", AR: "أمن تكنولوجيا المعلومات ومنع الاحتيال (المادة 6(1)(و) من GDPR)", IT: "Sicurezza IT e prevenzione delle frodi (Art. 6(1)(f) GDPR)" },
  termsPrivacyPurposeItem4: { EN: "Marketing communications (with consent, Art. 6(1)(a) GDPR)", ES: "Comunicaciones de marketing (con consentimiento, Art. 6(1)(a) GDPR)", FR: "Communications marketing (avec consentement, Art. 6(1)(a) RGPD)", DE: "Marketing nur nach Einwilligung (Art. 6(1)a)", RU: "Маркетинговые коммуникации (с согласия, Арт. 6(1)(a) GDPR)", ZH: "营销通讯（经同意，GDPR 第 6(1)(a) 条）", JA: "マーケティング通信（同意を得て、GDPR 第 6(1)(a) 条）", PT: "Comunicações de marketing (com consentimento, Art. 6(1)(a) GDPR)", AR: "الاتصالات التسويقية (بموافقة، المادة 6(1)(أ) من GDPR)", IT: "Comunicazioni di marketing (con consenso, Art. 6(1)(a) GDPR)" },
  termsPrivacyThirdPartyTitle: { EN: "4. Third-Party Data Sharing", ES: "4. Compartir Datos con Terceros", FR: "4. Partage de Données avec des Tiers", DE: "4. Drittanbieter & Datenübertragung", RU: "4. Обмен данными с третьими лицами", ZH: "4. 第三方数据共享", JA: "4. 第三者へのデータ共有", PT: "4. Compartilhamento de Dados com Terceiros", AR: "4. مشاركة البيانات مع أطراف ثالثة", IT: "4. Condivisione di Dati con Terze Parti" },
  termsPrivacyThirdPartyContent: { EN: "Data may be shared with:", ES: "Los datos pueden compartirse con:", FR: "Les données peuvent être partagées avec :", DE: "Daten können übermittelt werden an:", RU: "Данные могут быть переданы:", ZH: "数据可能会与以下各方共享：", JA: "データは次の相手と共有される場合があります：", PT: "Os dados podem ser compartilhados com:", AR: "قد تتم مشاركة البيانات مع:", IT: "I dati possono essere condivisi con:" },
  termsPrivacyThirdPartyItem1: { EN: "Hosting providers (EU)", ES: "Proveedores de alojamiento (UE)", FR: "Fournisseurs d'hébergement (UE)", DE: "Hosting (EU)", RU: "Хостинг-провайдеры (ЕС)", ZH: "托管提供商（欧盟）", JA: "ホスティングプロバイダー（EU）", PT: "Provedores de hospedagem (UE)", AR: "مقدمو الاستضافة (الاتحاد الأوروبي)", IT: "Fornitori di hosting (UE)" },
  termsPrivacyThirdPartyItem2: { EN: "Payment processors (e.g., Stripe, CoinGate)", ES: "Procesadores de pago (p. ej., Stripe, CoinGate)", FR: "Processeurs de paiement (par ex., Stripe, CoinGate)", DE: "Zahlungsdienstleister (Stripe, CoinGate o. ä.)", RU: "Платежные процессоры (например, Stripe, CoinGate)", ZH: "支付处理器（例如 Stripe、CoinGate）", JA: "決済処理業者（例: Stripe、CoinGate）", PT: "Processadores de pagamento (por exemplo, Stripe, CoinGate)", AR: "معالجات الدفع (مثل Stripe وCoinGate)", IT: "Processori di pagamento (ad es., Stripe, CoinGate)" },
  termsPrivacyThirdPartyItem3: { EN: "Solana blockchain (public & immutable ledger)", ES: "Blockchain de Solana (libro mayor público e inmutable)", FR: "Blockchain Solana (registre public et immuable)", DE: "Solana Blockchain (öffentliche, unveränderliche Speicherung)", RU: "Блокчейн Solana (публичный и неизменяемый реестр)", ZH: "Solana 区块链（公共且不可变的账本）", JA: "Solana ブロックチェーン（公開および不変の台帳）", PT: "Blockchain Solana (registro público e imutável)", AR: "بلوكشين سولانا (دفتر عام وغير قابل للتغيير)", IT: "Blockchain Solana (registro pubblico e immutabile)" },
  termsPrivacyThirdPartyItem4: { EN: "VAT OSS tax authorities", ES: "Autoridades fiscales de IVA OSS", FR: "Autorités fiscales TVA OSS", DE: "OSS Steuerbehörden", RU: "Налоговые органы НДС OSS", ZH: "增值税 OSS 税务机关", JA: "VAT OSS 税務当局", PT: "Autoridades fiscais de IVA OSS", AR: "السلطات الضريبية لـ VAT OSS", IT: "Autorità fiscali IVA OSS" },
  termsPrivacyThirdPartyItem5: { EN: "CRM systems", ES: "Sistemas CRM", FR: "Systèmes CRM", DE: "CRM-System", RU: "CRM-системы", ZH: "CRM 系统", JA: "CRM システム", PT: "Sistemas CRM", AR: "أنظمة إدارة علاقات العملاء", IT: "Sistemi CRM" },
  termsPrivacyThirdPartyTransfers: { EN: "Data Transfers to Third Countries", ES: "Transferencias de Datos a Terceros Países", FR: "Transferts de Données vers des Pays Tiers", DE: "Übertragung in Drittländer", RU: "Передача данных в третьи страны", ZH: "向第三国传输数据", JA: "第三国へのデータ転送", PT: "Transferências de Dados para Terceiros Países", AR: "نقل البيانات إلى دول ثالثة", IT: "Trasferimenti di Dati verso Paesi Terzi" },
  termsPrivacyThirdPartyTransfer1: { EN: "UK: covered by EU Adequacy Decision", ES: "Reino Unido: cubierto por la Decisión de Adecuación de la UE", FR: "Royaume-Uni : couvert par la décision d'adéquation de l'UE", DE: "UK: Angemessenheitsbeschluss", RU: "Великобритания: покрывается Решением ЕС о достаточности", ZH: "英国：受欧盟充分性决定覆盖", JA: "英国: EU 十分性決定の対象", PT: "Reino Unido: coberto pela Decisão de Adequação da UE", AR: "المملكة المتحدة: مشمولة بقرار الكفاءة من الاتحاد الأوروبي", IT: "Regno Unito: coperto da Decisione di Adeguatezza UE" },
  termsPrivacyThirdPartyTransfer2: { EN: "USA: Standard Contractual Clauses (SCCs)", ES: "EE.UU.: Cláusulas Contractuales Estándar (SCC)", FR: "États-Unis : Clauses Contractuelles Types (CCT)", DE: "USA: Standardvertragsklauseln", RU: "США: Стандартные договорные положения (SCC)", ZH: "美国：标准合同条款 (SCC)", JA: "米国: 標準契約条項（SCC）", PT: "EUA: Cláusulas Contratuais Padrão (SCC)", AR: "الولايات المتحدة: البنود التعاقدية القياسية (SCCs)", IT: "USA: Clausole Contrattuali Standard (SCC)" },
  termsPrivacyRetentionTitle: { EN: "5. Data Retention", ES: "5. Retención de Datos", FR: "5. Conservation des Données", DE: "5. Speicherdauer", RU: "5. Хранение данных", ZH: "5. 数据保留", JA: "5. データ保持", PT: "5. Retenção de Dados", AR: "5. الاحتفاظ بالبيانات", IT: "5. Conservazione dei Dati" },
  termsPrivacyRetentionItem1: { EN: "Tax-related data: 6-10 years", ES: "Datos relacionados con impuestos: 6-10 años", FR: "Données liées aux impôts : 6-10 ans", DE: "Steuerdaten: 6–10 Jahre", RU: "Данные, связанные с налогами: 6-10 лет", ZH: "税务相关数据：6-10 年", JA: "税務関連データ: 6-10 年", PT: "Dados relacionados a impostos: 6-10 anos", AR: "البيانات المتعلقة بالضرائب: 6-10 سنوات", IT: "Dati fiscali: 6-10 anni" },
  termsPrivacyRetentionItem2: { EN: "eSIM usage data: until contract end", ES: "Datos de uso de eSIM: hasta el final del contrato", FR: "Données d'utilisation eSIM : jusqu'à la fin du contrat", DE: "eSIM-Nutzungsdaten: bis Vertragsende", RU: "Данные использования eSIM: до окончания контракта", ZH: "eSIM 使用数据：直至合同结束", JA: "eSIM 使用データ: 契約終了まで", PT: "Dados de uso de eSIM: até o fim do contrato", AR: "بيانات استخدام eSIM: حتى نهاية العقد", IT: "Dati di utilizzo eSIM: fino alla fine del contratto" },
  termsPrivacyRetentionItem3: { EN: "Wallet data: pseudonymised", ES: "Datos de billetera: pseudonimizados", FR: "Données de portefeuille : pseudonymisées", DE: "Wallet-Daten: pseudonymisiert", RU: "Данные кошелька: псевдонимизированы", ZH: "钱包数据：假名化", JA: "ウォレットデータ: 仮名化", PT: "Dados de carteira: pseudonimizados", AR: "بيانات المحفظة: مخفية الهوية", IT: "Dati del portafoglio: pseudonimizzati" },
  termsPrivacyRightsTitle: { EN: "6. Your Rights (EU users)", ES: "6. Tus Derechos (usuarios de la UE)", FR: "6. Vos Droits (utilisateurs UE)", DE: "6. Ihre Rechte", RU: "6. Ваши права (пользователи ЕС)", ZH: "6. 您的权利（欧盟用户）", JA: "6. あなたの権利（EU ユーザー）", PT: "6. Seus Direitos (usuários da UE)", AR: "6. حقوقك (مستخدمو الاتحاد الأوروبي)", IT: "6. I Tuoi Diritti (utenti UE)" },
  termsPrivacyRightsContent: { EN: "You have the right to:", ES: "Tienes derecho a:", FR: "Vous avez le droit de :", DE: "Sie haben das Recht auf:", RU: "Вы имеете право на:", ZH: "您有权：", JA: "あなたは次の権利を有します：", PT: "Você tem o direito de:", AR: "لديك الحق في:", IT: "Hai il diritto di:" },
  termsPrivacyRightsItem1: { EN: "Access your data", ES: "Acceder a tus datos", FR: "Accéder à vos données", DE: "Auskunft", RU: "Доступ к вашим данным", ZH: "访问您的数据", JA: "データへのアクセス", PT: "Acessar seus dados", AR: "الوصول إلى بياناتك", IT: "Accedere ai tuoi dati" },
  termsPrivacyRightsItem2: { EN: "Request deletion", ES: "Solicitar eliminación", FR: "Demander la suppression", DE: "Löschung", RU: "Запрос на удаление", ZH: "请求删除", JA: "削除の要求", PT: "Solicitar exclusão", AR: "طلب الحذف", IT: "Richiedere la cancellazione" },
  termsPrivacyRightsItem3: { EN: "Request correction", ES: "Solicitar corrección", FR: "Demander la rectification", DE: "Berichtigung", RU: "Запрос на исправление", ZH: "请求更正", JA: "訂正の要求", PT: "Solicitar correção", AR: "طلب التصحيح", IT: "Richiedere la correzione" },
  termsPrivacyRightsItem4: { EN: "Data portability", ES: "Portabilidad de datos", FR: "Portabilité des données", DE: "Datenübertragbarkeit", RU: "Портативность данных", ZH: "数据可移植性", JA: "データの可搬性", PT: "Portabilidade de dados", AR: "نقل البيانات", IT: "Portabilità dei dati" },
  termsPrivacyRightsItem5: { EN: "File a complaint with any EU supervisory authority", ES: "Presentar una queja ante cualquier autoridad supervisora de la UE", FR: "Déposer une plainte auprès de toute autorité de contrôle de l'UE", DE: "Beschwerde bei EU-Aufsichtsbehörden", RU: "Подать жалобу в любой надзорный орган ЕС", ZH: "向任何欧盟监管机构提出投诉", JA: "EU 監督当局に苦情を申し立てる", PT: "Apresentar uma reclamação a qualquer autoridade supervisora da UE", AR: "تقديم شكوى إلى أي سلطة إشرافية في الاتحاد الأوروبي", IT: "Presentare un reclamo a qualsiasi autorità di vigilanza UE" },
  termsPrivacyRightsContact: { EN: "Contact: privacy@nomiqa-esim.com", ES: "Contacto: privacy@nomiqa-esim.com", FR: "Contact : privacy@nomiqa-esim.com", DE: "Kontakt: privacy@nomiqa-esim.com", RU: "Контакт: privacy@nomiqa-esim.com", ZH: "联系方式：privacy@nomiqa-esim.com", JA: "連絡先: privacy@nomiqa-esim.com", PT: "Contato: privacy@nomiqa-esim.com", AR: "اتصال: privacy@nomiqa-esim.com", IT: "Contatto: privacy@nomiqa-esim.com" },
  
  // Withdrawal Policy Section
  termsWithdrawalPolicyTitle: { EN: "4. Withdrawal Policy for Digital eSIM Products", ES: "4. Política de Retiro para Productos eSIM Digitales", FR: "4. Politique de Rétractation pour les Produits eSIM Numériques", DE: "4. Widerrufsbelehrung für digitale eSIM-Produkte", RU: "4. Политика отзыва для цифровых продуктов eSIM", ZH: "4. 数字 eSIM 产品的撤销政策", JA: "4. デジタル eSIM 製品の撤回ポリシー", PT: "4. Política de Rescisão para Produtos eSIM Digitais", AR: "4. سياسة الانسحاب لمنتجات eSIM الرقمية", IT: "4. Politica di Recesso per Prodotti eSIM Digitali" },
  termsWithdrawalPolicyContent: { EN: "The customer has no right of withdrawal, because the product is delivered immediately, the customer expressly agrees to immediate delivery, and the right of withdrawal expires upon delivery according to §356(5) BGB / Art. 16(m) EU Directive.", ES: "El cliente no tiene derecho de desistimiento, porque el producto se entrega inmediatamente, el cliente acepta expresamente la entrega inmediata, y el derecho de desistimiento expira con la entrega según §356(5) BGB / Art. 16(m) Directiva UE.", FR: "Le client n'a pas de droit de rétractation, car le produit est livré immédiatement, le client accepte expressément la livraison immédiate, et le droit de rétractation expire dès la livraison selon §356(5) BGB / Art. 16(m) Directive UE.", DE: "Der Kunde hat kein Widerrufsrecht, weil die eSIM sofort geliefert wird, der Kunde ausdrücklich zugestimmt hat und das Widerrufsrecht nach § 356 Abs. 5 BGB / Art. 16 lit. m entfällt.", RU: "Клиент не имеет права на отзыв, поскольку продукт доставляется немедленно, клиент прямо соглашается с немедленной доставкой, и право на отзыв истекает после доставки в соответствии с §356(5) BGB / Ст. 16(m) Директивы ЕС.", ZH: "客户没有撤销权，因为产品立即交付，客户明确同意立即交付，并且根据 §356(5) BGB / Art. 16(m) 欧盟指令，撤销权在交付后失效。", JA: "顧客は撤回権を持ちません。製品が即座に配信され、顧客が即座の配信に明示的に同意し、§356(5) BGB / Art. 16(m) EU 指令に従って配信時に撤回権が失効するためです。", PT: "O cliente não tem direito de rescisão, porque o produto é entregue imediatamente, o cliente concorda expressamente com a entrega imediata, e o direito de rescisão expira após a entrega de acordo com §356(5) BGB / Art. 16(m) Diretiva UE.", AR: "لا يملك العميل حق الانسحاب، لأن المنتج يتم تسليمه فورًا، ويوافق العميل صراحةً على التسليم الفوري، وينتهي حق الانسحاب عند التسليم وفقًا للمادة §356(5) BGB / المادة 16(م) من توجيه الاتحاد الأوروبي.", IT: "Il cliente non ha diritto di recesso, perché il prodotto è consegnato immediatamente, il cliente acconsente espressamente alla consegna immediata, e il diritto di recesso scade alla consegna secondo §356(5) BGB / Art. 16(m) Direttiva UE." },
  termsWithdrawalPolicyCustomer: { EN: "Customer confirmation:", ES: "Confirmación del cliente:", FR: "Confirmation du client :", DE: "Kundenbestätigung:", RU: "Подтверждение клиента:", ZH: "客户确认：", JA: "顧客の確認：", PT: "Confirmação do cliente:", AR: "تأكيد العميل:", IT: "Conferma del cliente:" },
  termsWithdrawalPolicyConfirmation: { EN: "I expressly request the immediate delivery of the eSIM and acknowledge that my right of withdrawal expires upon delivery.", ES: "Solicito expresamente la entrega inmediata de la eSIM y reconozco que mi derecho de desistimiento expira con la entrega.", FR: "Je demande expressément la livraison immédiate de l'eSIM et reconnais que mon droit de rétractation expire dès la livraison.", DE: "Ich verlange ausdrücklich die sofortige Bereitstellung und weiß, dass mein Widerrufsrecht erlischt.", RU: "Я прямо прошу о немедленной доставке eSIM и признаю, что мое право на отзыв истекает после доставки.", ZH: "我明确要求立即交付 eSIM，并承认我的撤销权在交付后失效。", JA: "eSIM の即座の配信を明示的に要求し、配信時に撤回権が失効することを認めます。", PT: "Eu solicito expressamente a entrega imediata do eSIM e reconheço que meu direito de rescisão expira após a entrega.", AR: "أطلب صراحةً التسليم الفوري لـ eSIM وأقر بأن حق الانسحاب الخاص بي ينتهي عند التسليم.", IT: "Richiedo espressamente la consegna immediata dell'eSIM e riconosco che il mio diritto di recesso scade alla consegna." },
  
  // ============================================
  // TOKEN DISCLAIMER V3 – INSTITUTIONAL GRADE
  // ============================================
  termsTokenTitle: { EN: "5. Nomiqa Token – Institutional Legal Framework (Utility Token)", ES: "5. Token Nomiqa – Marco Legal Institucional (Token de Utilidad)", FR: "5. Token Nomiqa – Cadre Juridique Institutionnel (Token Utilitaire)", DE: "5. Nomiqa Token – Institutioneller Rechtsrahmen (Utility Token)", RU: "5. Токен Nomiqa – Институциональная правовая база (Утилитарный токен)", ZH: "5. Nomiqa 代币 – 机构法律框架（实用代币）", JA: "5. Nomiqa トークン – 機関向け法的枠組み（ユーティリティトークン）", PT: "5. Token Nomiqa – Quadro Legal Institucional (Token de Utilidade)", AR: "5. رمز Nomiqa – الإطار القانوني المؤسسي (رمز المنفعة)", IT: "5. Token Nomiqa – Quadro Giuridico Istituzionale (Token di Utilità)" },
  termsTokenIntro: { EN: "The Nomiqa Token (NMQ) is a non-financial utility token issued on the Solana blockchain, used exclusively for functional purposes within the Nomiqa DePIN ecosystem, including:", ES: "El Token Nomiqa (NMQ) es un token de utilidad no financiero emitido en la blockchain de Solana, utilizado exclusivamente para fines funcionales dentro del ecosistema Nomiqa DePIN, incluyendo:", FR: "Le Token Nomiqa (NMQ) est un token utilitaire non financier émis sur la blockchain Solana, utilisé exclusivement à des fins fonctionnelles au sein de l'écosystème Nomiqa DePIN, notamment :", DE: "Der Nomiqa Token (NMQ) ist ein nicht-finanzieller Utility Token auf der Solana-Blockchain, der ausschließlich für funktionale Zwecke innerhalb des Nomiqa DePIN-Ökosystems dient:", RU: "Токен Nomiqa (NMQ) — нефинансовый утилитарный токен, выпущенный на блокчейне Solana, используемый исключительно для функциональных целей в экосистеме Nomiqa DePIN:", ZH: "Nomiqa 代币（NMQ）是在 Solana 区块链上发行的非金融实用代币，专门用于 Nomiqa DePIN 生态系统内的功能目的：", JA: "Nomiqa トークン（NMQ）は、Solana ブロックチェーン上で発行された非金融ユーティリティトークンであり、Nomiqa DePIN エコシステム内の機能的目的にのみ使用されます：", PT: "O Token Nomiqa (NMQ) é um token de utilidade não financeiro emitido na blockchain Solana, usado exclusivamente para fins funcionais dentro do ecossistema Nomiqa DePIN:", AR: "رمز Nomiqa (NMQ) هو رمز منفعة غير مالي صادر على بلوكشين Solana، يُستخدم حصريًا لأغراض وظيفية ضمن نظام Nomiqa DePIN:", IT: "Il Token Nomiqa (NMQ) è un token di utilità non finanziario emesso sulla blockchain Solana, utilizzato esclusivamente per scopi funzionali all'interno dell'ecosistema Nomiqa DePIN:" },
  termsTokenItem1: { EN: "Contributor rewards for network data contributions", ES: "Recompensas por contribuciones de datos a la red", FR: "Récompenses pour les contributions de données au réseau", DE: "Contributor-Rewards für Netzwerkdaten-Beiträge", RU: "Вознаграждения за вклад данных в сеть", ZH: "网络数据贡献的贡献者奖励", JA: "ネットワークデータ貢献に対する報酬", PT: "Recompensas por contribuições de dados à rede", AR: "مكافآت المساهمين لمساهمات بيانات الشبكة", IT: "Ricompense per i contributi di dati alla rete" },
  termsTokenItem2: { EN: "Ecosystem benefits and feature unlocks", ES: "Beneficios del ecosistema y desbloqueo de funciones", FR: "Avantages écosystème et déblocage de fonctionnalités", DE: "Ökosystem-Vorteile und Feature-Freischaltungen", RU: "Преимущества экосистемы и разблокировка функций", ZH: "生态系统福利和功能解锁", JA: "エコシステムの特典と機能のアンロック", PT: "Benefícios do ecossistema e desbloqueio de recursos", AR: "مزايا النظام البيئي وفتح الميزات", IT: "Vantaggi dell'ecosistema e sblocco di funzionalità" },
  termsTokenItem3: { EN: "eSIM purchase discounts", ES: "Descuentos en compras de eSIM", FR: "Remises sur les achats eSIM", DE: "eSIM-Kaufrabatte", RU: "Скидки на покупку eSIM", ZH: "eSIM 购买折扣", JA: "eSIM 購入割引", PT: "Descontos em compras de eSIM", AR: "خصومات شراء eSIM", IT: "Sconti sugli acquisti eSIM" },
  termsTokenItem4: { EN: "Functional features within the Nomiqa DePIN platform", ES: "Funciones dentro de la plataforma Nomiqa DePIN", FR: "Fonctionnalités au sein de la plateforme Nomiqa DePIN", DE: "Funktionale Features innerhalb der Nomiqa DePIN-Plattform", RU: "Функциональные возможности в рамках платформы Nomiqa DePIN", ZH: "Nomiqa DePIN 平台内的功能特性", JA: "Nomiqa DePIN プラットフォーム内の機能", PT: "Recursos funcionais dentro da plataforma Nomiqa DePIN", AR: "الميزات الوظيفية داخل منصة Nomiqa DePIN", IT: "Funzionalità all'interno della piattaforma Nomiqa DePIN" },
  termsTokenNotTitle: { EN: "The token is NOT:", ES: "El token NO es:", FR: "Le token n'est PAS :", DE: "Der Token ist KEIN:", RU: "Токен НЕ является:", ZH: "代币不是：", JA: "トークンは以下ではありません：", PT: "O token NÃO é:", AR: "الرمز ليس:", IT: "Il token NON è:" },
  termsTokenNotItem1: { EN: "An investment or speculative instrument", ES: "Un instrumento de inversión o especulación", FR: "Un instrument d'investissement ou de spéculation", DE: "Ein Investitions- oder Spekulationsinstrument", RU: "Инвестиционным или спекулятивным инструментом", ZH: "投资或投机工具", JA: "投資または投機的手段", PT: "Um instrumento de investimento ou especulação", AR: "أداة استثمار أو مضاربة", IT: "Uno strumento di investimento o speculazione" },
  termsTokenNotItem2: { EN: "A security, equity share, or financial instrument under MiFID II", ES: "Un valor, acción o instrumento financiero bajo MiFID II", FR: "Un titre, une action ou un instrument financier au sens de MiFID II", DE: "Ein Wertpapier, eine Beteiligung oder ein Finanzinstrument gemäß MiFID II", RU: "Ценной бумагой, долей участия или финансовым инструментом по MiFID II", ZH: "MiFID II 下的证券、股权或金融工具", JA: "MiFID II に基づく証券、株式、または金融商品", PT: "Um título, ação ou instrumento financeiro nos termos da MiFID II", AR: "ورقة مالية أو حصة ملكية أو أداة مالية بموجب MiFID II", IT: "Un titolo, una partecipazione azionaria o uno strumento finanziario ai sensi di MiFID II" },
  termsTokenNotItem3: { EN: "E-money or a payment token under MiCA", ES: "Dinero electrónico o un token de pago bajo MiCA", FR: "De la monnaie électronique ou un token de paiement au sens de MiCA", DE: "E-Geld oder ein Zahlungstoken gemäß MiCA", RU: "Электронными деньгами или платежным токеном по MiCA", ZH: "MiCA 下的电子货币或支付代币", JA: "MiCA に基づく電子マネーまたは決済トークン", PT: "Dinheiro eletrônico ou um token de pagamento nos termos da MiCA", AR: "نقود إلكترونية أو رمز دفع بموجب MiCA", IT: "Moneta elettronica o un token di pagamento ai sensi del MiCA" },
  termsTokenNotItem4: { EN: "An asset-referenced token under MiCA", ES: "Un token referenciado en activos bajo MiCA", FR: "Un token adossé à des actifs au sens de MiCA", DE: "Ein Asset-Referenced Token gemäß MiCA", RU: "Токеном, привязанным к активам, по MiCA", ZH: "MiCA 下的资产参考代币", JA: "MiCA に基づく資産参照トークン", PT: "Um token referenciado em ativos nos termos da MiCA", AR: "رمز مرجعي للأصول بموجب MiCA", IT: "Un token referenziato ad asset ai sensi del MiCA" },
  termsTokenNotItem5: { EN: "A loan, derivative, or debt instrument", ES: "Un préstamo, derivado o instrumento de deuda", FR: "Un prêt, un dérivé ou un instrument de dette", DE: "Ein Darlehen, Derivat oder Schuldtitel", RU: "Кредитом, деривативом или долговым инструментом", ZH: "贷款、衍生品或债务工具", JA: "融資、デリバティブ、または債務商品", PT: "Um empréstimo, derivativo ou instrumento de dívida", AR: "قرضًا أو مشتقًا أو أداة دين", IT: "Un prestito, derivato o strumento di debito" },
  termsTokenNotItem6: { EN: "A promise of financial returns, dividends, or profit-sharing", ES: "Una promesa de retornos financieros, dividendos o participación en beneficios", FR: "Une promesse de rendements financiers, de dividendes ou de partage des bénéfices", DE: "Ein Versprechen finanzieller Renditen, Dividenden oder Gewinnbeteiligung", RU: "Обещанием финансовой доходности, дивидендов или участия в прибыли", ZH: "财务回报、股息或利润分享的承诺", JA: "金銭的リターン、配当、または利益分配の約束", PT: "Uma promessa de retornos financeiros, dividendos ou participação nos lucros", AR: "وعدًا بعوائد مالية أو أرباح أو تقاسم أرباح", IT: "Una promessa di rendimenti finanziari, dividendi o partecipazione agli utili" },

  // V3: Restricted Jurisdictions
  termsTokenRestrictedTitle: { EN: "Restricted Jurisdictions", ES: "Jurisdicciones Restringidas", FR: "Juridictions Restreintes", DE: "Eingeschränkte Jurisdiktionen", RU: "Ограниченные юрисдикции", ZH: "受限司法管辖区", JA: "制限対象法域", PT: "Jurisdições Restritas", AR: "الولايات القضائية المقيدة", IT: "Giurisdizioni Limitate" },
  termsTokenRestrictedContent: { EN: "The Nomiqa Token is not offered, distributed, or made available to persons or entities located in, or citizens of, any jurisdiction where the distribution, sale, or use of utility tokens is prohibited or restricted by law. This includes, but is not limited to:", ES: "El Token Nomiqa no se ofrece, distribuye ni pone a disposición de personas o entidades ubicadas en jurisdicciones donde la distribución de tokens de utilidad está prohibida o restringida por ley, incluyendo:", FR: "Le Token Nomiqa n'est pas offert, distribué ou mis à disposition de personnes situées dans des juridictions où la distribution de tokens utilitaires est interdite, notamment :", DE: "Der Nomiqa Token wird nicht in Jurisdiktionen angeboten, in denen die Verteilung von Utility Tokens verboten oder eingeschränkt ist, einschließlich:", RU: "Токен Nomiqa не предлагается лицам в юрисдикциях, где распространение утилитарных токенов запрещено или ограничено законом:", ZH: "Nomiqa 代币不向位于禁止或限制实用代币分发的司法管辖区的人员提供，包括但不限于：", JA: "Nomiqa トークンは、ユーティリティトークンの配布が禁止または制限されている法域の個人には提供されません：", PT: "O Token Nomiqa não é oferecido em jurisdições onde a distribuição de tokens de utilidade é proibida por lei, incluindo:", AR: "لا يتم تقديم رمز Nomiqa في الولايات القضائية التي يحظر فيها توزيع رموز المنفعة، بما في ذلك:", IT: "Il Token Nomiqa non è offerto in giurisdizioni dove la distribuzione di token di utilità è vietata, tra cui:" },
  termsTokenRestrictedItem1: { EN: "United States of America (including all territories and possessions) — in compliance with Regulation S under the U.S. Securities Act of 1933", ES: "Estados Unidos de América — en cumplimiento con la Regulación S de la Ley de Valores de EE.UU. de 1933", FR: "États-Unis d'Amérique — en conformité avec le Règlement S du Securities Act de 1933", DE: "Vereinigte Staaten von Amerika — gemäß Regulation S des U.S. Securities Act von 1933", RU: "Соединенные Штаты Америки — в соответствии с Положением S Закона о ценных бумагах США 1933 года", ZH: "美利坚合众国 — 依据美国 1933 年《证券法》S 条例", JA: "アメリカ合衆国 — 1933年米国証券法のレギュレーションSに準拠", PT: "Estados Unidos da América — em conformidade com a Regulação S da Lei de Valores Mobiliários dos EUA de 1933", AR: "الولايات المتحدة الأمريكية — وفقًا للائحة S بموجب قانون الأوراق المالية الأمريكي لعام 1933", IT: "Stati Uniti d'America — in conformità al Regolamento S del Securities Act del 1933" },
  termsTokenRestrictedItem2: { EN: "Any country, territory, or region subject to comprehensive sanctions imposed by the United Nations, OFAC (U.S.), the European Union, or His Majesty's Treasury (UK)", ES: "Cualquier país sujeto a sanciones integrales de la ONU, OFAC, la UE o HM Treasury", FR: "Tout pays soumis à des sanctions globales de l'ONU, de l'OFAC, de l'UE ou de HM Treasury", DE: "Jedes Land unter umfassenden Sanktionen der UN, OFAC, EU oder HM Treasury", RU: "Любая страна под всеобъемлющими санкциями ООН, OFAC, ЕС или HM Treasury", ZH: "受联合国、OFAC、欧盟或英国财政部全面制裁的任何国家", JA: "国連、OFAC、EU、または英国財務省による包括的制裁対象の国", PT: "Qualquer país sujeito a sanções abrangentes da ONU, OFAC, UE ou HM Treasury", AR: "أي بلد خاضع لعقوبات شاملة من الأمم المتحدة أو OFAC أو الاتحاد الأوروبي أو خزانة صاحب الجلالة", IT: "Qualsiasi paese soggetto a sanzioni globali ONU, OFAC, UE o HM Treasury" },
  termsTokenRestrictedItem3: { EN: "Any jurisdiction where the acquisition, holding, or use of blockchain-based tokens is prohibited", ES: "Cualquier jurisdicción donde la adquisición de tokens basados en blockchain está prohibida", FR: "Toute juridiction où l'acquisition de tokens basés sur la blockchain est interdite", DE: "Jede Jurisdiktion, in der der Erwerb blockchain-basierter Token verboten ist", RU: "Любая юрисдикция, где приобретение токенов на основе блокчейна запрещено", ZH: "任何禁止获取基于区块链的代币的司法管辖区", JA: "ブロックチェーンベースのトークンの取得が禁止されている法域", PT: "Qualquer jurisdição onde a aquisição de tokens baseados em blockchain é proibida", AR: "أي ولاية قضائية يحظر فيها اقتناء الرموز المستندة إلى البلوكشين", IT: "Qualsiasi giurisdizione dove l'acquisizione di token basati su blockchain è vietata" },

  // V3: Purchaser Representation
  termsTokenPurchaserTitle: { EN: "Purchaser Representation & Acknowledgement", ES: "Declaración y Reconocimiento del Comprador", FR: "Déclaration et Reconnaissance de l'Acheteur", DE: "Käufererklärung & Bestätigung", RU: "Заявление и подтверждение покупателя", ZH: "购买者声明和确认", JA: "購入者の表明および承認", PT: "Declaração e Reconhecimento do Comprador", AR: "إقرار واعتراف المشتري", IT: "Dichiarazione e Riconoscimento dell'Acquirente" },
  termsTokenPurchaserContent: { EN: "By acquiring, holding, or using the Nomiqa Token, you represent and warrant that:", ES: "Al adquirir o usar el Token Nomiqa, usted declara y garantiza que:", FR: "En acquérant le Token Nomiqa, vous déclarez et garantissez que :", DE: "Mit dem Erwerb des Nomiqa Tokens erklären und bestätigen Sie:", RU: "Приобретая токен Nomiqa, вы заявляете и гарантируете, что:", ZH: "通过获取 Nomiqa 代币，您声明并保证：", JA: "Nomiqa トークンを取得することにより、あなたは以下を表明し保証します：", PT: "Ao adquirir o Token Nomiqa, você declara e garante que:", AR: "من خلال الحصول على رمز Nomiqa، فإنك تقر وتضمن أن:", IT: "Acquisendo il Token Nomiqa, dichiari e garantisci che:" },
  termsTokenPurchaserItem1: { EN: "You acquire the token for functional use within the Nomiqa ecosystem, not as an investment", ES: "Adquiere el token para uso funcional, no como inversión", FR: "Vous acquérez le token pour un usage fonctionnel, pas comme investissement", DE: "Sie erwerben den Token zur funktionalen Nutzung, nicht als Investment", RU: "Вы приобретаете токен для функционального использования, а не как инвестицию", ZH: "您获取代币用于功能性使用，而非投资", JA: "投資としてではなく、機能的使用のためにトークンを取得します", PT: "Você adquire o token para uso funcional, não como investimento", AR: "تحصل على الرمز للاستخدام الوظيفي وليس كاستثمار", IT: "Acquisisci il token per uso funzionale, non come investimento" },
  termsTokenPurchaserItem2: { EN: "You have no expectation of profit, price appreciation, or financial return from holding the token", ES: "No tiene expectativa de ganancia o rendimiento financiero por poseer el token", FR: "Vous n'attendez aucun profit ou rendement financier de la détention du token", DE: "Sie haben keine Gewinnerwartung oder Erwartung einer Preissteigerung", RU: "Вы не ожидаете прибыли или финансового дохода от владения токеном", ZH: "您不期望从持有代币获得利润或财务回报", JA: "トークンの保有から利益や金銭的リターンを期待していません", PT: "Você não tem expectativa de lucro ou retorno financeiro pela posse do token", AR: "ليس لديك أي توقع للربح أو العائد المالي من حيازة الرمز", IT: "Non hai aspettative di profitto o rendimento finanziario dal possesso del token" },
  termsTokenPurchaserItem3: { EN: "You are fully aware of the risks inherent in blockchain technology, including but not limited to volatility, technical failure, and regulatory changes", ES: "Es plenamente consciente de los riesgos inherentes a la tecnología blockchain", FR: "Vous êtes pleinement conscient des risques inhérents à la technologie blockchain", DE: "Sie sind sich der Risiken der Blockchain-Technologie voll bewusst", RU: "Вы полностью осведомлены о рисках, связанных с технологией блокчейн", ZH: "您充分了解区块链技术固有的风险", JA: "ブロックチェーン技術に固有のリスクを十分に認識しています", PT: "Você está plenamente ciente dos riscos inerentes à tecnologia blockchain", AR: "أنت على دراية تامة بالمخاطر الكامنة في تكنولوجيا البلوكشين", IT: "Sei pienamente consapevole dei rischi inerenti alla tecnologia blockchain" },
  termsTokenPurchaserItem4: { EN: "You are in compliance with all applicable laws and regulations of your jurisdiction regarding the use of digital tokens", ES: "Cumple con todas las leyes aplicables de su jurisdicción respecto al uso de tokens digitales", FR: "Vous êtes en conformité avec toutes les lois applicables de votre juridiction", DE: "Sie halten alle geltenden Gesetze Ihrer Jurisdiktion bezüglich digitaler Token ein", RU: "Вы соблюдаете все применимые законы вашей юрисдикции в отношении использования цифровых токенов", ZH: "您遵守您所在司法管辖区有关使用数字代币的所有适用法律", JA: "デジタルトークンの使用に関する管轄法域のすべての適用法令を遵守しています", PT: "Você está em conformidade com todas as leis aplicáveis de sua jurisdição em relação ao uso de tokens digitais", AR: "أنت ملتزم بجميع القوانين المعمول بها في ولايتك القضائية فيما يتعلق باستخدام الرموز الرقمية", IT: "Sei in conformità con tutte le leggi applicabili della tua giurisdizione riguardo ai token digitali" },
  termsTokenPurchaserItem5: { EN: "You are not a U.S. person as defined under Regulation S of the U.S. Securities Act of 1933", ES: "No es una persona estadounidense según la Regulación S de la Ley de Valores de EE.UU.", FR: "Vous n'êtes pas une personne américaine au sens du Règlement S", DE: "Sie sind keine U.S.-Person gemäß Regulation S des U.S. Securities Act", RU: "Вы не являетесь лицом США согласно Положению S Закона о ценных бумагах", ZH: "您不是美国 1933 年《证券法》S 条例定义的美国人士", JA: "米国証券法レギュレーションSに定義される米国人ではありません", PT: "Você não é uma pessoa dos EUA conforme definido na Regulação S", AR: "أنت لست شخصًا أمريكيًا وفقًا لتعريف اللائحة S", IT: "Non sei una persona statunitense ai sensi del Regolamento S" },

  // V3: Vesting
  termsTokenVestingTitle: { EN: "Token Vesting & Lock-Up", ES: "Vesting y Bloqueo de Tokens", FR: "Vesting et Verrouillage des Tokens", DE: "Token Vesting & Lock-Up", RU: "Вестинг токенов и период блокировки", ZH: "代币归属和锁定", JA: "トークンのベスティングとロックアップ", PT: "Vesting e Bloqueio de Tokens", AR: "استحقاق الرموز والإغلاق", IT: "Vesting e Lock-Up dei Token" },
  termsTokenVestingContent: { EN: "Tokens distributed through private sale, team allocations, or strategic partnerships may be subject to vesting schedules including, but not limited to: lock-up periods, cliff periods, time-based linear or milestone-based vesting, smart contract–enforced restrictions, and partial release at Token Generation Event (TGE). The specific vesting terms shall be set forth in the relevant individual agreement. No purchaser or recipient shall have a claim to immediate liquidity or tradability of tokens subject to vesting.", ES: "Los tokens distribuidos a través de venta privada pueden estar sujetos a calendarios de vesting incluyendo: períodos de bloqueo, cliff, vesting lineal o por hitos, y restricciones por contrato inteligente.", FR: "Les tokens distribués par vente privée peuvent être soumis à des calendriers de vesting incluant : périodes de blocage, cliff, vesting linéaire ou par jalons, et restrictions par contrat intelligent.", DE: "Tokens aus Private Sales oder strategischen Partnerschaften können Vesting-Zeitplänen unterliegen, einschließlich Lock-up, Cliff, linearem oder Milestone-basiertem Vesting und Smart-Contract-Beschränkungen.", RU: "Токены, распределённые через частную продажу, могут подлежать графикам вестинга, включая: периоды блокировки, клифф, линейный вестинг и ограничения смарт-контрактов.", ZH: "通过私募分配的代币可能受归属时间表的约束，包括：锁定期、悬崖期、基于时间或里程碑的归属以及智能合约限制。", JA: "プライベートセールを通じて配布されたトークンは、ロックアップ期間、クリフ期間、時間ベースまたはマイルストーンベースのベスティング、スマートコントラクトによる制限を含むベスティングスケジュールの対象となる場合があります。", PT: "Tokens distribuídos através de venda privada podem estar sujeitos a cronogramas de vesting, incluindo: períodos de bloqueio, cliff, vesting linear ou por marcos, e restrições por contrato inteligente.", AR: "قد تخضع الرموز الموزعة من خلال البيع الخاص لجداول استحقاق تشمل: فترات الإغلاق، والهاوية، والاستحقاق الخطي أو القائم على المعالم، وقيود العقود الذكية.", IT: "I token distribuiti attraverso vendita privata possono essere soggetti a programmi di vesting, inclusi: periodi di lock-up, cliff, vesting lineare o basato su milestone, e restrizioni tramite smart contract." },

  // V3: Secondary Market
  termsTokenSecondaryTitle: { EN: "Secondary Market Liability Exclusion", ES: "Exclusión de Responsabilidad del Mercado Secundario", FR: "Exclusion de Responsabilité du Marché Secondaire", DE: "Haftungsausschluss Sekundärmarkt", RU: "Исключение ответственности на вторичном рынке", ZH: "二级市场责任排除", JA: "二次市場の責任除外", PT: "Exclusão de Responsabilidade do Mercado Secundário", AR: "استبعاد مسؤولية السوق الثانوية", IT: "Esclusione di Responsabilità del Mercato Secondario" },
  termsTokenSecondaryContent: { EN: "Business Unlimited Worldwide Ltd. bears no responsibility or liability for any losses, damages, or claims arising from the trading, listing, or exchange of the Nomiqa Token on any secondary market, decentralised exchange (DEX), or centralised exchange (CEX). No guarantees of liquidity, market availability, or price stability are made or implied. The Company does not control, endorse, or guarantee the availability of the token on any third-party platform.", ES: "Business Unlimited Worldwide Ltd. no asume ninguna responsabilidad por pérdidas derivadas de la negociación del Token Nomiqa en cualquier mercado secundario, DEX o CEX. No se ofrecen garantías de liquidez, disponibilidad o estabilidad de precios.", FR: "Business Unlimited Worldwide Ltd. n'assume aucune responsabilité pour les pertes résultant de l'échange du Token Nomiqa sur tout marché secondaire, DEX ou CEX. Aucune garantie de liquidité ou de stabilité des prix n'est donnée.", DE: "Business Unlimited Worldwide Ltd. übernimmt keine Haftung für Verluste aus dem Handel des Nomiqa Tokens auf Sekundärmärkten, DEXs oder CEXs. Es werden keine Garantien für Liquidität, Marktverfügbarkeit oder Preisstabilität gegeben.", RU: "Business Unlimited Worldwide Ltd. не несёт ответственности за убытки от торговли токеном Nomiqa на любом вторичном рынке, DEX или CEX. Никаких гарантий ликвидности или стабильности цен не предоставляется.", ZH: "Business Unlimited Worldwide Ltd. 对因在任何二级市场、DEX 或 CEX 上交易 Nomiqa 代币而产生的任何损失不承担任何责任。不提供流动性或价格稳定性的保证。", JA: "Business Unlimited Worldwide Ltd. は、二次市場、DEX、または CEX での Nomiqa トークンの取引から生じるいかなる損失についても責任を負いません。流動性または価格安定性の保証はありません。", PT: "Business Unlimited Worldwide Ltd. não assume responsabilidade por perdas decorrentes da negociação do Token Nomiqa em qualquer mercado secundário, DEX ou CEX. Nenhuma garantia de liquidez ou estabilidade de preços é oferecida.", AR: "لا تتحمل Business Unlimited Worldwide Ltd. أي مسؤولية عن الخسائر الناتجة عن تداول رمز Nomiqa في أي سوق ثانوية أو DEX أو CEX. لا يتم تقديم أي ضمانات للسيولة أو استقرار الأسعار.", IT: "Business Unlimited Worldwide Ltd. non si assume alcuna responsabilità per perdite derivanti dallo scambio del Token Nomiqa su qualsiasi mercato secondario, DEX o CEX. Non vengono fornite garanzie di liquidità o stabilità dei prezzi." },

  // V3: Governance Rights Exclusion
  termsTokenGovernanceTitle: { EN: "No Governance, Equity, or Ownership Rights", ES: "Sin Derechos de Gobernanza, Capital o Propiedad", FR: "Aucun Droit de Gouvernance, de Capital ou de Propriété", DE: "Keine Governance-, Beteiligungs- oder Eigentumsrechte", RU: "Отсутствие прав управления, участия или собственности", ZH: "无治理、股权或所有权", JA: "ガバナンス権、持分権、所有権なし", PT: "Sem Direitos de Governança, Participação ou Propriedade", AR: "لا حقوق حوكمة أو ملكية أو حقوق ملكية", IT: "Nessun Diritto di Governance, Partecipazione o Proprietà" },
  termsTokenGovernanceContent: { EN: "The Nomiqa Token does not confer upon holders any of the following rights:", ES: "El Token Nomiqa no otorga a los titulares ninguno de los siguientes derechos:", FR: "Le Token Nomiqa ne confère aux détenteurs aucun des droits suivants :", DE: "Der Nomiqa Token gewährt Inhabern keine der folgenden Rechte:", RU: "Токен Nomiqa не предоставляет держателям следующих прав:", ZH: "Nomiqa 代币不授予持有者以下任何权利：", JA: "Nomiqa トークンは保有者に以下の権利を付与しません：", PT: "O Token Nomiqa não confere aos titulares nenhum dos seguintes direitos:", AR: "لا يمنح رمز Nomiqa حامليه أيًا من الحقوق التالية:", IT: "Il Token Nomiqa non conferisce ai titolari nessuno dei seguenti diritti:" },
  termsTokenGovernanceItem1: { EN: "Voting rights in corporate decisions", ES: "Derechos de voto en decisiones corporativas", FR: "Droits de vote dans les décisions de l'entreprise", DE: "Stimmrechte bei Unternehmensentscheidungen", RU: "Право голоса в корпоративных решениях", ZH: "公司决策中的投票权", JA: "企業の意思決定における議決権", PT: "Direitos de voto em decisões corporativas", AR: "حقوق التصويت في قرارات الشركة", IT: "Diritti di voto nelle decisioni aziendali" },
  termsTokenGovernanceItem2: { EN: "Equity or ownership interest in Business Unlimited Worldwide Ltd.", ES: "Interés de capital o propiedad en Business Unlimited Worldwide Ltd.", FR: "Participation au capital ou droit de propriété dans Business Unlimited Worldwide Ltd.", DE: "Kapitalbeteiligung an der Business Unlimited Worldwide Ltd.", RU: "Долевое участие в Business Unlimited Worldwide Ltd.", ZH: "对 Business Unlimited Worldwide Ltd. 的股权或所有权", JA: "Business Unlimited Worldwide Ltd. の持分または所有権", PT: "Participação acionária em Business Unlimited Worldwide Ltd.", AR: "حصة ملكية في Business Unlimited Worldwide Ltd.", IT: "Partecipazione azionaria in Business Unlimited Worldwide Ltd." },
  termsTokenGovernanceItem3: { EN: "Revenue share, dividends, or profit distributions", ES: "Participación en ingresos, dividendos o distribución de beneficios", FR: "Part des revenus, dividendes ou distribution de bénéfices", DE: "Umsatzbeteiligung, Dividenden oder Gewinnausschüttungen", RU: "Участие в доходах, дивидендах или распределении прибыли", ZH: "收入分成、股息或利润分配", JA: "収益分配、配当、または利益分配", PT: "Participação na receita, dividendos ou distribuição de lucros", AR: "تقاسم الإيرادات أو الأرباح أو التوزيعات", IT: "Partecipazione ai ricavi, dividendi o distribuzione degli utili" },
  termsTokenGovernanceItem4: { EN: "Claims against the Company's assets or reserves", ES: "Reclamaciones contra los activos o reservas de la Compañía", FR: "Créances sur les actifs ou réserves de la Société", DE: "Ansprüche gegen das Vermögen oder die Reserven der Gesellschaft", RU: "Претензии к активам или резервам Компании", ZH: "对公司资产或储备金的索赔", JA: "会社の資産または準備金に対する請求権", PT: "Reivindicações contra os ativos ou reservas da Empresa", AR: "مطالبات ضد أصول أو احتياطيات الشركة", IT: "Diritti sugli asset o riserve della Società" },
  termsTokenGovernanceItem5: { EN: "Any right to influence operational, strategic, or business decisions of the Company", ES: "Cualquier derecho a influir en las decisiones operacionales de la Compañía", FR: "Tout droit d'influencer les décisions opérationnelles de la Société", DE: "Jegliches Recht, operative oder strategische Entscheidungen der Gesellschaft zu beeinflussen", RU: "Любое право влиять на операционные решения Компании", ZH: "任何影响公司运营或战略决策的权利", JA: "会社の業務上の意思決定に影響を及ぼす権利", PT: "Qualquer direito de influenciar decisões operacionais da Empresa", AR: "أي حق في التأثير على القرارات التشغيلية للشركة", IT: "Qualsiasi diritto di influenzare le decisioni operative della Società" },

  // V3: No Public Offering
  termsTokenNoOfferingTitle: { EN: "No Public Offering", ES: "Sin Oferta Pública", FR: "Pas d'Offre Publique", DE: "Kein öffentliches Angebot", RU: "Отсутствие публичного предложения", ZH: "非公开发行", JA: "公募なし", PT: "Sem Oferta Pública", AR: "لا طرح عام", IT: "Nessuna Offerta Pubblica" },
  termsTokenNoOfferingContent: { EN: "The distribution of the Nomiqa Token does not constitute a public offering of securities in any jurisdiction. No prospectus, offering memorandum, or registration statement has been filed with any securities regulator. The token is distributed solely as a functional utility within the Nomiqa ecosystem.", ES: "La distribución del Token Nomiqa no constituye una oferta pública de valores. No se ha presentado ningún prospecto ante ningún regulador de valores.", FR: "La distribution du Token Nomiqa ne constitue pas une offre publique de titres. Aucun prospectus n'a été déposé auprès d'un régulateur.", DE: "Die Verteilung des Nomiqa Tokens stellt kein öffentliches Angebot von Wertpapieren dar. Es wurde kein Prospekt bei einer Wertpapieraufsichtsbehörde eingereicht.", RU: "Распространение токена Nomiqa не является публичным предложением ценных бумаг. Никакой проспект не был подан в регулирующий орган.", ZH: "Nomiqa 代币的分发不构成任何司法管辖区的证券公开发行。未向任何证券监管机构提交招股说明书。", JA: "Nomiqa トークンの配布は、いかなる法域においても証券の公募を構成するものではありません。", PT: "A distribuição do Token Nomiqa não constitui uma oferta pública de valores mobiliários. Nenhum prospecto foi arquivado junto a qualquer regulador.", AR: "لا يشكل توزيع رمز Nomiqa طرحًا عامًا للأوراق المالية. لم يتم تقديم أي نشرة إلى أي جهة تنظيمية.", IT: "La distribuzione del Token Nomiqa non costituisce un'offerta pubblica di titoli. Nessun prospetto è stato depositato presso alcun regolatore." },

  // V3: Blockchain Finality
  termsTokenBlockchainTitle: { EN: "Blockchain Finality & Technical Risks", ES: "Finalidad de Blockchain y Riesgos Técnicos", FR: "Finalité Blockchain et Risques Techniques", DE: "Blockchain-Finalität & Technische Risiken", RU: "Финальность блокчейна и технические риски", ZH: "区块链最终性和技术风险", JA: "ブロックチェーンの確定性と技術的リスク", PT: "Finalidade do Blockchain e Riscos Técnicos", AR: "نهائية البلوكشين والمخاطر الفنية", IT: "Finalità Blockchain e Rischi Tecnici" },
  termsTokenBlockchainContent: { EN: "All transactions executed on the Solana blockchain are final, irreversible, and immutable. The Company has no ability to reverse, modify, cancel, or refund any blockchain transaction once confirmed by the network. The Company does not control, operate, or maintain the Solana blockchain network and assumes no responsibility for network congestion, downtime, forks, or protocol changes. Users are solely responsible for the security of their private keys and wallet credentials.", ES: "Todas las transacciones en la blockchain de Solana son finales, irreversibles e inmutables. La Compañía no puede revertir ninguna transacción de blockchain.", FR: "Toutes les transactions sur la blockchain Solana sont finales, irréversibles et immuables. La Société ne peut annuler aucune transaction blockchain.", DE: "Alle Transaktionen auf der Solana-Blockchain sind endgültig, irreversibel und unveränderlich. Das Unternehmen kann keine Blockchain-Transaktionen rückgängig machen.", RU: "Все транзакции на блокчейне Solana являются окончательными, необратимыми и неизменяемыми. Компания не может отменить транзакции блокчейна.", ZH: "Solana 区块链上的所有交易都是最终的、不可逆的和不可变的。公司无法撤销任何区块链交易。", JA: "Solana ブロックチェーン上のすべての取引は最終的、不可逆的、不変です。当社はブロックチェーン取引を元に戻すことはできません。", PT: "Todas as transações na blockchain Solana são finais, irreversíveis e imutáveis. A Empresa não pode reverter transações de blockchain.", AR: "جميع المعاملات على بلوكشين Solana نهائية وغير قابلة للإلغاء وغير قابلة للتغيير. لا تستطيع الشركة عكس أي معاملة بلوكشين.", IT: "Tutte le transazioni sulla blockchain Solana sono definitive, irreversibili e immutabili. La Società non può annullare transazioni blockchain." },

  // V3: AML & Compliance
  termsTokenAMLTitle: { EN: "AML & Compliance", ES: "AML y Cumplimiento", FR: "AML et Conformité", DE: "AML & Compliance", RU: "ПОД и соответствие требованиям", ZH: "反洗钱与合规", JA: "AML とコンプライアンス", PT: "AML e Conformidade", AR: "مكافحة غسل الأموال والامتثال", IT: "AML e Conformità" },
  termsTokenAMLContent: { EN: "Business Unlimited Worldwide Ltd. reserves the right to conduct Anti-Money Laundering (AML) and Know Your Customer (KYC) checks at any time, and to refuse, suspend, or terminate participation in the token ecosystem where compliance requirements are not met, where suspicious activity is detected, or where required by applicable law or regulation. The Company may request additional documentation or information at its sole discretion.", ES: "Business Unlimited Worldwide Ltd. se reserva el derecho de realizar verificaciones AML y KYC y de rechazar la participación cuando no se cumplan los requisitos de cumplimiento.", FR: "Business Unlimited Worldwide Ltd. se réserve le droit d'effectuer des vérifications AML et KYC et de refuser la participation en cas de non-conformité.", DE: "Business Unlimited Worldwide Ltd. behält sich das Recht vor, AML- und KYC-Prüfungen durchzuführen und die Teilnahme am Token-Ökosystem zu verweigern.", RU: "Business Unlimited Worldwide Ltd. оставляет за собой право проводить проверки AML и KYC и отказывать в участии в экосистеме токенов.", ZH: "Business Unlimited Worldwide Ltd. 保留进行 AML 和 KYC 检查的权利，并有权拒绝参与代币生态系统。", JA: "Business Unlimited Worldwide Ltd. は、AML および KYC チェックを実施し、コンプライアンス要件が満たされない場合にトークンエコシステムへの参加を拒否する権利を留保します。", PT: "Business Unlimited Worldwide Ltd. reserva-se o direito de realizar verificações AML e KYC e recusar a participação no ecossistema de tokens.", AR: "تحتفظ Business Unlimited Worldwide Ltd. بالحق في إجراء فحوصات AML و KYC ورفض المشاركة في نظام الرموز البيئي.", IT: "Business Unlimited Worldwide Ltd. si riserva il diritto di effettuare verifiche AML e KYC e di rifiutare la partecipazione nell'ecosistema dei token." },

  // V3: Marketing Consistency
  termsTokenMarketingTitle: { EN: "Marketing & Communication Disclaimer", ES: "Descargo de Responsabilidad de Marketing", FR: "Clause de Non-Responsabilité Marketing", DE: "Marketing- & Kommunikationshaftungsausschluss", RU: "Отказ от ответственности за маркетинг", ZH: "营销和传播免责声明", JA: "マーケティングおよびコミュニケーション免責事項", PT: "Isenção de Responsabilidade de Marketing", AR: "إخلاء مسؤولية التسويق", IT: "Disclaimer Marketing e Comunicazione" },
  termsTokenMarketingContent: { EN: "Any marketing materials, social media posts, community communications, or promotional content published by or on behalf of Nomiqa are for informational purposes only and do not constitute contractual obligations, financial advice, or binding projections. No forward-looking statement, roadmap update, or public comment shall be interpreted as a guarantee of future performance, price, features, or token value. Users should rely solely on these Terms and any formally executed agreements.", ES: "Cualquier material de marketing publicado por Nomiqa es solo informativo y no constituye obligaciones contractuales, asesoramiento financiero o proyecciones vinculantes.", FR: "Tout matériel marketing publié par Nomiqa est à titre informatif uniquement et ne constitue pas des obligations contractuelles ou des conseils financiers.", DE: "Jegliche von Nomiqa veröffentlichten Marketingmaterialien dienen ausschließlich Informationszwecken und stellen keine vertraglichen Verpflichtungen oder Finanzberatung dar.", RU: "Любые маркетинговые материалы Nomiqa носят исключительно информационный характер и не являются договорными обязательствами или финансовыми консультациями.", ZH: "Nomiqa 发布的任何营销材料仅供参考，不构成合同义务、财务建议或约束性预测。", JA: "Nomiqa が公開するマーケティング資料は情報提供のみを目的とし、契約上の義務、財務アドバイス、または拘束力のある予測を構成するものではありません。", PT: "Qualquer material de marketing publicado pela Nomiqa é apenas informativo e não constitui obrigações contratuais ou aconselhamento financeiro.", AR: "أي مواد تسويقية تنشرها Nomiqa هي لأغراض إعلامية فقط ولا تشكل التزامات تعاقدية أو نصائح مالية.", IT: "Qualsiasi materiale di marketing pubblicato da Nomiqa è solo a scopo informativo e non costituisce obblighi contrattuali o consulenza finanziaria." },

  // V3: Guarantees section (enhanced)
  termsTokenGuarantees: { EN: "No Guarantees", ES: "Sin Garantías", FR: "Aucune Garantie", DE: "Keine Garantien", RU: "Отсутствие гарантий", ZH: "无保证", JA: "保証なし", PT: "Sem Garantias", AR: "لا ضمانات", IT: "Nessuna Garanzia" },
  termsTokenGuaranteeItem1: { EN: "Price development, stability, or appreciation", ES: "Desarrollo, estabilidad o apreciación de precios", FR: "Évolution, stabilité ou appréciation des prix", DE: "Preisentwicklung, Stabilität oder Wertsteigerung", RU: "Развитие, стабильность или рост цен", ZH: "价格发展、稳定性或增值", JA: "価格の推移、安定性、または上昇", PT: "Desenvolvimento, estabilidade ou valorização de preços", AR: "تطور الأسعار أو استقرارها أو ارتفاعها", IT: "Sviluppo, stabilità o apprezzamento dei prezzi" },
  termsTokenGuaranteeItem2: { EN: "Market value or exchange listing", ES: "Valor de mercado o cotización en bolsa", FR: "Valeur marchande ou cotation en bourse", DE: "Marktwert oder Börsennotierung", RU: "Рыночная стоимость или листинг на бирже", ZH: "市场价值或交易所上市", JA: "市場価値または取引所上場", PT: "Valor de mercado ou listagem em bolsa", AR: "القيمة السوقية أو الإدراج في البورصة", IT: "Valore di mercato o quotazione in borsa" },
  termsTokenGuaranteeItem3: { EN: "Future use cases, integrations, or ecosystem expansion", ES: "Casos de uso futuros, integraciones o expansión del ecosistema", FR: "Cas d'usage futurs, intégrations ou expansion de l'écosystème", DE: "Zukünftige Anwendungsfälle, Integrationen oder Ökosystem-Erweiterung", RU: "Будущие варианты использования, интеграции или расширение экосистемы", ZH: "未来用例、集成或生态系统扩展", JA: "将来のユースケース、統合、またはエコシステムの拡大", PT: "Casos de uso futuros, integrações ou expansão do ecossistema", AR: "حالات الاستخدام المستقبلية أو التكاملات أو توسيع النظام البيئي", IT: "Casi d'uso futuri, integrazioni o espansione dell'ecosistema" },
  termsTokenGuaranteeItem4: { EN: "Liquidity, tradability, or availability on any platform", ES: "Liquidez, comerciabilidad o disponibilidad en cualquier plataforma", FR: "Liquidité, négociabilité ou disponibilité sur toute plateforme", DE: "Liquidität, Handelbarkeit oder Verfügbarkeit auf einer Plattform", RU: "Ликвидность, торгуемость или доступность на какой-либо платформе", ZH: "流动性、可交易性或在任何平台上的可用性", JA: "流動性、取引可能性、またはプラットフォームでの利用可能性", PT: "Liquidez, negociabilidade ou disponibilidade em qualquer plataforma", AR: "السيولة أو القابلية للتداول أو التوفر على أي منصة", IT: "Liquidità, negoziabilità o disponibilità su qualsiasi piattaforma" },
  termsTokenVoluntary: { EN: "Use of the Nomiqa Token is entirely voluntary, purely functional, and subject to these Terms. No person or entity should acquire, hold, or use the token with any expectation of profit or financial gain.", ES: "El uso del Token Nomiqa es completamente voluntario y puramente funcional. Ninguna persona debe adquirirlo con expectativa de ganancia financiera.", FR: "L'utilisation du Token Nomiqa est entièrement volontaire et purement fonctionnelle. Aucune personne ne doit l'acquérir avec une attente de gain financier.", DE: "Die Nutzung des Nomiqa Tokens ist vollständig freiwillig und rein funktional. Niemand sollte den Token mit Gewinnerwartung erwerben.", RU: "Использование токена Nomiqa полностью добровольно и носит исключительно функциональный характер. Никто не должен приобретать токен в ожидании прибыли.", ZH: "Nomiqa 代币的使用完全是自愿的且纯功能性的。任何人不应带有盈利预期获取该代币。", JA: "Nomiqa トークンの使用は完全に任意であり、純粋に機能的です。利益の期待を持ってトークンを取得すべきではありません。", PT: "O uso do Token Nomiqa é inteiramente voluntário e puramente funcional. Ninguém deve adquiri-lo com expectativa de lucro financeiro.", AR: "استخدام رمز Nomiqa طوعي تمامًا ووظيفي بحت. لا يجب على أي شخص اقتنائه بتوقع ربح مالي.", IT: "L'uso del Token Nomiqa è interamente volontario e puramente funzionale. Nessuno dovrebbe acquisirlo con aspettativa di guadagno finanziario." },
};
