project_id = "gzhmbiopiciugriatsdb"

[functions.airlo-products]
verify_jwt = false

[functions.update-prices-from-csv]
verify_jwt = false

[functions.webhook-async-order]
verify_jwt = false

[functions.track-affiliate-click]
verify_jwt = false
