project_id = "gzhmbiopiciugriatsdb"

[functions.airlo-products]
verify_jwt = true

[functions.update-prices-from-csv]
verify_jwt = true

[functions.webhook-async-order]
verify_jwt = false

[functions.track-affiliate-registration]
verify_jwt = false

[functions.create-helio-paylink]
verify_jwt = false

[functions.helio-webhook]
verify_jwt = false

[functions.get-order-by-token]
verify_jwt = false

[functions.create-affiliate]
verify_jwt = false

[functions.chat-support]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.verify-email-code]
verify_jwt = false

[functions.resend-verification-code]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.submit-claim-request]
verify_jwt = true

[functions.submit-order]
verify_jwt = true

[functions.notify-tier-upgrade]
verify_jwt = false

[functions.get-esim-usage]
verify_jwt = true

[functions.register-network]
verify_jwt = false

[functions.auth-email-hook]
verify_jwt = false

[functions.signup-user]
verify_jwt = false

[functions.sync-contribution-data]
verify_jwt = true

[functions.get-contribution-stats]
verify_jwt = true

[functions.get-my-orders]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.get-global-coverage]
verify_jwt = false