project_id = "gzhmbiopiciugriatsdb"

[functions.airlo-products]
verify_jwt = true

[functions.recover-order]
verify_jwt = true

[functions.update-prices-from-csv]
verify_jwt = true

[functions.webhook-async-order]
verify_jwt = false

[functions.track-affiliate-click]
verify_jwt = false

[functions.create-helio-paylink]
verify_jwt = false

[functions.helio-webhook]
verify_jwt = false

[functions.get-order-by-token]
verify_jwt = false

[functions.create-affiliate]
verify_jwt = false

[functions.chat-support]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.verify-email-code]
verify_jwt = false

[functions.resend-verification-code]
verify_jwt = false

[functions.reset-password]
verify_jwt = false
