import { createContext, useContext, useEffect, useMemo, useState, ReactNode } from "react";

export type Language = "EN" | "ES" | "FR" | "DE" | "RU" | "ZH" | "JA" | "PT" | "AR" | "IT";

interface TranslationContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const TranslationContext = createContext<TranslationContextType | undefined>(undefined);

// Comprehensive translations for all pages and components
const translations: Record<string, Partial<Record<Language | 'HI', string>>> = {
  // Navigation
  shop: { EN: "Shop", ES: "Tienda", FR: "Boutique", DE: "Shop", RU: "Магазин", ZH: "商店", JA: "ショップ", PT: "Loja", AR: "المتجر", IT: "Negozio" },
  gettingStarted: { EN: "Getting Started", ES: "Cómo empezar", FR: "Commencer", DE: "Erste Schritte", RU: "Начало работы", ZH: "入门指南", JA: "はじめに", PT: "Primeiros passos", AR: "البدء", IT: "Inizia" },
  howToBuy: { EN: "How to Buy (SOL & $NOMIQA token)", ES: "Cómo comprar (SOL y token $NOMIQA)", FR: "Comment acheter (SOL et jeton $NOMIQA)", DE: "So kaufst du (SOL & $NOMIQA-Token)", RU: "Как купить (SOL и токен $NOMIQA)", ZH: "如何购买（SOL 和 $NOMIQA 代币）", JA: "購入方法（SOL と $NOMIQA トークン）", PT: "Como comprar (SOL e token $NOMIQA)", AR: "طريقة الشراء (SOL و رمز $NOMIQA)", IT: "Come comprare (SOL e token $NOMIQA)" },
  stake: { EN: "Stake", ES: "Staking", FR: "Staking", DE: "Staking", RU: "Стейкинг", ZH: "质押", JA: "ステーキング", PT: "Staking", AR: "الستيكينغ", IT: "Staking" },
  roadmap: { EN: "Roadmap", ES: "Hoja de ruta", FR: "Feuille de route", DE: "Roadmap", RU: "Дорожная карта", ZH: "路线图", JA: "ロードマップ", PT: "Roteiro", AR: "خارطة الطريق", IT: "Roadmap" },
  affiliate: { EN: "Affiliate", ES: "Afiliados", FR: "Affiliation", DE: "Partnerprogramm", RU: "Партнёрка", ZH: "联盟计划", JA: "アフィリエイト", PT: "Afiliados", AR: "برنامج الإحالة", IT: "Affiliato" },
  aboutUs: { EN: "About Us", ES: "Sobre nosotros", FR: "À propos", DE: "Über uns", RU: "О нас", ZH: "关于我们", JA: "私たちについて", PT: "Sobre nós", AR: "من نحن", IT: "Chi siamo" },
  howWeProtect: { EN: "How We Protect You", ES: "Cómo te protegemos", FR: "Comment nous vous protégeons", DE: "So schützen wir dich", RU: "Как мы защищаем вас", ZH: "我们如何保护你", JA: "私たちの保護方法", PT: "Como protegemos você", AR: "كيف نحميك", IT: "Come ti proteggiamo" },
  myEsims: { EN: "My eSIMs", ES: "Mis eSIM", FR: "Mes eSIM", DE: "Meine eSIMs", RU: "Мои eSIM", ZH: "我的 eSIM", JA: "マイ eSIM", PT: "Minhas eSIMs", AR: "شرائح eSIM الخاصة بي", IT: "Le mie eSIM" },
  myOrders: { EN: "My Orders", ES: "Mis pedidos", FR: "Mes commandes", DE: "Meine Bestellungen", RU: "Мои заказы", ZH: "我的订单", JA: "注文履歴", PT: "Meus pedidos", AR: "طلباتي", IT: "I miei ordini" },
  signIn: { EN: "Sign In", ES: "Iniciar sesión", FR: "Se connecter", DE: "Anmelden", RU: "Войти", ZH: "登录", JA: "ログイン", PT: "Entrar", AR: "تسجيل الدخول", IT: "Accedi" },
  signOut: { EN: "Sign Out", ES: "Cerrar sesión", FR: "Se déconnecter", DE: "Abmelden", RU: "Выйти", ZH: "退出登录", JA: "ログアウト", PT: "Sair", AR: "تسجيل الخروج", IT: "Esci" },
  signUp: { EN: "Sign Up", ES: "Crear cuenta", FR: "Créer un compte", DE: "Konto erstellen", RU: "Создать аккаунт", ZH: "创建账号", JA: "アカウント作成", PT: "Criar conta", AR: "إنشاء حساب", IT: "Registrati" },
  menu: { EN: "Menu", ES: "Menú", FR: "Menu", DE: "Menü", RU: "Меню", ZH: "菜单", JA: "メニュー", PT: "Menu", AR: "القائمة", IT: "Menu" },

  // Hero
  heroPrivate: { EN: "Private.", ES: "Privado.", FR: "Privé.", DE: "Privat.", RU: "Приватно.", ZH: "私密。", JA: "プライベート。", PT: "Privado.", AR: "خاص.", HI: "निजी।" },
  heroBorderless: { EN: "Borderless.", ES: "Sin fronteras.", FR: "Sans frontières.", DE: "Grenzenlos.", RU: "Без границ.", ZH: "无边界。", JA: "ボーダーレス.", PT: "Sem fronteiras.", AR: "بلا حدود.", HI: "बॉर्डरलेस।" },
  heroHuman: { EN: "Human.", ES: "Humano.", FR: "Humain.", DE: "Menschlich.", RU: "Человечно.", ZH: "人性。", JA: "ヒューマン。", PT: "Humano.", AR: "إنساني.", HI: "ह्यूमन।" },
  heroDescription1: { EN: "Connect anywhere in 60 seconds — no ID, no tracking, no limits.", ES: "Conéctate en cualquier lugar en 60 segundos — sin ID, sin rastreo, sin límites.", FR: "Connectez-vous partout en 60 secondes — sans ID, sans suivi, sans limites.", DE: "Verbinde dich überall in 60 Sekunden – keine ID, kein Tracking, keine Grenzen.", RU: "Подключайтесь где угодно за 60 секунд — без ID, без слежки, без ограничений.", ZH: "60 秒内随时随地连接——无需身份证、无跟踪、无限制。", JA: "どこでも60秒で接続 — ID不要、追跡なし、制限なし。", PT: "Conecte-se em qualquer lugar em 60 segundos — sem ID, sem rastreamento, sem limites.", AR: "اتصل من أي مكان خلال 60 ثانية — بدون هوية، بدون تتبع، بدون حدود.", HI: "60 सेकंड में कहीं भी कनेक्ट करें — बिना ID, बिना ट्रैकिंग, बिना सीमाओं के." },
  heroDescription2: { EN: "Join the world's first crypto-powered eSIM for freedom on your terms.", ES: "Únete a la primera eSIM impulsada por cripto para una libertad a tu manera.", FR: "Rejoignez la première eSIM alimentée par la crypto pour une liberté à votre façon.", DE: "Schließe dich der ersten krypto-basierten eSIM der Welt an – Freiheit zu deinen Bedingungen.", RU: "Присоединяйтесь к первой в мире eSIM на крипто — свобода на ваших условиях.", ZH: "加入全球首个加密驱动的 eSIM，以你的方式获得自由。", JA: "世界初の暗号通貨駆動のeSIMに参加し、あなたの条件で自由に。", PT: "Junte-se à primeira eSIM movida a cripto do mundo para liberdade nos seus termos.", AR: "انضم إلى أول eSIM مدعومة بالعملة المشفرة في العالم — حرية بشروطك.", HI: "दुनिया की पहली क्रिप्टो-पावर्ड eSIM से जुड़ें — स्वतंत्रता आपके तरीके से." },
  heroBuyNow: { EN: "Buy Now", ES: "Comprar ahora", FR: "Acheter", DE: "Jetzt kaufen", RU: "Купить", ZH: "立即购买", JA: "今すぐ購入", PT: "Comprar agora", AR: "اشتري الآن", HI: "अभी खरीदें" },
  heroWatchHow: { EN: "Watch How It Works", ES: "Cómo funciona", FR: "Voir comment ça marche", DE: "So funktioniert's", RU: "Как это работает", ZH: "观看操作", JA: "使い方を見る", PT: "Veja como funciona", AR: "شاهد كيف تعمل", HI: "कैसे काम करता है देखें" },

  // How It Works Section
  howItWorksTag: { EN: "Three steps", ES: "Tres pasos", FR: "Trois étapes", DE: "Drei Schritte", RU: "Три шага", ZH: "三个步骤", JA: "3つのステップ", PT: "Três passos", AR: "ثلاث خطوات", HI: "तीन कदम" },
  howItWorksTitle: { EN: "Connect. Travel. Repeat.", ES: "Conecta. Viaja. Repite.", FR: "Connectez. Voyagez. Répétez.", DE: "Verbinden. Reisen. Wiederholen.", RU: "Подключиться. Путешествовать. Повторить.", ZH: "连接。旅行。重复。", JA: "接続。旅行。繰り返し。", PT: "Conecte. Viaje. Repita.", AR: "اتصل. سافر. كرر.", HI: "कनेक्ट करें। यात्रा करें। दोहराएं।" },
  howItWorksSubtitle: { EN: "Your eSIM journey begins in seconds. No queues, no paperwork, no compromises.", ES: "Tu viaje eSIM comienza en segundos. Sin colas, sin papeleo, sin compromisos.", FR: "Votre parcours eSIM commence en quelques secondes. Pas de files d'attente, pas de paperasse, pas de compromis.", DE: "Deine eSIM-Reise beginnt in Sekunden. Keine Warteschlangen, kein Papierkram, keine Kompromisse.", RU: "Ваше путешествие с eSIM начинается за секунды. Никаких очередей, никакой бумажной волокиты, никаких компромиссов.", ZH: "您的 eSIM 之旅在几秒钟内开始。无需排队，无需文书工作，无需妥协。", JA: "あなたのeSIMの旅は数秒で始まります。待ち行列なし、書類なし、妥協なし。", PT: "Sua jornada eSIM começa em segundos. Sem filas, sem papelada, sem compromissos.", AR: "تبدأ رحلتك مع eSIM في ثوانٍ. بدون طوابير، بدون أوراق، بدون تنازلات.", HI: "आपकी eSIM यात्रा सेकंडों में शुरू होती है। कोई लाइन नहीं, कोई कागजी काम नहीं, कोई समझौता नहीं।" },
  howItWorksStep1: { EN: "Select plan", ES: "Selecciona plan", FR: "Sélectionner le plan", DE: "Plan auswählen", RU: "Выберите план", ZH: "选择计划", JA: "プランを選択", PT: "Selecionar plano", AR: "اختر الخطة", HI: "प्लान चुनें" },
  howItWorksStep2: { EN: "Scan QR code", ES: "Escanea código QR", FR: "Scanner le code QR", DE: "QR-Code scannen", RU: "Отсканируйте QR-код", ZH: "扫描二维码", JA: "QRコードをスキャン", PT: "Digitalizar código QR", AR: "امسح رمز QR", HI: "QR कोड स्कैन करें" },
  howItWorksStep3: { EN: "Connect instantly", ES: "Conecta al instante", FR: "Connectez instantanément", DE: "Sofort verbinden", RU: "Мгновенно подключиться", ZH: "立即连接", JA: "即座に接続", PT: "Conecte instantaneamente", AR: "اتصل فوراً", HI: "तुरंत कनेक्ट करें" },

  // Coverage Section (already present but keeping)
  coverageTitle: { EN: "Connected. Everywhere.", ES: "Conectados. En todas partes.", FR: "Connecté. Partout.", DE: "Verbunden. Überall.", RU: "На связи. Везде.", ZH: "连接。到处都是。", JA: "接続。どこでも。", PT: "Conectado. Em todos os lugares.", AR: "متصل. في كل مكان.", HI: "कनेक्टेड। हर जगह।" },
  coverageSubtitle1: { EN: "From cities to deserts, your signal follows you. 190+ countries, one private connection.", ES: "Desde ciudades hasta desiertos, tu señal te sigue. Más de 190 países, una conexión privada.", FR: "Des villes aux déserts, votre signal vous suit. 190+ pays, une connexion privée.", DE: "Von Städten bis Wüsten, dein Signal folgt dir. Über 190 Länder, eine private Verbindung.", RU: "От городов до пустынь, ваш сигнал следует за вами. Более 190 стран, одно частное подключение.", ZH: "从城市到沙漠，您的信号跟随您。190多个国家，一个私人连接。", JA: "都市から砂漠まで、あなたの信号はあなたを追いかけます。190か国以上、1つのプライベート接続。", PT: "De cidades a desertos, seu sinal o segue. Mais de 190 países, uma conexão privada.", AR: "من المدن إلى الصحاري، إشارتك تتبعك. أكثر من 190 دولة، اتصال خاص واحد.", HI: "शहरों से रेगिस्तानों तक, आपका सिग्नल आपका पीछा करता है। 190+ देश, एक निजी कनेक्शन।" },
  coverageSubtitle2: { EN: "One eSIM. The world is yours.", ES: "Una eSIM. El mundo es tuyo.", FR: "Une eSIM. Le monde vous appartient.", DE: "Eine eSIM. Die Welt gehört dir.", RU: "Одна eSIM. Мир твой.", ZH: "一张 eSIM。世界属于你。", JA: "1つのeSIM。世界はあなたのものです。", PT: "Um eSIM. O mundo é seu.", AR: "eSIM واحد. العالم ملكك.", HI: "एक eSIM। दुनिया आपकी है।" },
  coverageQuote: { EN: "Freedom means never losing signal — or yourself.", ES: "La libertad significa nunca perder la señal, ni a ti mismo.", FR: "La liberté signifie ne jamais perdre le signal — ou vous-même.", DE: "Freiheit bedeutet, niemals das Signal zu verlieren – oder sich selbst.", RU: "Свобода означает никогда не терять сигнал — или себя.", ZH: "自由意味着永不失去信号——或你自己。", JA: "自由とは、信号を失わないこと——そして自分自身を失わないことです。", PT: "Liberdade significa nunca perder o sinal — ou a si mesmo.", AR: "الحرية تعني عدم فقدان الإشارة أبدًا — أو نفسك.", HI: "स्वतंत्रता का मतलब कभी सिग्नल नहीं खोना है — या खुद को।" },
  coverageCountries: { EN: "Countries", ES: "Países", FR: "Pays", DE: "Länder", RU: "Страны", ZH: "国家", JA: "国", PT: "Países", AR: "دول", HI: "देश" },
  coverageUptime: { EN: "Uptime", ES: "Tiempo activo", FR: "Disponibilité", DE: "Betriebszeit", RU: "Безотказность", ZH: "正常运行时间", JA: "稼働時間", PT: "Tempo de atividade", AR: "وقت التشغيل", HI: "अपटाइम" },
  coverageSpeed: { EN: "Speed", ES: "Velocidad", FR: "Vitesse", DE: "Geschwindigkeit", RU: "Скорость", ZH: "速度", JA: "スピード", PT: "Velocidade", AR: "السرعة", HI: "गति" },

  // Why Nomiqa Section  
  whyNomiqaMainTitle: { EN: "Because your freedom shouldn't come with surveillance.", ES: "Porque tu libertad no debería venir con vigilancia.", FR: "Parce que votre liberté ne devrait pas s'accompagner de surveillance.", DE: "Weil deine Freiheit nicht mit Überwachung einhergehen sollte.", RU: "Потому что ваша свобода не должна сопровождаться слежкой.", ZH: "因为你的自由不应伴随监视。", JA: "あなたの自由には監視が伴うべきではないから。", PT: "Porque sua liberdade não deve vir com vigilância.", AR: "لأن حريتك لا يجب أن تأتي مع المراقبة.", HI: "क्योंकि आपकी स्वतंत्रता निगरानी के साथ नहीं आनी चाहिए।" },
  whyNomiqaMainSubtitle: { EN: "We built Nomiqa for travelers who demand more than convenience — they demand privacy, control, and respect.", ES: "Construimos Nomiqa para viajeros que exigen más que conveniencia: exigen privacidad, control y respeto.", FR: "Nous avons construit Nomiqa pour les voyageurs qui exigent plus que la commodité — ils exigent la vie privée, le contrôle et le respect.", DE: "Wir haben Nomiqa für Reisende gebaut, die mehr als nur Komfort fordern — sie fordern Privatsphäre, Kontrolle und Respekt.", RU: "Мы создали Nomiqa для путешественников, которые требуют больше, чем удобство — они требуют конфиденциальности, контроля и уважения.", ZH: "我们为旅行者构建了 Nomiqa，他们要求的不仅仅是便利——他们要求隐私、控制和尊重。", JA: "Nomiqaは、利便性以上のものを求める旅行者のために作られました——彼らはプライバシー、コントロール、尊重を求めています。", PT: "Construímos o Nomiqa para viajantes que exigem mais do que conveniência — eles exigem privacidade, controle e respeito.", AR: "قمنا ببناء Nomiqa للمسافرين الذين يطالبون بأكثر من الراحة — يطالبون بالخصوصية والتحكم والاحترام.", HI: "हमने Nomiqa उन यात्रियों के लिए बनाया है जो सुविधा से अधिक की मांग करते हैं — वे गोपनीयता, नियंत्रण और सम्मान की मांग करते हैं।" },
  whyNomiqaPrivacyTitle: { EN: "True Privacy. Zero Compromise.", ES: "Privacidad verdadera. Sin compromisos.", FR: "Vraie vie privée. Zéro compromis.", DE: "Echte Privatsphäre. Keine Kompromisse.", RU: "Настоящая конфиденциальность. Никаких компромиссов.", ZH: "真正的隐私。零妥协。", JA: "真のプライバシー。妥協なし。", PT: "Verdadeira privacidade. Zero compromissos.", AR: "خصوصية حقيقية. بدون تنازلات.", HI: "सच्ची गोपनीयता। कोई समझौता नहीं।" },
  whyNomiqaPrivacyDesc: { EN: "Your data is YOURS. No ID checks, no surveillance, no digital footprints.", ES: "Tus datos son TUYOS. Sin verificaciones de ID, sin vigilancia, sin huellas digitales.", FR: "Vos données sont À VOUS. Pas de vérifications d'identité, pas de surveillance, pas d'empreintes numériques.", DE: "Deine Daten gehören DIR. Keine ID-Prüfungen, keine Überwachung, keine digitalen Fußabdrücke.", RU: "Ваши данные — ВАШИ. Никаких проверок личности, никакого надзора, никаких цифровых следов.", ZH: "您的数据是您的。没有身份检查，没有监视，没有数字足迹。", JA: "あなたのデータはあなたのものです。ID チェックなし、監視なし、デジタルフットプリントなし。", PT: "Seus dados são SEUS. Sem verificações de ID, sem vigilância, sem pegadas digitais.", AR: "بياناتك ملكك. بدون فحوصات هوية، بدون مراقبة، بدون بصمات رقمية.", HI: "आपका डेटा आपका है। कोई ID जांच नहीं, कोई निगरानी नहीं, कोई डिजिटल फुटप्रिंट नहीं।" },
  whyNomiqaFreedomTitle: { EN: "Instant Access. Real Freedom.", ES: "Acceso instantáneo. Libertad real.", FR: "Accès instantané. Vraie liberté.", DE: "Sofortiger Zugang. Echte Freiheit.", RU: "Мгновенный доступ. Настоящая свобода.", ZH: "即时访问。真正的自由。", JA: "即座のアクセス。本当の自由。", PT: "Acesso instantâneo. Liberdade real.", AR: "وصول فوري. حرية حقيقية.", HI: "तत्काल पहुंच। वास्तविक स्वतंत्रता।" },
  whyNomiqaFreedomDesc: { EN: "Pay with crypto. Activate in seconds. No banks watching. No delays.", ES: "Paga con cripto. Activa en segundos. Sin bancos observando. Sin demoras.", FR: "Payez avec la crypto. Activez en quelques secondes. Pas de banques qui regardent. Pas de délais.", DE: "Bezahle mit Krypto. Aktiviere in Sekunden. Keine Banken, die zuschauen. Keine Verzögerungen.", RU: "Платите криптой. Активируйте за секунды. Никаких банков, наблюдающих за вами. Никаких задержек.", ZH: "用加密货币支付。几秒钟内激活。没有银行监视。没有延迟。", JA: "暗号通貨で支払います。数秒で有効化。銀行の監視なし。遅延なし。", PT: "Pague com cripto. Ative em segundos. Sem bancos observando. Sem atrasos.", AR: "ادفع بالعملة المشفرة. تنشيط في ثوانٍ. لا بنوك تراقب. لا تأخير.", HI: "क्रिप्टो से भुगतान करें। सेकंडों में सक्रिय करें। कोई बैंक देख नहीं रहा। कोई देरी नहीं।" },
  whyNomiqaBorderlessTitle: { EN: "Borderless Connection. Limitless Possibilities.", ES: "Conexión sin fronteras. Posibilidades ilimitadas.", FR: "Connexion sans frontières. Possibilités illimitées.", DE: "Grenzenlose Verbindung. Unbegrenzte Möglichkeiten.", RU: "Связь без границ. Безграничные возможности.", ZH: "无边界连接。无限可能。", JA: "ボーダーレス接続。無限の可能性。", PT: "Conexão sem fronteiras. Possibilidades ilimitadas.", AR: "اتصال بلا حدود. إمكانيات لا حدود لها.", HI: "सीमारहित कनेक्शन। असीमित संभावनाएं।" },
  whyNomiqaBorderlessDesc: { EN: "190+ countries. One eSIM. The world is yours to explore freely.", ES: "Más de 190 países. Una eSIM. El mundo es tuyo para explorar libremente.", FR: "190+ pays. Une eSIM. Le monde est à vous pour l'explorer librement.", DE: "Über 190 Länder. Eine eSIM. Die Welt steht dir frei zur Erkundung offen.", RU: "Более 190 стран. Одна eSIM. Мир открыт для вас.", ZH: "190多个国家。一张 eSIM。世界是你自由探索的。", JA: "190か国以上。1つのeSIM。世界は自由に探索できます。", PT: "Mais de 190 países. Um eSIM. O mundo é seu para explorar livremente.", AR: "أكثر من 190 دولة. eSIM واحد. العالم ملكك لاستكشافه بحرية.", HI: "190+ देश। एक eSIM। दुनिया स्वतंत्र रूप से तलाशने के लिए आपकी है।" },

  // Our Story / EasyCheckout Section
  ourStoryTag: { EN: "Our Story", ES: "Nuestra historia", FR: "Notre histoire", DE: "Unsere Geschichte", RU: "Наша история", ZH: "我们的故事", JA: "私たちのストーリー", PT: "Nossa história", AR: "قصتنا", HI: "हमारी कहानी" },
  ourStorySubtitle: { EN: "How we became the world's first privacy-first eSIM platform.", ES: "Cómo nos convertimos en la primera plataforma de eSIM centrada en la privacidad del mundo.", FR: "Comment nous sommes devenus la première plateforme eSIM axée sur la vie privée au monde.", DE: "Wie wir zur weltweit ersten datenschutzorientierten eSIM-Plattform wurden.", RU: "Как мы стали первой в мире платформой eSIM, ориентированной на конфиденциальность.", ZH: "我们如何成为世界上第一个以隐私为先的 eSIM 平台。", JA: "私たちが世界初のプライバシー重視のeSIMプラットフォームになった経緯。", PT: "Como nos tornamos a primeira plataforma eSIM focada em privacidade do mundo.", AR: "كيف أصبحنا أول منصة eSIM تركز على الخصوصية في العالم.", HI: "हम दुनिया का पहला गोपनीयता-प्रथम eSIM प्लेटफॉर्म कैसे बने।" },
  privacyFirstTitle: { EN: "Privacy First", ES: "Privacidad primero", FR: "Priorité à la vie privée", DE: "Privatsphäre zuerst", RU: "Конфиденциальность прежде всего", ZH: "隐私第一", JA: "プライバシー第一", PT: "Privacidade primeiro", AR: "الخصوصية أولاً", HI: "गोपनीयता पहले" },
  privacyFirstDesc: { EN: "No tracking. No surveillance. Just pure connectivity.", ES: "Sin rastreo. Sin vigilancia. Solo conectividad pura.", FR: "Pas de suivi. Pas de surveillance. Juste une connectivité pure.", DE: "Kein Tracking. Keine Überwachung. Nur pure Konnektivität.", RU: "Без слежки. Без надзора. Только чистая связь.", ZH: "无跟踪。无监视。只有纯粹的连接。", JA: "追跡なし。監視なし。純粋な接続性だけ。", PT: "Sem rastreamento. Sem vigilância. Apenas conectividade pura.", AR: "لا تتبع. لا مراقبة. مجرد اتصال نقي.", HI: "कोई ट्रैकिंग नहीं। कोई निगरानी नहीं। बस शुद्ध कनेक्टिविटी।" },
  cryptoNativeTitle: { EN: "Crypto Native", ES: "Nativo de cripto", FR: "Crypto natif", DE: "Krypto-nativ", RU: "Крипто-родной", ZH: "加密原生", JA: "クリプトネイティブ", PT: "Nativo de cripto", AR: "أصلي للعملات المشفرة", HI: "क्रिप्टो मूल" },
  cryptoNativeDesc: { EN: "Payments with SOL and $NOMIQA. Financial freedom included.", ES: "Pagos con SOL y $NOMIQA. Libertad financiera incluida.", FR: "Paiements avec SOL et $NOMIQA. Liberté financière incluse.", DE: "Zahlungen mit SOL und $NOMIQA. Finanzielle Freiheit inklusive.", RU: "Платежи с SOL и $NOMIQA. Финансовая свобода включена.", ZH: "使用 SOL 和 $NOMIQA 支付。包括财务自由。", JA: "SOLと$NOMIQAでの支払い。財務的自由が含まれています。", PT: "Pagamentos com SOL e $NOMIQA. Liberdade financeira incluída.", AR: "مدفوعات بـ SOL و $NOMIQA. الحرية المالية متضمنة.", HI: "SOL और $NOMIQA के साथ भुगतान। वित्तीय स्वतंत्रता शामिल।" },
  communityOwnedTitle: { EN: "Community Owned", ES: "Propiedad comunitaria", FR: "Propriété de la communauté", DE: "Im Besitz der Gemeinschaft", RU: "Принадлежит сообществу", ZH: "社区拥有", JA: "コミュニティ所有", PT: "Propriedade da comunidade", AR: "مملوك من قبل المجتمع", HI: "समुदाय के स्वामित्व में" },
  communityOwnedDesc: { EN: "Built by travelers, for travelers. Powered by Web3.", ES: "Construido por viajeros, para viajeros. Impulsado por Web3.", FR: "Construit par des voyageurs, pour des voyageurs. Alimenté par Web3.", DE: "Von Reisenden für Reisende gebaut. Angetrieben von Web3.", RU: "Создано путешественниками для путешественников. На базе Web3.", ZH: "由旅行者为旅行者打造。由 Web3 提供支持。", JA: "旅行者によって、旅行者のために構築されました。Web3で駆動されます。", PT: "Construído por viajantes, para viajantes. Alimentado por Web3.", AR: "مبني من قبل المسافرين، للمسافرين. مدعوم بـ Web3.", HI: "यात्रियों द्वारा, यात्रियों के लिए बनाया गया। Web3 द्वारा संचालित।" },
  learnMoreAbout: { EN: "Learn More About Us", ES: "Más sobre nosotros", FR: "En savoir plus sur nous", DE: "Mehr über uns erfahren", RU: "Узнать больше о нас", ZH: "了解更多关于我们", JA: "私たちについてもっと知る", PT: "Saiba mais sobre nós", AR: "تعرف على المزيد عنا", HI: "हमारे बारे में और जानें" },

  // Earn Section
  earnMainTitle: { EN: "Travel the world. Earn as you move.", ES: "Viaja por el mundo. Gana mientras te mueves.", FR: "Voyagez dans le monde. Gagnez en vous déplaçant.", DE: "Reise um die Welt. Verdiene beim Bewegen.", RU: "Путешествуйте по миру. Зарабатывайте во время движения.", ZH: "环游世界。边移动边赚钱。", JA: "世界を旅しましょう。移動しながら稼ぎます。", PT: "Viaje pelo mundo. Ganhe enquanto se move.", AR: "سافر حول العالم. اكسب أثناء التنقل.", HI: "दुनिया की यात्रा करें। चलते हुए कमाएं।" },
  earnMainSubtitle: { EN: "Stake $NOMIQA and earn data + rewards while connecting others.", ES: "Apuesta $NOMIQA y gana datos + recompensas mientras conectas a otros.", FR: "Stakez $NOMIQA et gagnez des données + des récompenses en connectant les autres.", DE: "Stake $NOMIQA und verdiene Daten + Belohnungen, während du andere verbindest.", RU: "Ставьте $NOMIQA и зарабатывайте данные + награды, подключая других.", ZH: "质押 $NOMIQA，在连接他人的同时赚取数据+奖励。", JA: "$NOMIQAをステークして、他の人を接続しながらデータ+報酬を獲得します。", PT: "Faça stake de $NOMIQA e ganhe dados + recompensas conectando outros.", AR: "قم بالستيكينغ $NOMIQA واكسب البيانات + المكافآت أثناء توصيل الآخرين.", HI: "$NOMIQA को स्टेक करें और दूसरों को कनेक्ट करते हुए डेटा + रिवार्ड्स कमाएं।" },
  earnMainDescription: { EN: "Build your network of travelers, creators, and Web3 pioneers.", ES: "Construye tu red de viajeros, creadores y pioneros de Web3.", FR: "Construisez votre réseau de voyageurs, de créateurs et de pionniers du Web3.", DE: "Baue dein Netzwerk von Reisenden, Schöpfern und Web3-Pionieren auf.", RU: "Создайте свою сеть путешественников, создателей и пионеров Web3.", ZH: "建立您的旅行者、创作者和 Web3 先驱网络。", JA: "旅行者、クリエイター、Web3パイオニアのネットワークを構築します。", PT: "Construa sua rede de viajantes, criadores e pioneiros do Web3.", AR: "قم ببناء شبكتك من المسافرين والمبدعين ورواد Web3.", HI: "यात्रियों, रचनाकारों और Web3 अग्रदूतों का अपना नेटवर्क बनाएं।" },
  earnStartStaking: { EN: "Start Staking", ES: "Empezar staking", FR: "Commencer le staking", DE: "Staking starten", RU: "Начать стейкинг", ZH: "开始质押", JA: "ステーキングを開始", PT: "Iniciar staking", AR: "بدء الستيكينغ", HI: "स्टेकिंग शुरू करें" },
  earnJoinAffiliate: { EN: "Join the Affiliate Network", ES: "Únete a la red de afiliados", FR: "Rejoignez le réseau d'affiliation", DE: "Trete dem Partnernetzwerk bei", RU: "Присоединяйтесь к партнёрской сети", ZH: "加入联盟网络", JA: "アフィリエイトネットワークに参加", PT: "Junte-se à rede de afiliados", AR: "انضم إلى شبكة الإحالة", HI: "सहयोगी नेटवर्क में शामिल हों" },

  // Trust / Partners Section
  trustInfrastructureTag: { EN: "Trusted Infrastructure", ES: "Infraestructura confiable", FR: "Infrastructure de confiance", DE: "Vertrauenswürdige Infrastruktur", RU: "Надёжная инфраструктура", ZH: "可信赖的基础设施", JA: "信頼されたインフラストラクチャ", PT: "Infraestrutura confiável", AR: "بنية تحتية موثوقة", HI: "विश्वसनीय बुनियादी ढांचा" },
  trustMainTitle: { EN: "Built on the Best", ES: "Construido sobre lo mejor", FR: "Construit sur le meilleur", DE: "Auf dem Besten aufgebaut", RU: "Создано на лучших", ZH: "建立在最好的基础上", JA: "最高のものの上に構築", PT: "Construído sobre o melhor", AR: "مبني على الأفضل", HI: "सर्वश्रेष्ठ पर निर्मित" },
  trustSubtitle: { EN: "Powered by industry-leading blockchain and payment infrastructure you already know and trust.", ES: "Impulsado por blockchain y infraestructura de pagos líderes en la industria en los que ya confías.", FR: "Alimenté par une infrastructure blockchain et de paiement de pointe en laquelle vous avez déjà confiance.", DE: "Angetrieben von branchenführender Blockchain- und Zahlungsinfrastruktur, der du bereits vertraust.", RU: "На базе ведущей в отрасли блокчейн- и платёжной инфраструктуры, которой вы уже доверяете.", ZH: "由行业领先的区块链和支付基础设施提供支持，您已经熟悉并信任。", JA: "業界をリードするブロックチェーンと決済インフラストラクチャで動作しており、すでに知っていて信頼しています。", PT: "Alimentado por infraestrutura blockchain e de pagamento líder do setor em que você já confia.", AR: "مدعوم ببنية تحتية رائدة في الصناعة للبلوكتشين والمدفوعات التي تعرفها وتثق بها بالفعل.", HI: "उद्योग-अग्रणी ब्लॉकचेन और भुगतान बुनियादी ढांचे द्वारा संचालित जिस पर आप पहले से जानते और भरोसा करते हैं।" },
  trustLightningFast: { EN: "Lightning Fast", ES: "Ultrarrápido", FR: "Éclair rapide", DE: "Blitzschnell", RU: "Молниеносно", ZH: "闪电般快", JA: "電光石火", PT: "Ultrarrápido", AR: "سريع كالبرق", HI: "बिजली की तरह तेज" },
  trustTrustedWallet: { EN: "Trusted Wallet", ES: "Billetera de confianza", FR: "Portefeuille de confiance", DE: "Vertrauenswürdige Wallet", RU: "Надёжный кошелёк", ZH: "值得信赖的钱包", JA: "信頼されたウォレット", PT: "Carteira confiável", AR: "محفظة موثوقة", HI: "विश्वसनीय वॉलेट" },
  trustDefiProtocol: { EN: "DeFi Protocol", ES: "Protocolo DeFi", FR: "Protocole DeFi", DE: "DeFi-Protokoll", RU: "Протокол DeFi", ZH: "DeFi 协议", JA: "DeFiプロトコル", PT: "Protocolo DeFi", AR: "بروتوكول DeFi", HI: "DeFi प्रोटोकॉल" },
  trustSecurePayments: { EN: "Secure Payments", ES: "Pagos seguros", FR: "Paiements sécurisés", DE: "Sichere Zahlungen", RU: "Безопасные платежи", ZH: "安全支付", JA: "安全な支払い", PT: "Pagamentos seguros", AR: "مدفوعات آمنة", HI: "सुरक्षित भुगतान" },

  // Footer
  footerTagline: { EN: "Nomiqa — where privacy meets connection.", ES: "Nomiqa — donde la privacidad se encuentra con la conexión.", FR: "Nomiqa — où la vie privée rencontre la connexion.", DE: "Nomiqa — wo Privatsphäre auf Verbindung trifft.", RU: "Nomiqa — где конфиденциальность встречается со связью.", ZH: "Nomiqa — 隐私与连接相遇的地方。", JA: "Nomiqa — プライバシーと接続が出会う場所。", PT: "Nomiqa — onde a privacidade encontra a conexão.", AR: "Nomiqa — حيث تلتقي الخصوصية بالاتصال.", HI: "Nomiqa — जहां गोपनीयता कनेक्शन से मिलती है।" },
  footerPoweredBy: { EN: "Powered by Nomiqa.", ES: "Impulsado por Nomiqa.", FR: "Propulsé par Nomiqa.", DE: "Angetrieben von Nomiqa.", RU: "Работает на Nomiqa.", ZH: "由 Nomiqa 提供支持。", JA: "Nomiqaで駆動されます。", PT: "Desenvolvido por Nomiqa.", AR: "مدعوم من Nomiqa.", HI: "Nomiqa द्वारा संचालित।" },
  footerCopyright: { EN: "Powered by the people. Built for the borderless.", ES: "Impulsado por la gente. Construido para los sin fronteras.", FR: "Alimenté par les gens. Construit pour les sans frontières.", DE: "Von den Menschen angetrieben. Für die Grenzenlosen gebaut.", RU: "На базе людей. Создано для безграничных.", ZH: "由人民提供支持。为无边界而建。", JA: "人々によって動かされ、ボーダーレスのために構築されました。", PT: "Alimentado pelas pessoas. Construído para os sem fronteiras.", AR: "مدعوم من قبل الناس. مبني لمن لا حدود لهم.", HI: "लोगों द्वारा संचालित। सीमाहीन के लिए बनाया गया।" },
  products: { EN: "Products", ES: "Productos", FR: "Produits", DE: "Produkte", RU: "Продукты", ZH: "产品", JA: "製品", PT: "Produtos", AR: "المنتجات", HI: "उत्पाद" },
  company: { EN: "Company", ES: "Empresa", FR: "Entreprise", DE: "Unternehmen", RU: "Компания", ZH: "公司", JA: "会社", PT: "Empresa", AR: "الشركة", HI: "कंपनी" },
  support: { EN: "Support", ES: "Soporte", FR: "Support", DE: "Support", RU: "Поддержка", ZH: "支持", JA: "サポート", PT: "Suporte", AR: "الدعم", HI: "समर्थन" },
  coverage: { EN: "Coverage", ES: "Cobertura", FR: "Couverture", DE: "Abdeckung", RU: "Покрытие", ZH: "覆盖", JA: "カバレッジ", PT: "Cobertura", AR: "التغطية", HI: "कवरेज" },
  staking: { EN: "Staking", ES: "Staking", FR: "Staking", DE: "Staking", RU: "Стейкинг", ZH: "质押", JA: "ステーキング", PT: "Staking", AR: "الستيكينغ", HI: "स्टेकिंग" },
  nmqToken: { EN: "NMQ Token", ES: "Token NMQ", FR: "Jeton NMQ", DE: "NMQ-Token", RU: "Токен NMQ", ZH: "NMQ 代币", JA: "NMQトークン", PT: "Token NMQ", AR: "رمز NMQ", HI: "NMQ टोकन" },
  privacyPolicy: { EN: "Privacy Policy", ES: "Política de privacidad", FR: "Politique de confidentialité", DE: "Datenschutzerklärung", RU: "Политика конфиденциальности", ZH: "隐私政策", JA: "プライバシーポリシー", PT: "Política de privacidade", AR: "سياسة الخصوصية", HI: "गोपनीयता नीति" },
  termsOfService: { EN: "Terms of Service", ES: "Términos de servicio", FR: "Conditions d'utilisation", DE: "Nutzungsbedingungen", RU: "Условия использования", ZH: "服务条款", JA: "利用規約", PT: "Termos de serviço", AR: "شروط الخدمة", HI: "सेवा की शर्तें" },

  // Sticky CTA
  getEsimNow: { EN: "Get Your eSIM Now", ES: "Obtén tu eSIM ahora", FR: "Obtenez votre eSIM maintenant", DE: "Hol dir jetzt deine eSIM", RU: "Получите свою eSIM сейчас", ZH: "立即获取您的 eSIM", JA: "今すぐeSIMを入手", PT: "Obtenha seu eSIM agora", AR: "احصل على eSIM الآن", HI: "अभी अपना eSIM प्राप्त करें" },
  buyNow: { EN: "Buy Now", ES: "Comprar ahora", FR: "Acheter", DE: "Jetzt kaufen", RU: "Купить", ZH: "立即购买", JA: "今すぐ購入", PT: "Comprar agora", AR: "اشتري الآن", HI: "अभी खरीदें" },

  // Earn Reward Block
  earnAsConnect: { EN: "Earn as You Connect.", ES: "Gana mientras te conectas.", FR: "Gagnez en vous connectant.", DE: "Verdiene beim Verbinden.", RU: "Зарабатывайте при подключении.", ZH: "连接时赚取。", JA: "接続しながら稼ぐ。", PT: "Ganhe enquanto se conecta.", AR: "اكسب أثناء الاتصال.", HI: "कनेक्ट करते हुए कमाएं।" },
  earnRewardDesc: { EN: "Get rewarded with NOMIQA Tokens every time you activate or share your eSIM — powering the world's first crypto-enabled travel network.", ES: "Recibe recompensas con tokens NOMIQA cada vez que actives o compartas tu eSIM — impulsando la primera red de viajes habilitada para cripto del mundo.", FR: "Soyez récompensé avec des jetons NOMIQA chaque fois que vous activez ou partagez votre eSIM — alimentant le premier réseau de voyage cryptographique au monde.", DE: "Erhalte NOMIQA-Token jedes Mal, wenn du deine eSIM aktivierst oder teilst — und treibe das weltweit erste krypto-fähige Reise-Netzwerk an.", RU: "Получайте вознаграждения токенами NOMIQA каждый раз, когда вы активируете или делитесь своей eSIM — питая первую в мире криптографическую туристическую сеть.", ZH: "每次激活或分享您的 eSIM 时都会获得 NOMIQA 代币奖励——为世界上第一个支持加密货币的旅行网络提供动力。", JA: "eSIMをアクティブ化または共有するたびにNOMIQAトークンで報酬を受け取ります— 世界初の暗号化対応旅行ネットワークを動かします。", PT: "Receba recompensas com tokens NOMIQA toda vez que você ativar ou compartilhar seu eSIM — alimentando a primeira rede de viagens habilitada para cripto do mundo.", AR: "احصل على مكافآت برموز NOMIQA في كل مرة تقوم فيها بتنشيط أو مشاركة eSIM الخاص بك — مما يدعم أول شبكة سفر ممكّنة بالعملات المشفرة في العالم.", HI: "हर बार जब आप अपना eSIM सक्रिय करते या साझा करते हैं तो NOMIQA टोकन्स के साथ पुरस्कृत हों — दुनिया के पहले क्रिप्टो-सक्षम ट्रैवल नेटवर्क को शक्ति प्रदान करते हुए।" },
  redeemTokens: { EN: "Redeem tokens for extra data", ES: "Canjea tokens por datos adicionales", FR: "Échanger des jetons contre des données supplémentaires", DE: "Tokens gegen zusätzliche Daten eintauschen", RU: "Обменяйте токены на дополнительные данные", ZH: "兑换代币以获取额外数据", JA: "トークンを交換して追加データを取得", PT: "Troque tokens por dados extras", AR: "استبدال الرموز للحصول على بيانات إضافية", HI: "अतिरिक्त डेटा के लिए टोकन्स को रिडीम करें" },
  earnForReferrals: { EN: "Earn rewards for referrals", ES: "Gana recompensas por referencias", FR: "Gagnez des récompenses pour les références", DE: "Verdiene Belohnungen für Empfehlungen", RU: "Зарабатывайте награды за рекомендации", ZH: "为推荐赚取奖励", JA: "紹介で報酬を獲得", PT: "Ganhe recompensas por indicações", AR: "اكسب مكافآت للإحالات", HI: "रेफरल के लिए रिवार्ड्स कमाएं" },
  growPrivateNetwork: { EN: "Grow your private travel network", ES: "Haz crecer tu red de viajes privada", FR: "Développez votre réseau de voyage privé", DE: "Baue dein privates Reise-Netzwerk aus", RU: "Расширяйте свою частную туристическую сеть", ZH: "扩展您的私人旅行网络", JA: "プライベートトラベルネットワークを拡大", PT: "Expanda sua rede de viagens privada", AR: "قم بتوسيع شبكة السفر الخاصة بك", HI: "अपने निजी ट्रैवल नेटवर्क को बढ़ाएं" },
  discoverToken: { EN: "Discover $NOMIQA Token", ES: "Descubre el token $NOMIQA", FR: "Découvrez le jeton $NOMIQA", DE: "Entdecke den $NOMIQA-Token", RU: "Откройте для себя токен $NOMIQA", ZH: "发现 $NOMIQA 代币", JA: "$NOMIQAトークンを発見", PT: "Descubra o token $NOMIQA", AR: "اكتشف رمز $NOMIQA", HI: "$NOMIQA टोकन की खोज करें" },

  // Shop Page
  shopTitle: { EN: "Choose Your Plan", ES: "Elige tu plan", FR: "Choisissez votre plan", DE: "Wähle deinen Plan", RU: "Выберите свой план", ZH: "选择您的计划", JA: "プランを選択", PT: "Escolha seu plano", AR: "اختر خطتك", HI: "अपनी योजना चुनें" },
  searchPlaceholder: { EN: "Search by country or region...", ES: "Buscar por país o región...", FR: "Rechercher par pays ou région...", DE: "Nach Land oder Region suchen...", RU: "Поиск по стране или региону...", ZH: "按国家或地区搜索...", JA: "国または地域で検索...", PT: "Pesquisar por país ou região...", AR: "البحث عن البلد أو المنطقة...", HI: "देश या क्षेत्र से खोजें..." },
  allPlans: { EN: "All Plans", ES: "Todos los planes", FR: "Tous les plans", DE: "Alle Pläne", RU: "Все планы", ZH: "所有计划", JA: "すべてのプラン", PT: "Todos os planos", AR: "جميع الخطط", HI: "सभी योजनाएं" },
  localPlans: { EN: "Local (Single Country)", ES: "Local (Un país)", FR: "Local (Un seul pays)", DE: "Lokal (Einzelnes Land)", RU: "Местные (Одна страна)", ZH: "本地（单一国家）", JA: "ローカル（単一国）", PT: "Local (País único)", AR: "محلي (بلد واحد)", HI: "स्थानीय (एकल देश)" },
  regionalPlans: { EN: "Regional (Multiple Countries)", ES: "Regional (Múltiples países)", FR: "Régional (Plusieurs pays)", DE: "Regional (Mehrere Länder)", RU: "Региональные (Несколько стран)", ZH: "区域性（多个国家）", JA: "地域（複数の国）", PT: "Regional (Vários países)", AR: "إقليمي (دول متعددة)", HI: "क्षेत्रीय (कई देश)" },
  popular: { EN: "Popular", ES: "Popular", FR: "Populaire", DE: "Beliebt", RU: "Популярно", ZH: "热门", JA: "人気", PT: "Popular", AR: "شائع", HI: "लोकप्रिय" },
  addedToCart: { EN: "added to cart!", ES: "¡añadido al carrito!", FR: "ajouté au panier!", DE: "zum Warenkorb hinzugefügt!", RU: "добавлено в корзину!", ZH: "已添加到购物车！", JA: "カートに追加されました！", PT: "adicionado ao carrinho!", AR: "تمت الإضافة إلى السلة!", HI: "कार्ट में जोड़ा गया!" },
  addToCart: { EN: "Add to Cart", ES: "Añadir al carrito", FR: "Ajouter au panier", DE: "In den Warenkorb", RU: "Добавить в корзину", ZH: "添加到购物车", JA: "カートに追加", PT: "Adicionar ao carrinho", AR: "إضافة إلى السلة", HI: "कार्ट में जोड़ें" },
  share: { EN: "Share", ES: "Compartir", FR: "Partager", DE: "Teilen", RU: "Поделиться", ZH: "分享", JA: "共有", PT: "Compartilhar", AR: "مشاركة", HI: "साझा करें" },
  loadMore: { EN: "Load More Plans", ES: "Cargar más planes", FR: "Charger plus de plans", DE: "Mehr Pläne laden", RU: "Загрузить больше планов", ZH: "加载更多计划", JA: "さらにプランを読み込む", PT: "Carregar mais planos", AR: "تحميل المزيد من الخطط", HI: "और योजनाएं लोड करें" },
  loading: { EN: "Loading...", ES: "Cargando...", FR: "Chargement...", DE: "Laden...", RU: "Загрузка...", ZH: "加载中...", JA: "読み込み中...", PT: "Carregando...", AR: "جار التحميل...", HI: "लोड हो रहा है..." },
  noPlansFound: { EN: "No plans found matching your search.", ES: "No se encontraron planes que coincidan con tu búsqueda.", FR: "Aucun plan trouvé correspondant à votre recherche.", DE: "Keine Pläne gefunden, die deiner Suche entsprechen.", RU: "Не найдено планов, соответствующих вашему поиску.", ZH: "未找到匹配您搜索的计划。", JA: "検索に一致するプランが見つかりませんでした。", PT: "Nenhum plano encontrado correspondente à sua pesquisa.", AR: "لم يتم العثور على خطط تطابق بحثك.", HI: "आपकी खोज से मेल खाती कोई योजना नहीं मिली।" },

  // FAQ headings
  faqTitle: { EN: "Questions? We've got you.", ES: "¿Preguntas? Te ayudamos.", FR: "Des questions ? On est là.", DE: "Fragen? Wir sind da.", RU: "Вопросы? Мы поможем.", ZH: "有问题？我们来帮你。", JA: "質問はありますか？お任せください。", PT: "Dúvidas? Estamos com você.", AR: "أسئلة؟ نحن هنا لأجلك.", HI: "सवाल? हम आपके साथ हैं।" },
  faqSubtitle: { EN: "eSIM setup, troubleshooting, and payments.", ES: "Configuración de eSIM, solución de problemas y pagos.", FR: "Configuration eSIM, dépannage et paiements.", DE: "eSIM-Einrichtung, Fehlerbehebung und Zahlungen.", RU: "Настройка eSIM, устранение неполадок и платежи.", ZH: "eSIM 设置、故障排除和支付。", JA: "eSIM の設定、トラブルシューティング、支払い。", PT: "Configuração de eSIM, solução de problemas e pagamentos.", AR: "إعداد eSIM، استكشاف الأخطاء وإصلاحها، والمدفوعات.", HI: "eSIM सेटअप, ट्रबलशूटिंग और पेमेंट।" },

  // FAQ Q&A keys
  faq1Q: { EN: "How do I install my eSIM?", ES: "¿Cómo instalo mi eSIM?", FR: "Comment installer mon eSIM ?", DE: "Wie installiere ich meine eSIM?", RU: "Как установить мою eSIM?", ZH: "如何安装我的 eSIM？", JA: "eSIM のインストール方法は？", PT: "Como instalo meu eSIM?", AR: "كيف أقوم بتثبيت eSIM؟", IT: "Come installo la mia eSIM?" },
  faq1A: { EN: "After purchase, you'll receive a QR code and instructions. Scan it in your phone's eSIM settings and follow the prompts.", ES: "Después de la compra, recibirás un código QR e instrucciones. Escanéalo en la configuración de eSIM de tu teléfono y sigue las indicaciones.", FR: "Après l'achat, vous recevrez un code QR et des instructions. Scannez-le dans les paramètres eSIM de votre téléphone et suivez les instructions.", DE: "Nach dem Kauf erhältst du einen QR-Code und Anweisungen. Scanne ihn in den eSIM-Einstellungen deines Telefons und folge den Anweisungen.", RU: "После покупки вы получите QR-код и инструкции. Отсканируйте его в настройках eSIM вашего телефона и следуйте инструкциям.", ZH: "购买后，您将收到二维码和说明。在手机的 eSIM 设置中扫描它，然后按照提示操作。", JA: "購入後、QR コードと手順が届きます。携帯電話の eSIM 設定でスキャンし、プロンプトに従ってください。", PT: "Após a compra, você receberá um código QR e instruções. Escaneie-o nas configurações de eSIM do seu telefone e siga as instruções.", AR: "بعد الشراء، ستتلقى رمز QR وتعليمات. امسحه في إعدادات eSIM على هاتفك واتبع التعليمات.", IT: "Dopo l'acquisto, riceverai un codice QR e le istruzioni. Scansionalo nelle impostazioni eSIM del tuo telefono e segui le istruzioni." },
  faq2Q: { EN: "Does eSIM work on my phone?", ES: "¿Funciona eSIM en mi teléfono?", FR: "L'eSIM fonctionne-t-elle sur mon téléphone ?", DE: "Funktioniert eSIM auf meinem Telefon?", RU: "Работает ли eSIM на моем телефоне?", ZH: "eSIM 可以在我的手机上使用吗？", JA: "eSIM は私の携帯電話で動作しますか？", PT: "O eSIM funciona no meu telefone?", AR: "هل يعمل eSIM على هاتفي؟", IT: "L'eSIM funziona sul mio telefono?" },
  faq2A: { EN: "Most recent iPhone and Android models support eSIM. Check your device settings: Mobile/Cellular > Add eSIM.", ES: "La mayoría de los modelos recientes de iPhone y Android admiten eSIM. Verifica la configuración de tu dispositivo: Móvil/Celular > Agregar eSIM.", FR: "La plupart des modèles récents d'iPhone et Android prennent en charge l'eSIM. Vérifiez les paramètres de votre appareil : Mobile/Cellulaire > Ajouter eSIM.", DE: "Die meisten neueren iPhone- und Android-Modelle unterstützen eSIM. Überprüfe deine Geräteeinstellungen: Mobil/Mobilfunk > eSIM hinzufügen.", RU: "Большинство последних моделей iPhone и Android поддерживают eSIM. Проверьте настройки устройства: Мобильная сеть/Сотовая связь > Добавить eSIM.", ZH: "大多数最新的 iPhone 和 Android 型号支持 eSIM。检查您的设备设置：移动/蜂窝 > 添加 eSIM。", JA: "最新の iPhone と Android モデルの大部分は eSIM をサポートしています。デバイス設定を確認してください：モバイル/セルラー > eSIM を追加。", PT: "A maioria dos modelos recentes de iPhone e Android suporta eSIM. Verifique as configurações do seu dispositivo: Móvel/Celular > Adicionar eSIM.", AR: "تدعم معظم طرازات iPhone و Android الحديثة eSIM. تحقق من إعدادات جهازك: الجوال/الخلوي > إضافة eSIM.", IT: "La maggior parte dei modelli recenti di iPhone e Android supporta eSIM. Controlla le impostazioni del tuo dispositivo: Cellulare/Mobile > Aggiungi eSIM." },
  faq3Q: { EN: "How fast is activation?", ES: "¿Qué tan rápida es la activación?", FR: "Quelle est la rapidité d'activation ?", DE: "Wie schnell ist die Aktivierung?", RU: "Как быстро происходит активация?", ZH: "激活有多快？", JA: "アクティベーションはどのくらい速いですか？", PT: "Quão rápida é a ativação?", AR: "ما مدى سرعة التفعيل؟", IT: "Quanto è veloce l'attivazione?" },
  faq3A: { EN: "Usually under 60 seconds after scanning the QR code and enabling data for the new eSIM profile.", ES: "Por lo general, menos de 60 segundos después de escanear el código QR y habilitar datos para el nuevo perfil eSIM.", FR: "Généralement moins de 60 secondes après avoir scanné le code QR et activé les données pour le nouveau profil eSIM.", DE: "Normalerweise unter 60 Sekunden nach dem Scannen des QR-Codes und dem Aktivieren von Daten für das neue eSIM-Profil.", RU: "Обычно менее 60 секунд после сканирования QR-кода и включения данных для нового профиля eSIM.", ZH: "通常在扫描二维码并为新 eSIM 配置文件启用数据后不到 60 秒。", JA: "通常、QR コードをスキャンして新しい eSIM プロファイルのデータを有効にした後、60 秒未満です。", PT: "Geralmente menos de 60 segundos após escanear o código QR e ativar os dados para o novo perfil eSIM.", AR: "عادةً أقل من 60 ثانية بعد مسح رمز QR وتمكين البيانات للملف الشخصي eSIM الجديد.", IT: "Di solito meno di 60 secondi dopo aver scansionato il codice QR e abilitato i dati per il nuovo profilo eSIM." },
  faq4Q: { EN: "What if data isn't working?", ES: "¿Qué pasa si los datos no funcionan?", FR: "Que faire si les données ne fonctionnent pas ?", DE: "Was ist, wenn Daten nicht funktionieren?", RU: "Что делать, если данные не работают?", ZH: "如果数据不起作用怎么办？", JA: "データが機能しない場合はどうすればよいですか？", PT: "E se os dados não estiverem funcionando?", AR: "ماذا لو لم تعمل البيانات؟", IT: "Cosa succede se i dati non funzionano?" },
  faq4A: { EN: "Toggle Airplane Mode, ensure the eSIM is set as the active data line, and enable Data Roaming for that profile.", ES: "Activa y desactiva el modo avión, asegúrate de que la eSIM esté configurada como la línea de datos activa y habilita el roaming de datos para ese perfil.", FR: "Activez et désactivez le mode Avion, assurez-vous que l'eSIM est définie comme la ligne de données active et activez l'itinérance des données pour ce profil.", DE: "Schalte den Flugmodus ein und aus, stelle sicher, dass die eSIM als aktive Datenleitung festgelegt ist, und aktiviere Daten-Roaming für dieses Profil.", RU: "Переключите режим полета, убедитесь, что eSIM установлена как активная линия данных, и включите роуминг данных для этого профиля.", ZH: "切换飞行模式，确保 eSIM 设置为活动数据线路，并为该配置文件启用数据漫游。", JA: "機内モードを切り替え、eSIM がアクティブなデータラインとして設定されていることを確認し、そのプロファイルのデータローミングを有効にします。", PT: "Alterne o modo avião, certifique-se de que o eSIM está definido como a linha de dados ativa e ative o roaming de dados para esse perfil.", AR: "قم بتبديل وضع الطيران، وتأكد من تعيين eSIM كخط البيانات النشط، وتمكين التجوال للبيانات لهذا الملف الشخصي.", IT: "Attiva e disattiva la modalità aereo, assicurati che l'eSIM sia impostata come linea dati attiva e abilita il roaming dati per quel profilo." },
  faq5Q: { EN: "Can I keep my physical SIM for calls?", ES: "¿Puedo mantener mi SIM física para llamadas?", FR: "Puis-je garder ma carte SIM physique pour les appels ?", DE: "Kann ich meine physische SIM für Anrufe behalten?", RU: "Могу ли я оставить физическую SIM-карту для звонков?", ZH: "我可以保留物理 SIM 卡用于通话吗？", JA: "通話用に物理 SIM を保持できますか？", PT: "Posso manter meu SIM físico para chamadas?", AR: "هل يمكنني الاحتفاظ ببطاقة SIM الفعلية للمكالمات؟", IT: "Posso mantenere la mia SIM fisica per le chiamate?" },
  faq5A: { EN: "Yes. Keep your primary SIM for calls/SMS and set the eSIM for data only. You can switch anytime in settings.", ES: "Sí. Mantén tu SIM principal para llamadas/SMS y configura la eSIM solo para datos. Puedes cambiar en cualquier momento en la configuración.", FR: "Oui. Gardez votre carte SIM principale pour les appels/SMS et configurez l'eSIM pour les données uniquement. Vous pouvez changer à tout moment dans les paramètres.", DE: "Ja. Behalte deine primäre SIM für Anrufe/SMS und stelle die eSIM nur für Daten ein. Du kannst jederzeit in den Einstellungen wechseln.", RU: "Да. Оставьте основную SIM-карту для звонков/SMS и настройте eSIM только для данных. Вы можете переключаться в любое время в настройках.", ZH: "是的。保留您的主 SIM 卡用于通话/短信，并将 eSIM 设置为仅用于数据。您可以随时在设置中切换。", JA: "はい。通話/SMS 用にプライマリ SIM を保持し、eSIM をデータのみに設定します。設定でいつでも切り替えることができます。", PT: "Sim. Mantenha seu SIM principal para chamadas/SMS e configure o eSIM apenas para dados. Você pode alternar a qualquer momento nas configurações.", AR: "نعم. احتفظ ببطاقة SIM الأساسية للمكالمات/الرسائل النصية القصيرة وقم بتعيين eSIM للبيانات فقط. يمكنك التبديل في أي وقت في الإعدادات.", IT: "Sì. Mantieni la tua SIM primaria per chiamate/SMS e imposta l'eSIM solo per i dati. Puoi cambiare in qualsiasi momento nelle impostazioni." },
  faq6Q: { EN: "How do I top up or buy again?", ES: "¿Cómo recargo o compro nuevamente?", FR: "Comment recharger ou acheter à nouveau ?", DE: "Wie lade ich auf oder kaufe erneut?", RU: "Как пополнить или купить снова?", ZH: "如何充值或再次购买？", JA: "チャージまたは再購入するにはどうすればよいですか？", PT: "Como recarrego ou compro novamente?", AR: "كيف أقوم بإعادة التعبئة أو الشراء مرة أخرى؟", IT: "Come ricarico o acquisto di nuovo?" },
  faq6A: { EN: "Return to the shop, pick a plan, and you'll get a fresh QR if needed. Some eSIMs support direct top-ups.", ES: "Vuelve a la tienda, elige un plan y obtendrás un nuevo QR si es necesario. Algunas eSIM admiten recargas directas.", FR: "Retournez à la boutique, choisissez un forfait et vous obtiendrez un nouveau QR si nécessaire. Certaines eSIM prennent en charge les recharges directes.", DE: "Kehre zum Shop zurück, wähle einen Plan und du erhältst bei Bedarf einen neuen QR-Code. Einige eSIMs unterstützen direkte Aufladungen.", RU: "Вернитесь в магазин, выберите план, и вы получите новый QR-код при необходимости. Некоторые eSIM поддерживают прямое пополнение.", ZH: "返回商店，选择计划，如果需要，您将获得新的二维码。某些 eSIM 支持直接充值。", JA: "ショップに戻り、プランを選択すると、必要に応じて新しい QR コードが取得されます。一部の eSIM は直接チャージをサポートしています。", PT: "Volte à loja, escolha um plano e você receberá um novo QR, se necessário. Alguns eSIMs suportam recargas diretas.", AR: "عد إلى المتجر، واختر خطة، وستحصل على رمز QR جديد إذا لزم الأمر. تدعم بعض eSIM عمليات إعادة التعبئة المباشرة.", IT: "Torna al negozio, scegli un piano e riceverai un nuovo QR se necessario. Alcuni eSIM supportano ricariche dirette." },
  faq7Q: { EN: "Which crypto can I pay with?", ES: "¿Con qué cripto puedo pagar?", FR: "Avec quelle crypto puis-je payer ?", DE: "Mit welcher Krypto kann ich bezahlen?", RU: "Какой криптовалютой я могу платить?", ZH: "我可以用哪种加密货币支付？", JA: "どの暗号通貨で支払うことができますか？", PT: "Com qual cripto posso pagar?", AR: "ما هي العملة المشفرة التي يمكنني الدفع بها؟", IT: "Con quale criptovaluta posso pagare?" },
  faq7A: { EN: "Pay with SOL or USDC on Solana. $NOMIQA support is coming soon.", ES: "Paga con SOL o USDC en Solana. El soporte para $NOMIQA llegará pronto.", FR: "Payez avec SOL ou USDC sur Solana. Le support $NOMIQA arrive bientôt.", DE: "Bezahle mit SOL oder USDC auf Solana. $NOMIQA-Unterstützung kommt bald.", RU: "Платите SOL или USDC в Solana. Поддержка $NOMIQA скоро появится.", ZH: "使用 Solana 上的 SOL 或 USDC 支付。$NOMIQA 支持即将推出。", JA: "Solana で SOL または USDC で支払います。$NOMIQA サポートは近日公開予定です。", PT: "Pague com SOL ou USDC na Solana. O suporte a $NOMIQA está chegando em breve.", AR: "ادفع باستخدام SOL أو USDC على Solana. دعم $NOMIQA قريبًا.", IT: "Paga con SOL o USDC su Solana. Il supporto $NOMIQA arriverà presto." },
  faq8Q: { EN: "Do you require ID or KYC?", ES: "¿Requieren identificación o KYC?", FR: "Exigez-vous une pièce d'identité ou KYC ?", DE: "Benötigt ihr einen Ausweis oder KYC?", RU: "Требуется ли удостоверение личности или KYC?", ZH: "你们需要身份证或 KYC 吗？", JA: "身分証明書または KYC は必要ですか？", PT: "Você exige identificação ou KYC?", AR: "هل تتطلب الهوية أو KYC؟", IT: "Richiedete un documento d'identità o KYC?" },
  faq8A: { EN: "No. We don't require ID or KYC. Your privacy matters.", ES: "No. No requerimos identificación ni KYC. Tu privacidad importa.", FR: "Non. Nous n'exigeons pas de pièce d'identité ni de KYC. Votre vie privée compte.", DE: "Nein. Wir benötigen keinen Ausweis oder KYC. Deine Privatsphäre ist wichtig.", RU: "Нет. Мы не требуем удостоверение личности или KYC. Ваша конфиденциальность важна.", ZH: "不。我们不需要身份证或 KYC。您的隐私很重要。", JA: "いいえ。身分証明書や KYC は必要ありません。あなたのプライバシーは重要です。", PT: "Não. Não exigimos identificação ou KYC. Sua privacidade é importante.", AR: "لا. نحن لا نطلب الهوية أو KYC. خصوصيتك مهمة.", IT: "No. Non richiediamo documenti d'identità o KYC. La tua privacy è importante." },
  faq9Q: { EN: "Can I use it in 190+ countries?", ES: "¿Puedo usarlo en más de 190 países?", FR: "Puis-je l'utiliser dans plus de 190 pays ?", DE: "Kann ich es in über 190 Ländern verwenden?", RU: "Могу ли я использовать его в более чем 190 странах?", ZH: "我可以在 190 多个国家/地区使用吗？", JA: "190か国以上で使用できますか？", PT: "Posso usá-lo em mais de 190 países?", AR: "هل يمكنني استخدامه في أكثر من 190 دولة؟", IT: "Posso usarlo in più di 190 paesi?" },
  faq9A: { EN: "Yes. We support 190+ countries. Coverage varies by plan.", ES: "Sí. Admitimos más de 190 países. La cobertura varía según el plan.", FR: "Oui. Nous prenons en charge plus de 190 pays. La couverture varie selon le forfait.", DE: "Ja. Wir unterstützen über 190 Länder. Die Abdeckung variiert je nach Plan.", RU: "Да. Мы поддерживаем более 190 стран. Покрытие зависит от плана.", ZH: "是的。我们支持 190 多个国家/地区。覆盖范围因计划而异。", JA: "はい。190か国以上をサポートしています。カバレッジはプランによって異なります。", PT: "Sim. Suportamos mais de 190 países. A cobertura varia de acordo com o plano.", AR: "نعم. ندعم أكثر من 190 دولة. تختلف التغطية حسب الخطة.", IT: "Sì. Supportiamo oltre 190 paesi. La copertura varia in base al piano." },
  faq10Q: { EN: "Where can I see my orders?", ES: "¿Dónde puedo ver mis pedidos?", FR: "Où puis-je voir mes commandes ?", DE: "Wo kann ich meine Bestellungen sehen?", RU: "Где я могу увидеть свои заказы?", ZH: "我在哪里可以看到我的订单？", JA: "注文はどこで確認できますか？", PT: "Onde posso ver meus pedidos?", AR: "أين يمكنني رؤية طلباتي؟", IT: "Dove posso vedere i miei ordini?" },
  faq10A: { EN: "Go to My Orders from the menu after signing in. You'll see QR codes, activation info, and status.", ES: "Ve a Mis pedidos desde el menú después de iniciar sesión. Verás los códigos QR, información de activación y el estado.", FR: "Accédez à Mes commandes depuis le menu après vous être connecté. Vous verrez les codes QR, les informations d'activation et le statut.", DE: "Gehe nach dem Anmelden im Menü zu Meine Bestellungen. Du siehst QR-Codes, Aktivierungsinformationen und Status.", RU: "Перейдите в раздел Мои заказы из меню после входа в систему. Вы увидите QR-коды, информацию об активации и статус.", ZH: "登录后从菜单转到我的订单。您将看到二维码、激活信息和状态。", JA: "サインイン後、メニューから注文履歴に移動します。QR コード、アクティベーション情報、ステータスが表示されます。", PT: "Vá para Meus pedidos no menu após fazer login. Você verá códigos QR, informações de ativação e status.", AR: "انتقل إلى طلباتي من القائمة بعد تسجيل الدخول. ستشاهد رموز QR ومعلومات التفعيل والحالة.", IT: "Vai a I miei ordini dal menu dopo aver effettuato l'accesso. Vedrai i codici QR, le informazioni di attivazione e lo stato." },


  // About Page
  aboutTitle: { EN: "About Us", ES: "Sobre nosotros", FR: "À propos de nous", DE: "Über uns", RU: "О нас", ZH: "关于我们", JA: "私たちについて", PT: "Sobre nós", AR: "من نحن", IT: "Chi siamo" },
  aboutSubtitle: { EN: "How Nomiqa became the world's first privacy-first eSIM platform", ES: "Cómo Nomiqa se convirtió en la primera plataforma de eSIM centrada en la privacidad del mundo", FR: "Comment Nomiqa est devenue la première plateforme eSIM axée sur la confidentialité au monde", DE: "Wie Nomiqa zur weltweit ersten datenschutzorientierten eSIM-Plattform wurde", RU: "Как Nomiqa стала первой в мире платформой eSIM, ориентированной на конфиденциальность", ZH: "Nomiqa 如何成为世界上第一个以隐私为先的 eSIM 平台", JA: "Nomiqa が世界初のプライバシー第一の eSIM プラットフォームになった経緯", PT: "Como a Nomiqa se tornou a primeira plataforma eSIM focada em privacidade do mundo", AR: "كيف أصبحت Nomiqa أول منصة eSIM تركز على الخصوصية في العالم", IT: "Come Nomiqa è diventata la prima piattaforma eSIM al mondo incentrata sulla privacy" },
  
  // Privacy Page
  privacyTitle: { EN: "How We Protect", ES: "Cómo protegemos", FR: "Comment nous protégeons", DE: "Wie wir schützen", RU: "Как мы защищаем", ZH: "我们如何保护", JA: "私たちの保護方法", PT: "Como protegemos", AR: "كيف نحمي", IT: "Come proteggiamo" },
  privacySubtitle: { EN: "Customer Privacy", ES: "Privacidad del cliente", FR: "Confidentialité client", DE: "Kundenprivatsphäre", RU: "Конфиденциальность клиентов", ZH: "客户隐私", JA: "顧客のプライバシー", PT: "Privacidade do cliente", AR: "خصوصية العميل", IT: "Privacy del cliente" },
  privacyDescription: { EN: "Your data is YOURS. Not ours. Not anyone's. Here's how we guarantee it.", ES: "Tus datos son TUYOS. No nuestros. Ni de nadie. Así es como lo garantizamos.", FR: "Vos données sont à VOUS. Pas à nous. À personne. Voici comment nous le garantissons.", DE: "Deine Daten gehören DIR. Nicht uns. Niemand anderem. So garantieren wir das.", RU: "Ваши данные принадлежат ВАМ. Не нам. Никому. Вот как мы это гарантируем.", ZH: "您的数据是您的。不是我们的。也不是任何人的。这就是我们如何保证它。", JA: "あなたのデータはあなたのものです。私たちのものではありません。誰のものでもありません。それを保証する方法です。", PT: "Seus dados são SEUS. Não nossos. Nem de ninguém. Veja como garantimos isso.", AR: "بياناتك ملكك. ليست لنا. ولا لأحد. إليك كيف نضمن ذلك.", IT: "I tuoi dati sono TUOI. Non nostri. Non di nessuno. Ecco come lo garantiamo." },
};

function isRTL(lang: Language) {
  return lang === "AR"; // Arabic
}

function detectBrowserLanguage(): Language {
  if (typeof navigator === 'undefined') return "EN";
  
  const browserLang = navigator.language || (navigator as any).userLanguage;
  const langCode = browserLang.split('-')[0].toUpperCase();
  
  const langMap: Record<string, Language> = {
    'EN': 'EN', 'ES': 'ES', 'FR': 'FR', 'DE': 'DE', 
    'RU': 'RU', 'ZH': 'ZH', 'JA': 'JA', 'PT': 'PT', 
    'AR': 'AR', 'IT': 'IT'
  };
  
  return langMap[langCode] || "EN";
}

// getInitialLanguage moved below to support path-based locale slugs

export function TranslationProvider({ children }: { children: ReactNode }) {
  const [language, setLang] = useState<Language>(getInitialLanguage);

  useEffect(() => {
    // Persist to localStorage
    if (typeof window !== 'undefined') {
      localStorage.setItem("lang", language);
    }
    
    // Update document attributes
    const dir = isRTL(language) ? "rtl" : "ltr";
    if (typeof document !== 'undefined' && document.documentElement) {
      document.documentElement.setAttribute("dir", dir);
      document.documentElement.setAttribute("lang", language.toLowerCase());
    }
  }, [language]);

  const t = useMemo(() => {
    return (key: string) => {
      const entry = translations[key];
      if (!entry) return key;
      return entry[language] ?? entry["EN"] ?? key;
    };
  }, [language]);

  const value = useMemo<TranslationContextType>(() => ({
    language,
    setLanguage: (l: Language) => setLang(l),
    t,
  }), [language, t]);

  return (
    <TranslationContext.Provider value={value}>
      {children}
    </TranslationContext.Provider>
  );
}

function getPathLanguage(): Language | null {
  if (typeof window === 'undefined') return null;
  const slug = window.location.pathname.split('/')[1]?.toLowerCase();
  const slugMap: Record<string, Language> = {
    english: 'EN', espanol: 'ES', francais: 'FR', deutsch: 'DE',
    russian: 'RU', chinese: 'ZH', japanese: 'JA', portugues: 'PT', arabic: 'AR', italiano: 'IT'
  };
  return slug ? slugMap[slug] ?? null : null;
}

function getInitialLanguage(): Language {
  if (typeof window === 'undefined') return "EN";

  // 1) From path slug
  const fromPath = getPathLanguage();
  if (fromPath) return fromPath;

  // 2) From localStorage
  const savedLang = localStorage.getItem("lang") as Language | null;
  if (savedLang && ['EN','ES','FR','DE','RU','ZH','JA','PT','AR','IT'].includes(savedLang)) {
    return savedLang;
  }

  // 3) From browser
  return detectBrowserLanguage();
}

export function useTranslation() {
  const ctx = useContext(TranslationContext);
  if (!ctx) {
    throw new Error("useTranslation must be used within TranslationProvider");
  }
  return ctx;
}
