import { createContext, useContext, useState, ReactNode, useEffect } from "react";

type Language = "EN" | "ES" | "FR" | "DE" | "RU" | "ZH" | "JA" | "PT" | "AR" | "HI";

interface TranslationContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const TranslationContext = createContext<TranslationContextType | undefined>(undefined);

const translations: Record<string, Record<Language, string>> = {
  // Navigation
  shop: { EN: "Shop", ES: "Shop", FR: "Shop", DE: "Shop", RU: "Shop", ZH: "Shop", JA: "Shop", PT: "Shop", AR: "Shop", HI: "Shop" },
  gettingStarted: { EN: "Getting Started", ES: "Getting Started", FR: "Getting Started", DE: "Getting Started", RU: "Getting Started", ZH: "Getting Started", JA: "Getting Started", PT: "Getting Started", AR: "Getting Started", HI: "Getting Started" },
  howToBuy: { EN: "How to Buy (SOL & $NOMIQA token)", ES: "How to Buy (SOL & $NOMIQA token)", FR: "How to Buy (SOL & $NOMIQA token)", DE: "How to Buy (SOL & $NOMIQA token)", RU: "How to Buy (SOL & $NOMIQA token)", ZH: "How to Buy (SOL & $NOMIQA token)", JA: "How to Buy (SOL & $NOMIQA token)", PT: "How to Buy (SOL & $NOMIQA token)", AR: "How to Buy (SOL & $NOMIQA token)", HI: "How to Buy (SOL & $NOMIQA token)" },
  stake: { EN: "Stake", ES: "Stake", FR: "Stake", DE: "Stake", RU: "Stake", ZH: "Stake", JA: "Stake", PT: "Stake", AR: "Stake", HI: "Stake" },
  roadmap: { EN: "Roadmap", ES: "Roadmap", FR: "Roadmap", DE: "Roadmap", RU: "Roadmap", ZH: "Roadmap", JA: "Roadmap", PT: "Roadmap", AR: "Roadmap", HI: "Roadmap" },
  affiliate: { EN: "Affiliate", ES: "Affiliate", FR: "Affiliate", DE: "Affiliate", RU: "Affiliate", ZH: "Affiliate", JA: "Affiliate", PT: "Affiliate", AR: "Affiliate", HI: "Affiliate" },
  aboutUs: { EN: "About Us", ES: "About Us", FR: "About Us", DE: "About Us", RU: "About Us", ZH: "About Us", JA: "About Us", PT: "About Us", AR: "About Us", HI: "About Us" },
  howWeProtect: { EN: "How We Protect You", ES: "How We Protect You", FR: "How We Protect You", DE: "How We Protect You", RU: "How We Protect You", ZH: "How We Protect You", JA: "How We Protect You", PT: "How We Protect You", AR: "How We Protect You", HI: "How We Protect You" },
  myEsims: { EN: "My eSIMs", ES: "My eSIMs", FR: "My eSIMs", DE: "My eSIMs", RU: "My eSIMs", ZH: "My eSIMs", JA: "My eSIMs", PT: "My eSIMs", AR: "My eSIMs", HI: "My eSIMs" },
  myOrders: { EN: "My Orders", ES: "My Orders", FR: "My Orders", DE: "My Orders", RU: "My Orders", ZH: "My Orders", JA: "My Orders", PT: "My Orders", AR: "My Orders", HI: "My Orders" },
  signIn: { EN: "Sign In", ES: "Sign In", FR: "Sign In", DE: "Sign In", RU: "Sign In", ZH: "Sign In", JA: "Sign In", PT: "Sign In", AR: "Sign In", HI: "Sign In" },
  signOut: { EN: "Sign Out", ES: "Sign Out", FR: "Sign Out", DE: "Sign Out", RU: "Sign Out", ZH: "Sign Out", JA: "Sign Out", PT: "Sign Out", AR: "Sign Out", HI: "Sign Out" },
  signUp: { EN: "Sign Up", ES: "Sign Up", FR: "Sign Up", DE: "Sign Up", RU: "Sign Up", ZH: "Sign Up", JA: "Sign Up", PT: "Sign Up", AR: "Sign Up", HI: "Sign Up" },
  menu: { EN: "Menu", ES: "Menu", FR: "Menu", DE: "Menu", RU: "Menu", ZH: "Menu", JA: "Menu", PT: "Menu", AR: "Menu", HI: "Menu" },

  // Hero
  heroPrivate: { EN: "Private.", ES: "Private.", FR: "Private.", DE: "Private.", RU: "Private.", ZH: "Private.", JA: "Private.", PT: "Private.", AR: "Private.", HI: "Private." },
  heroBorderless: { EN: "Borderless.", ES: "Borderless.", FR: "Borderless.", DE: "Borderless.", RU: "Borderless.", ZH: "Borderless.", JA: "Borderless.", PT: "Borderless.", AR: "Borderless.", HI: "Borderless." },
  heroHuman: { EN: "Human.", ES: "Human.", FR: "Human.", DE: "Human.", RU: "Human.", ZH: "Human.", JA: "Human.", PT: "Human.", AR: "Human.", HI: "Human." },
  heroDescription1: { EN: "Connect anywhere in 60 seconds — no ID, no tracking, no limits", ES: "Connect anywhere in 60 seconds — no ID, no tracking, no limits", FR: "Connect anywhere in 60 seconds — no ID, no tracking, no limits", DE: "Connect anywhere in 60 seconds — no ID, no tracking, no limits", RU: "Connect anywhere in 60 seconds — no ID, no tracking, no limits", ZH: "Connect anywhere in 60 seconds — no ID, no tracking, no limits", JA: "Connect anywhere in 60 seconds — no ID, no tracking, no limits", PT: "Connect anywhere in 60 seconds — no ID, no tracking, no limits", AR: "Connect anywhere in 60 seconds — no ID, no tracking, no limits", HI: "Connect anywhere in 60 seconds — no ID, no tracking, no limits" },
  heroDescription2: { EN: "Join the world's first crypto-powered eSIM for freedom on your terms.", ES: "Join the world's first crypto-powered eSIM for freedom on your terms.", FR: "Join the world's first crypto-powered eSIM for freedom on your terms.", DE: "Join the world's first crypto-powered eSIM for freedom on your terms.", RU: "Join the world's first crypto-powered eSIM for freedom on your terms.", ZH: "Join the world's first crypto-powered eSIM for freedom on your terms.", JA: "Join the world's first crypto-powered eSIM for freedom on your terms.", PT: "Join the world's first crypto-powered eSIM for freedom on your terms.", AR: "Join the world's first crypto-powered eSIM for freedom on your terms.", HI: "Join the world's first crypto-powered eSIM for freedom on your terms." },
  heroBuyNow: { EN: "Buy Now", ES: "Buy Now", FR: "Buy Now", DE: "Buy Now", RU: "Buy Now", ZH: "Buy Now", JA: "Buy Now", PT: "Buy Now", AR: "Buy Now", HI: "Buy Now" },
  heroWatchHow: { EN: "Watch How It Works", ES: "Watch How It Works", FR: "Watch How It Works", DE: "Watch How It Works", RU: "Watch How It Works", ZH: "Watch How It Works", JA: "Watch How It Works", PT: "Watch How It Works", AR: "Watch How It Works", HI: "Watch How It Works" },

  // How It Works
  howItWorksTag: { EN: "HOW IT WORKS", ES: "HOW IT WORKS", FR: "HOW IT WORKS", DE: "HOW IT WORKS", RU: "HOW IT WORKS", ZH: "HOW IT WORKS", JA: "HOW IT WORKS", PT: "HOW IT WORKS", AR: "HOW IT WORKS", HI: "HOW IT WORKS" },
  howItWorksTitle: { EN: "Connect in 3 Steps", ES: "Connect in 3 Steps", FR: "Connect in 3 Steps", DE: "Connect in 3 Steps", RU: "Connect in 3 Steps", ZH: "Connect in 3 Steps", JA: "Connect in 3 Steps", PT: "Connect in 3 Steps", AR: "Connect in 3 Steps", HI: "Connect in 3 Steps" },
  howItWorksSubtitle: { EN: "From purchase to connection in under 60 seconds", ES: "From purchase to connection in under 60 seconds", FR: "From purchase to connection in under 60 seconds", DE: "From purchase to connection in under 60 seconds", RU: "From purchase to connection in under 60 seconds", ZH: "From purchase to connection in under 60 seconds", JA: "From purchase to connection in under 60 seconds", PT: "From purchase to connection in under 60 seconds", AR: "From purchase to connection in under 60 seconds", HI: "From purchase to connection in under 60 seconds" },

  // Why Nomiqa
  whyNomiqaMainTitle: { EN: "Because your freedom shouldn't come with surveillance.", ES: "Because your freedom shouldn't come with surveillance.", FR: "Because your freedom shouldn't come with surveillance.", DE: "Because your freedom shouldn't come with surveillance.", RU: "Because your freedom shouldn't come with surveillance.", ZH: "Because your freedom shouldn't come with surveillance.", JA: "Because your freedom shouldn't come with surveillance.", PT: "Because your freedom shouldn't come with surveillance.", AR: "Because your freedom shouldn't come with surveillance.", HI: "Because your freedom shouldn't come with surveillance." },
  whyNomiqaMainSubtitle: { EN: "True privacy, instant freedom, borderless connection", ES: "True privacy, instant freedom, borderless connection", FR: "True privacy, instant freedom, borderless connection", DE: "True privacy, instant freedom, borderless connection", RU: "True privacy, instant freedom, borderless connection", ZH: "True privacy, instant freedom, borderless connection", JA: "True privacy, instant freedom, borderless connection", PT: "True privacy, instant freedom, borderless connection", AR: "True privacy, instant freedom, borderless connection", HI: "True privacy, instant freedom, borderless connection" },
  whyNomiqaPrivacyTitle: { EN: "True Privacy. Zero Compromise.", ES: "True Privacy. Zero Compromise.", FR: "True Privacy. Zero Compromise.", DE: "True Privacy. Zero Compromise.", RU: "True Privacy. Zero Compromise.", ZH: "True Privacy. Zero Compromise.", JA: "True Privacy. Zero Compromise.", PT: "True Privacy. Zero Compromise.", AR: "True Privacy. Zero Compromise.", HI: "True Privacy. Zero Compromise." },
  whyNomiqaPrivacyDesc: { EN: "Your data is YOURS. No ID checks, no surveillance, no digital footprints.", ES: "Your data is YOURS. No ID checks, no surveillance, no digital footprints.", FR: "Your data is YOURS. No ID checks, no surveillance, no digital footprints.", DE: "Your data is YOURS. No ID checks, no surveillance, no digital footprints.", RU: "Your data is YOURS. No ID checks, no surveillance, no digital footprints.", ZH: "Your data is YOURS. No ID checks, no surveillance, no digital footprints.", JA: "Your data is YOURS. No ID checks, no surveillance, no digital footprints.", PT: "Your data is YOURS. No ID checks, no surveillance, no digital footprints.", AR: "Your data is YOURS. No ID checks, no surveillance, no digital footprints.", HI: "Your data is YOURS. No ID checks, no surveillance, no digital footprints." },
  whyNomiqaAccessTitle: { EN: "Instant Access. Real Freedom.", ES: "Instant Access. Real Freedom.", FR: "Instant Access. Real Freedom.", DE: "Instant Access. Real Freedom.", RU: "Instant Access. Real Freedom.", ZH: "Instant Access. Real Freedom.", JA: "Instant Access. Real Freedom.", PT: "Instant Access. Real Freedom.", AR: "Instant Access. Real Freedom.", HI: "Instant Access. Real Freedom." },
  whyNomiqaAccessDesc: { EN: "Pay with crypto. Activate in seconds. No banks watching. No delays.", ES: "Pay with crypto. Activate in seconds. No banks watching. No delays.", FR: "Pay with crypto. Activate in seconds. No banks watching. No delays.", DE: "Pay with crypto. Activate in seconds. No banks watching. No delays.", RU: "Pay with crypto. Activate in seconds. No banks watching. No delays.", ZH: "Pay with crypto. Activate in seconds. No banks watching. No delays.", JA: "Pay with crypto. Activate in seconds. No banks watching. No delays.", PT: "Pay with crypto. Activate in seconds. No banks watching. No delays.", AR: "Pay with crypto. Activate in seconds. No banks watching. No delays.", HI: "Pay with crypto. Activate in seconds. No banks watching. No delays." },
  whyNomiqaBorderlessTitle: { EN: "Borderless Connection. Limitless Possibilities.", ES: "Borderless Connection. Limitless Possibilities.", FR: "Borderless Connection. Limitless Possibilities.", DE: "Borderless Connection. Limitless Possibilities.", RU: "Borderless Connection. Limitless Possibilities.", ZH: "Borderless Connection. Limitless Possibilities.", JA: "Borderless Connection. Limitless Possibilities.", PT: "Borderless Connection. Limitless Possibilities.", AR: "Borderless Connection. Limitless Possibilities.", HI: "Borderless Connection. Limitless Possibilities." },
  whyNomiqaBorderlessDesc: { EN: "190+ countries. One eSIM. The world is yours to explore freely.", ES: "190+ countries. One eSIM. The world is yours to explore freely.", FR: "190+ countries. One eSIM. The world is yours to explore freely.", DE: "190+ countries. One eSIM. The world is yours to explore freely.", RU: "190+ countries. One eSIM. The world is yours to explore freely.", ZH: "190+ countries. One eSIM. The world is yours to explore freely.", JA: "190+ countries. One eSIM. The world is yours to explore freely.", PT: "190+ countries. One eSIM. The world is yours to explore freely.", AR: "190+ countries. One eSIM. The world is yours to explore freely.", HI: "190+ countries. One eSIM. The world is yours to explore freely." },

  // Coverage Section
  coverageTitle: { EN: "Connected. Everywhere.", ES: "Connected. Everywhere.", FR: "Connected. Everywhere.", DE: "Connected. Everywhere.", RU: "Connected. Everywhere.", ZH: "Connected. Everywhere.", JA: "Connected. Everywhere.", PT: "Connected. Everywhere.", AR: "Connected. Everywhere.", HI: "Connected. Everywhere." },
  coverageSubtitle1: { EN: "From cities to deserts, your signal follows you.", ES: "From cities to deserts, your signal follows you.", FR: "From cities to deserts, your signal follows you.", DE: "From cities to deserts, your signal follows you.", RU: "From cities to deserts, your signal follows you.", ZH: "From cities to deserts, your signal follows you.", JA: "From cities to deserts, your signal follows you.", PT: "From cities to deserts, your signal follows you.", AR: "From cities to deserts, your signal follows you.", HI: "From cities to deserts, your signal follows you." },
  coverageSubtitle2: { EN: "190+ countries, one private connection.", ES: "190+ countries, one private connection.", FR: "190+ countries, one private connection.", DE: "190+ countries, one private connection.", RU: "190+ countries, one private connection.", ZH: "190+ countries, one private connection.", JA: "190+ countries, one private connection.", PT: "190+ countries, one private connection.", AR: "190+ countries, one private connection.", HI: "190+ countries, one private connection." },
  coverageQuote: { EN: "Freedom means never losing signal — or yourself.", ES: "Freedom means never losing signal — or yourself.", FR: "Freedom means never losing signal — or yourself.", DE: "Freedom means never losing signal — or yourself.", RU: "Freedom means never losing signal — or yourself.", ZH: "Freedom means never losing signal — or yourself.", JA: "Freedom means never losing signal — or yourself.", PT: "Freedom means never losing signal — or yourself.", AR: "Freedom means never losing signal — or yourself.", HI: "Freedom means never losing signal — or yourself." },
  coverageCountries: { EN: "Countries", ES: "Countries", FR: "Countries", DE: "Countries", RU: "Countries", ZH: "Countries", JA: "Countries", PT: "Countries", AR: "Countries", HI: "Countries" },
  coverageUptime: { EN: "Uptime", ES: "Uptime", FR: "Uptime", DE: "Uptime", RU: "Uptime", ZH: "Uptime", JA: "Uptime", PT: "Uptime", AR: "Uptime", HI: "Uptime" },
  coverageSpeed: { EN: "Speed", ES: "Speed", FR: "Speed", DE: "Speed", RU: "Speed", ZH: "Speed", JA: "Speed", PT: "Speed", AR: "Speed", HI: "Speed" },

  // Our Story Section
  ourStoryTag: { EN: "OUR STORY", ES: "OUR STORY", FR: "OUR STORY", DE: "OUR STORY", RU: "OUR STORY", ZH: "OUR STORY", JA: "OUR STORY", PT: "OUR STORY", AR: "OUR STORY", HI: "OUR STORY" },
  ourStorySubtitle: { EN: "Building the infrastructure for digital freedom", ES: "Building the infrastructure for digital freedom", FR: "Building the infrastructure for digital freedom", DE: "Building the infrastructure for digital freedom", RU: "Building the infrastructure for digital freedom", ZH: "Building the infrastructure for digital freedom", JA: "Building the infrastructure for digital freedom", PT: "Building the infrastructure for digital freedom", AR: "Building the infrastructure for digital freedom", HI: "Building the infrastructure for digital freedom" },
  privacyFirstTitle: { EN: "Privacy-First", ES: "Privacy-First", FR: "Privacy-First", DE: "Privacy-First", RU: "Privacy-First", ZH: "Privacy-First", JA: "Privacy-First", PT: "Privacy-First", AR: "Privacy-First", HI: "Privacy-First" },
  privacyFirstDesc: { EN: "No KYC. No tracking. No surveillance. Your identity stays yours.", ES: "No KYC. No tracking. No surveillance. Your identity stays yours.", FR: "No KYC. No tracking. No surveillance. Your identity stays yours.", DE: "No KYC. No tracking. No surveillance. Your identity stays yours.", RU: "No KYC. No tracking. No surveillance. Your identity stays yours.", ZH: "No KYC. No tracking. No surveillance. Your identity stays yours.", JA: "No KYC. No tracking. No surveillance. Your identity stays yours.", PT: "No KYC. No tracking. No surveillance. Your identity stays yours.", AR: "No KYC. No tracking. No surveillance. Your identity stays yours.", HI: "No KYC. No tracking. No surveillance. Your identity stays yours." },
  cryptoNativeTitle: { EN: "Crypto-Native", ES: "Crypto-Native", FR: "Crypto-Native", DE: "Crypto-Native", RU: "Crypto-Native", ZH: "Crypto-Native", JA: "Crypto-Native", PT: "Crypto-Native", AR: "Crypto-Native", HI: "Crypto-Native" },
  cryptoNativeDesc: { EN: "Pay with SOL or USDC. Fast, private, and censorship-resistant.", ES: "Pay with SOL or USDC. Fast, private, and censorship-resistant.", FR: "Pay with SOL or USDC. Fast, private, and censorship-resistant.", DE: "Pay with SOL or USDC. Fast, private, and censorship-resistant.", RU: "Pay with SOL or USDC. Fast, private, and censorship-resistant.", ZH: "Pay with SOL or USDC. Fast, private, and censorship-resistant.", JA: "Pay with SOL or USDC. Fast, private, and censorship-resistant.", PT: "Pay with SOL or USDC. Fast, private, and censorship-resistant.", AR: "Pay with SOL or USDC. Fast, private, and censorship-resistant.", HI: "Pay with SOL or USDC. Fast, private, and censorship-resistant." },
  communityOwnedTitle: { EN: "Community-Owned", ES: "Community-Owned", FR: "Community-Owned", DE: "Community-Owned", RU: "Community-Owned", ZH: "Community-Owned", JA: "Community-Owned", PT: "Community-Owned", AR: "Community-Owned", HI: "Community-Owned" },
  communityOwnedDesc: { EN: "Powered by the people, for the people. Join the movement.", ES: "Powered by the people, for the people. Join the movement.", FR: "Powered by the people, for the people. Join the movement.", DE: "Powered by the people, for the people. Join the movement.", RU: "Powered by the people, for the people. Join the movement.", ZH: "Powered by the people, for the people. Join the movement.", JA: "Powered by the people, for the people. Join the movement.", PT: "Powered by the people, for the people. Join the movement.", AR: "Powered by the people, for the people. Join the movement.", HI: "Powered by the people, for the people. Join the movement." },
  learnMoreAbout: { EN: "Learn More About Us", ES: "Learn More About Us", FR: "Learn More About Us", DE: "Learn More About Us", RU: "Learn More About Us", ZH: "Learn More About Us", JA: "Learn More About Us", PT: "Learn More About Us", AR: "Learn More About Us", HI: "Learn More About Us" },

  // Earn Section
  earnMainTitle: { EN: "Travel the world. Earn as you move.", ES: "Travel the world. Earn as you move.", FR: "Travel the world. Earn as you move.", DE: "Travel the world. Earn as you move.", RU: "Travel the world. Earn as you move.", ZH: "Travel the world. Earn as you move.", JA: "Travel the world. Earn as you move.", PT: "Travel the world. Earn as you move.", AR: "Travel the world. Earn as you move.", HI: "Travel the world. Earn as you move." },
  earnMainSubtitle: { EN: "Stake $NOMIQA and earn data + rewards while connecting others.", ES: "Stake $NOMIQA and earn data + rewards while connecting others.", FR: "Stake $NOMIQA and earn data + rewards while connecting others.", DE: "Stake $NOMIQA and earn data + rewards while connecting others.", RU: "Stake $NOMIQA and earn data + rewards while connecting others.", ZH: "Stake $NOMIQA and earn data + rewards while connecting others.", JA: "Stake $NOMIQA and earn data + rewards while connecting others.", PT: "Stake $NOMIQA and earn data + rewards while connecting others.", AR: "Stake $NOMIQA and earn data + rewards while connecting others.", HI: "Stake $NOMIQA and earn data + rewards while connecting others." },
  earnMainDescription: { EN: "Build your network of travelers, creators, and Web3 pioneers.", ES: "Build your network of travelers, creators, and Web3 pioneers.", FR: "Build your network of travelers, creators, and Web3 pioneers.", DE: "Build your network of travelers, creators, and Web3 pioneers.", RU: "Build your network of travelers, creators, and Web3 pioneers.", ZH: "Build your network of travelers, creators, and Web3 pioneers.", JA: "Build your network of travelers, creators, and Web3 pioneers.", PT: "Build your network of travelers, creators, and Web3 pioneers.", AR: "Build your network of travelers, creators, and Web3 pioneers.", HI: "Build your network of travelers, creators, and Web3 pioneers." },
  earnStartStaking: { EN: "Start Staking", ES: "Start Staking", FR: "Start Staking", DE: "Start Staking", RU: "Start Staking", ZH: "Start Staking", JA: "Start Staking", PT: "Start Staking", AR: "Start Staking", HI: "Start Staking" },
  earnJoinAffiliate: { EN: "Join the Affiliate Network", ES: "Join the Affiliate Network", FR: "Join the Affiliate Network", DE: "Join the Affiliate Network", RU: "Join the Affiliate Network", ZH: "Join the Affiliate Network", JA: "Join the Affiliate Network", PT: "Join the Affiliate Network", AR: "Join the Affiliate Network", HI: "Join the Affiliate Network" },

  // FAQ
  faqTitle: { EN: "Frequently Asked Questions", ES: "Frequently Asked Questions", FR: "Frequently Asked Questions", DE: "Frequently Asked Questions", RU: "Frequently Asked Questions", ZH: "Frequently Asked Questions", JA: "Frequently Asked Questions", PT: "Frequently Asked Questions", AR: "Frequently Asked Questions", HI: "Frequently Asked Questions" },
  faqSubtitle: { EN: "Everything you need to know about nomiqa", ES: "Everything you need to know about nomiqa", FR: "Everything you need to know about nomiqa", DE: "Everything you need to know about nomiqa", RU: "Everything you need to know about nomiqa", ZH: "Everything you need to know about nomiqa", JA: "Everything you need to know about nomiqa", PT: "Everything you need to know about nomiqa", AR: "Everything you need to know about nomiqa", HI: "Everything you need to know about nomiqa" },
  faq1Q: { EN: "What is an eSIM?", ES: "What is an eSIM?", FR: "What is an eSIM?", DE: "What is an eSIM?", RU: "What is an eSIM?", ZH: "What is an eSIM?", JA: "What is an eSIM?", PT: "What is an eSIM?", AR: "What is an eSIM?", HI: "What is an eSIM?" },
  faq1A: { EN: "An eSIM is a digital SIM that allows you to activate a mobile plan without a physical SIM card.", ES: "An eSIM is a digital SIM that allows you to activate a mobile plan without a physical SIM card.", FR: "An eSIM is a digital SIM that allows you to activate a mobile plan without a physical SIM card.", DE: "An eSIM is a digital SIM that allows you to activate a mobile plan without a physical SIM card.", RU: "An eSIM is a digital SIM that allows you to activate a mobile plan without a physical SIM card.", ZH: "An eSIM is a digital SIM that allows you to activate a mobile plan without a physical SIM card.", JA: "An eSIM is a digital SIM that allows you to activate a mobile plan without a physical SIM card.", PT: "An eSIM is a digital SIM that allows you to activate a mobile plan without a physical SIM card.", AR: "An eSIM is a digital SIM that allows you to activate a mobile plan without a physical SIM card.", HI: "An eSIM is a digital SIM that allows you to activate a mobile plan without a physical SIM card." },
  faq2Q: { EN: "How do I pay with crypto?", ES: "How do I pay with crypto?", FR: "How do I pay with crypto?", DE: "How do I pay with crypto?", RU: "How do I pay with crypto?", ZH: "How do I pay with crypto?", JA: "How do I pay with crypto?", PT: "How do I pay with crypto?", AR: "How do I pay with crypto?", HI: "How do I pay with crypto?" },
  faq2A: { EN: "We accept SOL and USDC payments on Solana. Simply connect your wallet at checkout.", ES: "We accept SOL and USDC payments on Solana. Simply connect your wallet at checkout.", FR: "We accept SOL and USDC payments on Solana. Simply connect your wallet at checkout.", DE: "We accept SOL and USDC payments on Solana. Simply connect your wallet at checkout.", RU: "We accept SOL and USDC payments on Solana. Simply connect your wallet at checkout.", ZH: "We accept SOL and USDC payments on Solana. Simply connect your wallet at checkout.", JA: "We accept SOL and USDC payments on Solana. Simply connect your wallet at checkout.", PT: "We accept SOL and USDC payments on Solana. Simply connect your wallet at checkout.", AR: "We accept SOL and USDC payments on Solana. Simply connect your wallet at checkout.", HI: "We accept SOL and USDC payments on Solana. Simply connect your wallet at checkout." },
  faq3Q: { EN: "Do I need KYC verification?", ES: "Do I need KYC verification?", FR: "Do I need KYC verification?", DE: "Do I need KYC verification?", RU: "Do I need KYC verification?", ZH: "Do I need KYC verification?", JA: "Do I need KYC verification?", PT: "Do I need KYC verification?", AR: "Do I need KYC verification?", HI: "Do I need KYC verification?" },
  faq3A: { EN: "No. We never require ID or personal information. Your privacy is our priority.", ES: "No. We never require ID or personal information. Your privacy is our priority.", FR: "No. We never require ID or personal information. Your privacy is our priority.", DE: "No. We never require ID or personal information. Your privacy is our priority.", RU: "No. We never require ID or personal information. Your privacy is our priority.", ZH: "No. We never require ID or personal information. Your privacy is our priority.", JA: "No. We never require ID or personal information. Your privacy is our priority.", PT: "No. We never require ID or personal information. Your privacy is our priority.", AR: "No. We never require ID or personal information. Your privacy is our priority.", HI: "No. We never require ID or personal information. Your privacy is our priority." },
  faq4Q: { EN: "How long does activation take?", ES: "How long does activation take?", FR: "How long does activation take?", DE: "How long does activation take?", RU: "How long does activation take?", ZH: "How long does activation take?", JA: "How long does activation take?", PT: "How long does activation take?", AR: "How long does activation take?", HI: "How long does activation take?" },
  faq4A: { EN: "Instant! Scan the QR code after purchase and you're connected in seconds.", ES: "Instant! Scan the QR code after purchase and you're connected in seconds.", FR: "Instant! Scan the QR code after purchase and you're connected in seconds.", DE: "Instant! Scan the QR code after purchase and you're connected in seconds.", RU: "Instant! Scan the QR code after purchase and you're connected in seconds.", ZH: "Instant! Scan the QR code after purchase and you're connected in seconds.", JA: "Instant! Scan the QR code after purchase and you're connected in seconds.", PT: "Instant! Scan the QR code after purchase and you're connected in seconds.", AR: "Instant! Scan the QR code after purchase and you're connected in seconds.", HI: "Instant! Scan the QR code after purchase and you're connected in seconds." },
  faq5Q: { EN: "Which countries are supported?", ES: "Which countries are supported?", FR: "Which countries are supported?", DE: "Which countries are supported?", RU: "Which countries are supported?", ZH: "Which countries are supported?", JA: "Which countries are supported?", PT: "Which countries are supported?", AR: "Which countries are supported?", HI: "Which countries are supported?" },
  faq5A: { EN: "We support 190+ countries worldwide. Check our coverage map for details.", ES: "We support 190+ countries worldwide. Check our coverage map for details.", FR: "We support 190+ countries worldwide. Check our coverage map for details.", DE: "We support 190+ countries worldwide. Check our coverage map for details.", RU: "We support 190+ countries worldwide. Check our coverage map for details.", ZH: "We support 190+ countries worldwide. Check our coverage map for details.", JA: "We support 190+ countries worldwide. Check our coverage map for details.", PT: "We support 190+ countries worldwide. Check our coverage map for details.", AR: "We support 190+ countries worldwide. Check our coverage map for details.", HI: "We support 190+ countries worldwide. Check our coverage map for details." },
  faq6Q: { EN: "Can I use it with my current phone?", ES: "Can I use it with my current phone?", FR: "Can I use it with my current phone?", DE: "Can I use it with my current phone?", RU: "Can I use it with my current phone?", ZH: "Can I use it with my current phone?", JA: "Can I use it with my current phone?", PT: "Can I use it with my current phone?", AR: "Can I use it with my current phone?", HI: "Can I use it with my current phone?" },
  faq6A: { EN: "Most modern smartphones support eSIM. Check your device compatibility.", ES: "Most modern smartphones support eSIM. Check your device compatibility.", FR: "Most modern smartphones support eSIM. Check your device compatibility.", DE: "Most modern smartphones support eSIM. Check your device compatibility.", RU: "Most modern smartphones support eSIM. Check your device compatibility.", ZH: "Most modern smartphones support eSIM. Check your device compatibility.", JA: "Most modern smartphones support eSIM. Check your device compatibility.", PT: "Most modern smartphones support eSIM. Check your device compatibility.", AR: "Most modern smartphones support eSIM. Check your device compatibility.", HI: "Most modern smartphones support eSIM. Check your device compatibility." },
  faq7Q: { EN: "What happens to my data after the plan expires?", ES: "What happens to my data after the plan expires?", FR: "What happens to my data after the plan expires?", DE: "What happens to my data after the plan expires?", RU: "What happens to my data after the plan expires?", ZH: "What happens to my data after the plan expires?", JA: "What happens to my data after the plan expires?", PT: "What happens to my data after the plan expires?", AR: "What happens to my data after the plan expires?", HI: "What happens to my data after the plan expires?" },
  faq7A: { EN: "Your eSIM stays on your device. Simply top up to reactivate.", ES: "Your eSIM stays on your device. Simply top up to reactivate.", FR: "Your eSIM stays on your device. Simply top up to reactivate.", DE: "Your eSIM stays on your device. Simply top up to reactivate.", RU: "Your eSIM stays on your device. Simply top up to reactivate.", ZH: "Your eSIM stays on your device. Simply top up to reactivate.", JA: "Your eSIM stays on your device. Simply top up to reactivate.", PT: "Your eSIM stays on your device. Simply top up to reactivate.", AR: "Your eSIM stays on your device. Simply top up to reactivate.", HI: "Your eSIM stays on your device. Simply top up to reactivate." },
  faq8Q: { EN: "Is my connection secure?", ES: "Is my connection secure?", FR: "Is my connection secure?", DE: "Is my connection secure?", RU: "Is my connection secure?", ZH: "Is my connection secure?", JA: "Is my connection secure?", PT: "Is my connection secure?", AR: "Is my connection secure?", HI: "Is my connection secure?" },
  faq8A: { EN: "Yes. We use encrypted connections and don't track your browsing.", ES: "Yes. We use encrypted connections and don't track your browsing.", FR: "Yes. We use encrypted connections and don't track your browsing.", DE: "Yes. We use encrypted connections and don't track your browsing.", RU: "Yes. We use encrypted connections and don't track your browsing.", ZH: "Yes. We use encrypted connections and don't track your browsing.", JA: "Yes. We use encrypted connections and don't track your browsing.", PT: "Yes. We use encrypted connections and don't track your browsing.", AR: "Yes. We use encrypted connections and don't track your browsing.", HI: "Yes. We use encrypted connections and don't track your browsing." },
  faq9Q: { EN: "What is the $NOMIQA token?", ES: "What is the $NOMIQA token?", FR: "What is the $NOMIQA token?", DE: "What is the $NOMIQA token?", RU: "What is the $NOMIQA token?", ZH: "What is the $NOMIQA token?", JA: "What is the $NOMIQA token?", PT: "What is the $NOMIQA token?", AR: "What is the $NOMIQA token?", HI: "What is the $NOMIQA token?" },
  faq9A: { EN: "The community token for nomiqa. Stake to earn rewards and governance rights.", ES: "The community token for nomiqa. Stake to earn rewards and governance rights.", FR: "The community token for nomiqa. Stake to earn rewards and governance rights.", DE: "The community token for nomiqa. Stake to earn rewards and governance rights.", RU: "The community token for nomiqa. Stake to earn rewards and governance rights.", ZH: "The community token for nomiqa. Stake to earn rewards and governance rights.", JA: "The community token for nomiqa. Stake to earn rewards and governance rights.", PT: "The community token for nomiqa. Stake to earn rewards and governance rights.", AR: "The community token for nomiqa. Stake to earn rewards and governance rights.", HI: "The community token for nomiqa. Stake to earn rewards and governance rights." },
  faq10Q: { EN: "Can I get a refund?", ES: "Can I get a refund?", FR: "Can I get a refund?", DE: "Can I get a refund?", RU: "Can I get a refund?", ZH: "Can I get a refund?", JA: "Can I get a refund?", PT: "Can I get a refund?", AR: "Can I get a refund?", HI: "Can I get a refund?" },
  faq10A: { EN: "Due to the instant delivery nature of eSIMs, all sales are final.", ES: "Due to the instant delivery nature of eSIMs, all sales are final.", FR: "Due to the instant delivery nature of eSIMs, all sales are final.", DE: "Due to the instant delivery nature of eSIMs, all sales are final.", RU: "Due to the instant delivery nature of eSIMs, all sales are final.", ZH: "Due to the instant delivery nature of eSIMs, all sales are final.", JA: "Due to the instant delivery nature of eSIMs, all sales are final.", PT: "Due to the instant delivery nature of eSIMs, all sales are final.", AR: "Due to the instant delivery nature of eSIMs, all sales are final.", HI: "Due to the instant delivery nature of eSIMs, all sales are final." },

  // Footer
  footerTagline: { EN: "nomiqa — where privacy meets connection.", ES: "nomiqa — where privacy meets connection.", FR: "nomiqa — where privacy meets connection.", DE: "nomiqa — where privacy meets connection.", RU: "nomiqa — where privacy meets connection.", ZH: "nomiqa — where privacy meets connection.", JA: "nomiqa — where privacy meets connection.", PT: "nomiqa — where privacy meets connection.", AR: "nomiqa — where privacy meets connection.", HI: "nomiqa — where privacy meets connection." },
  footerSubtagline: { EN: "Powered by the people. Built for the borderless.", ES: "Powered by the people. Built for the borderless.", FR: "Powered by the people. Built for the borderless.", DE: "Powered by the people. Built for the borderless.", RU: "Powered by the people. Built for the borderless.", ZH: "Powered by the people. Built for the borderless.", JA: "Powered by the people. Built for the borderless.", PT: "Powered by the people. Built for the borderless.", AR: "Powered by the people. Built for the borderless.", HI: "Powered by the people. Built for the borderless." },
  products: { EN: "Products", ES: "Products", FR: "Products", DE: "Products", RU: "Products", ZH: "Products", JA: "Products", PT: "Products", AR: "Products", HI: "Products" },
  company: { EN: "Company", ES: "Company", FR: "Company", DE: "Company", RU: "Company", ZH: "Company", JA: "Company", PT: "Company", AR: "Company", HI: "Company" },
  support: { EN: "Support", ES: "Support", FR: "Support", DE: "Support", RU: "Support", ZH: "Support", JA: "Support", PT: "Support", AR: "Support", HI: "Support" },
  
  // Common
  privacy: { EN: "Privacy", ES: "Privacy", FR: "Privacy", DE: "Privacy", RU: "Privacy", ZH: "Privacy", JA: "Privacy", PT: "Privacy", AR: "Privacy", HI: "Privacy" },
  about: { EN: "About", ES: "About", FR: "About", DE: "About", RU: "About", ZH: "About", JA: "About", PT: "About", AR: "About", HI: "About" },
};

export const TranslationProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("preferredLanguage");
    return (saved as Language) || "EN";
  });

  useEffect(() => {
    localStorage.setItem("preferredLanguage", language);
  }, [language]);

  const t = (key: string): string => {
    return translations[key]?.[language] || key;
  };

  return (
    <TranslationContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </TranslationContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(TranslationContext);
  if (!context) {
    throw new Error("useTranslation must be used within a TranslationProvider");
  }
  return context;
};
